/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// jTextFieldIdNota
package view.dialog;

import enums.SituacaoEnum;
//import Interface.Tela.ExpedicaoJIF;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import model.NotaFiscal;
import service.NotaFiscalService;
import utils.DataHoraAtual;
import utils.FormatarData;
import utils.StringToDate;

/**
 *
 * @author DNA
 */
public class JDialogExpedicao extends javax.swing.JDialog {

    NotaFiscal nota;

    public JDialogExpedicao(java.awt.Frame parent, boolean modal, NotaFiscal notaFiscal) {
        super(parent, modal);
        initComponents();
        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(SituacaoEnum.values()));
        cbSituacao.setRenderer(new SituacaoEnumRenderer());
        nota = new NotaFiscal();
        nota = notaFiscal;
        setaValoresNosCampos(notaFiscal);

    }

    private JDialogExpedicao(JFrame jFrame, boolean b) {

        initComponents();
        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(SituacaoEnum.values()));
        cbSituacao.setRenderer(new SituacaoEnumRenderer());

    }

    class SituacaoEnumRenderer extends javax.swing.DefaultListCellRenderer {

        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (value instanceof SituacaoEnum) {
                value = ((SituacaoEnum) value).getValorDescricao();
            }
            return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Tipo_Fornecedor = new javax.swing.JLabel();
        jLabel_Fornecedor = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();
        txtOsNOta = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        dcDataNota = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        cbSituacao = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNotaNumero = new javax.swing.JTextField();
        jLabelData3 = new javax.swing.JLabel();
        txtChaveNota = new javax.swing.JTextField();
        jLabelData4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotaObservacao = new javax.swing.JTextArea();
        jButtonEnvAgo = new javax.swing.JButton();
        jButtonEnvHoj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel_IdNota = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vol_uf = new javax.swing.JTextField();
        vol_placa = new javax.swing.JTextField();
        vol_motorista = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vol_quantidade = new javax.swing.JTextField();
        vol_especie = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        vol_peso_bruto = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        vol_numeracao = new javax.swing.JTextField();
        vol_peso_liquido = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expedição rapida");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Tipo_Fornecedor.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel_Tipo_Fornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tipo_Fornecedor.setText(" ");
        jLabel_Tipo_Fornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Fornecedor.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel_Fornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Fornecedor.setText(" ");
        jLabel_Fornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelData1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData1.setText("OS");

        txtOsNOta.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtOsNOta.setEnabled(false);

        jLabelData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setText("DATA EXPEDIÇÃO");

        dcDataNota.setDateFormatString("dd'/'MM'/'yyyy");
        dcDataNota.setEnabled(false);
        dcDataNota.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        dcDataNota.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                dcDataNotaHierarchyChanged(evt);
            }
        });
        dcDataNota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dcDataNotaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                dcDataNotaAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dcDataNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcDataNotaMouseClicked(evt);
            }
        });
        dcDataNota.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcDataNotaPropertyChange(evt);
            }
        });
        dcDataNota.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                dcDataNotaVetoableChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HORA");

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setEnabled(false);
        txtHora.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFocusLost(evt);
            }
        });
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
        });

        cbSituacao.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SITUAÇÃO");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DOCUMENTO NOTA N°:");

        txtNotaNumero.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtNotaNumero.setEnabled(false);
        txtNotaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaNumeroActionPerformed(evt);
            }
        });

        jLabelData3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelData3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData3.setText("CHAVE  NOTA");

        txtChaveNota.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtChaveNota.setEnabled(false);
        txtChaveNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaveNotaActionPerformed(evt);
            }
        });

        jLabelData4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelData4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData4.setText("OBSERVAÇÃO");

        txtNotaObservacao.setColumns(20);
        txtNotaObservacao.setLineWrap(true);
        txtNotaObservacao.setRows(5);
        txtNotaObservacao.setEnabled(false);
        jScrollPane1.setViewportView(txtNotaObservacao);

        jButtonEnvAgo.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonEnvAgo.setText("Enviado agora");
        jButtonEnvAgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvAgoActionPerformed(evt);
            }
        });

        jButtonEnvHoj.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonEnvHoj.setText("Enviado hoje");
        jButtonEnvHoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvHojActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("Lançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButtonAlterar.setText("Editar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel_IdNota.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel_IdNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_IdNota.setText(" ");
        jLabel_IdNota.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Placa Veiculo");

        vol_uf.setEnabled(false);
        vol_uf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_ufFocusLost(evt);
            }
        });

        vol_placa.setEnabled(false);
        vol_placa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_placaFocusLost(evt);
            }
        });
        vol_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vol_placaKeyReleased(evt);
            }
        });

        vol_motorista.setEnabled(false);
        vol_motorista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vol_motoristaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_motoristaFocusLost(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Motorista :");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("UF");

        vol_quantidade.setEnabled(false);

        vol_especie.setEnabled(false);
        vol_especie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_especieFocusLost(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Espécie");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Peso Bruto");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Numeração");

        vol_peso_bruto.setEnabled(false);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Peso Liquido");

        vol_numeracao.setEnabled(false);
        vol_numeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vol_numeracaoActionPerformed(evt);
            }
        });

        vol_peso_liquido.setEnabled(false);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Quantidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Tipo_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_IdNota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOsNOta)
                            .addComponent(jLabelData1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcDataNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNotaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonEnvAgo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEnvHoj)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vol_motorista, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vol_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vol_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelData3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtChaveNota))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(vol_quantidade, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vol_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vol_numeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vol_peso_bruto)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vol_peso_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelData4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButtonAlterar, jButtonEnvAgo, jButtonEnvHoj});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tipo_Fornecedor)
                    .addComponent(jLabel_Fornecedor)
                    .addComponent(jLabel_IdNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtOsNOta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcDataNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData3)
                    .addComponent(txtChaveNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelData4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel25))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vol_peso_bruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_peso_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_numeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vol_motorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnvAgo)
                    .addComponent(jButtonEnvHoj)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, jLabelData, jLabelData1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbSituacao, dcDataNota, txtHora, txtOsNOta});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, txtNotaNumero});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelData3, txtChaveNota});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel19, jLabel21, jLabel28});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel23, jLabel25, jLabel26, jLabel27, jLabel30});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButtonAlterar, jButtonEnvAgo, jButtonEnvHoj, vol_especie, vol_motorista, vol_numeracao, vol_peso_bruto, vol_peso_liquido, vol_placa, vol_quantidade, vol_uf});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dcDataNotaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_dcDataNotaHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dcDataNotaHierarchyChanged

    private void dcDataNotaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dcDataNotaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dcDataNotaAncestorMoved

    private void dcDataNotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dcDataNotaAncestorAdded
        //  jFormattedTextFieldHora.requestFocus();
    }//GEN-LAST:event_dcDataNotaAncestorAdded

    private void dcDataNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcDataNotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dcDataNotaMouseClicked

    private void dcDataNotaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcDataNotaPropertyChange
        //  jFormattedTextFieldHora.requestFocus();
    }//GEN-LAST:event_dcDataNotaPropertyChange

    private void dcDataNotaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_dcDataNotaVetoableChange

    }//GEN-LAST:event_dcDataNotaVetoableChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            nota.setId_nota(Integer.parseInt(txtOsNOta.getText()));
            nota.setNota_data(FormatarData.formatarData(dcDataNota.getDate()));
            nota.setNota_hora(txtHora.getText());
            SituacaoEnum situacaoEnum = (SituacaoEnum) cbSituacao.getSelectedItem();
            nota.setNota_situacao(situacaoEnum.getNome());

            nota.setNota_nota(txtNotaNumero.getText());
            nota.setNota_chave(txtChaveNota.getText());
            nota.setNota_observacao(txtNotaObservacao.getText());

            nota.getTransporteModel().setMotorista(vol_motorista.getText());
            nota.getTransporteModel().setPlaca(vol_placa.getText());
            nota.getTransporteModel().setUf(vol_uf.getText());

            nota.getTransporteModel().setQuantidade(vol_quantidade.getText());
            nota.getTransporteModel().setEspecie(vol_especie.getText());
            nota.getTransporteModel().setPesobruto(vol_peso_bruto.getText());
            nota.getTransporteModel().setPesoliquido(vol_peso_liquido.getText());
            nota.getTransporteModel().setMotorista(vol_motorista.getText());
            nota.getTransporteModel().setNumeracao(vol_numeracao.getText());

            NotaFiscalService notaFiscalService = new NotaFiscalService();
            notaFiscalService.expedirNotaFiscal(nota);
            this.dispose();
        } catch (Exception e) {
            System.out.println("erro ao executar expedição ::: " + e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtHoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusGained
    }//GEN-LAST:event_txtHoraFocusGained

    private void txtHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusLost
    }//GEN-LAST:event_txtHoraFocusLost

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //   jTextFieldNota.requestFocus();
        }
    }//GEN-LAST:event_txtHoraKeyPressed

    private void jButtonEnvAgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvAgoActionPerformed
        cbSituacao.setSelectedItem(SituacaoEnum.ENVIADO);
        txtHora.setText(DataHoraAtual.obterHoraFormatada());
        dcDataNota.setDate(StringToDate.deStringParaData(DataHoraAtual.obterDataFormatada()));
    }//GEN-LAST:event_jButtonEnvAgoActionPerformed

    private void txtNotaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaNumeroActionPerformed

    private void txtChaveNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaveNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaveNotaActionPerformed

    private void jButtonEnvHojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvHojActionPerformed
        cbSituacao.setSelectedItem(SituacaoEnum.ENVIADO);

        dcDataNota.setDate(StringToDate.deStringParaData(DataHoraAtual.obterDataFormatada()));

    }//GEN-LAST:event_jButtonEnvHojActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        if (dcDataNota.isEnabled()) {
            liberaCampos(false);
        } else {
            liberaCampos(true);
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        if (jTextFieldIdNota.getText().isEmpty()) {
//        } else {
//        iniciaFormualario();
//        }

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        ExpedicaoJIF.jButton1.doClick();
    }//GEN-LAST:event_formWindowClosing

    private void vol_ufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_ufFocusLost
//        AjustaMinhaUf();
        vol_uf.setText(vol_uf.getText().toUpperCase());
    }//GEN-LAST:event_vol_ufFocusLost

    private void vol_placaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_placaFocusLost
        //aqui
//        AjustaMinhaPlaca();
        vol_placa.setText(vol_placa.getText().toUpperCase());
    }//GEN-LAST:event_vol_placaFocusLost

    private void vol_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vol_placaKeyReleased
//        AjustaMinhaPlaca();
    }//GEN-LAST:event_vol_placaKeyReleased

    private void vol_motoristaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_motoristaFocusGained
        //        vol_motorista.setBackground(Color.cyan);
    }//GEN-LAST:event_vol_motoristaFocusGained

    private void vol_motoristaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_motoristaFocusLost
        vol_motorista.setText(vol_motorista.getText().toUpperCase());
        vol_motorista.setBackground(Color.WHITE);
    }//GEN-LAST:event_vol_motoristaFocusLost

    private void vol_especieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_especieFocusLost
        vol_especie.setText(vol_especie.getText().toUpperCase());
    }//GEN-LAST:event_vol_especieFocusLost

    private void vol_numeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vol_numeracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vol_numeracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogExpedicao dialog = new JDialogExpedicao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setaValoresNosCampos(NotaFiscal notaFiscal) {
        txtOsNOta.setText("" + notaFiscal.getId_nota());
        txtHora.setText(notaFiscal.getNota_hora());
        txtNotaNumero.setText(notaFiscal.getNota_nota());
        txtChaveNota.setText(notaFiscal.getNota_chave());
        txtNotaObservacao.setText(notaFiscal.getNota_observacao());
        vol_quantidade.setText(notaFiscal.getTransporteModel().getQuantidade());
        vol_especie.setText(notaFiscal.getTransporteModel().getEspecie());
        vol_numeracao.setText(notaFiscal.getTransporteModel().getNumeracao());
        vol_peso_bruto.setText(notaFiscal.getTransporteModel().getPesobruto());
        vol_peso_liquido.setText(notaFiscal.getTransporteModel().getPesoliquido());
        vol_motorista.setText(notaFiscal.getTransporteModel().getMotorista());
        vol_placa.setText(notaFiscal.getTransporteModel().getPlaca());
        vol_uf.setText(notaFiscal.getTransporteModel().getUf());

        // Formato da data correspondente ao formato da string
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Convertendo a string para um objeto Date
            Date dataNota = formatoData.parse(notaFiscal.getNota_data());

            // Configurando a data no componente JDateChooser
            dcDataNota.setDate(dataNota);

        } catch (ParseException e) {
            e.printStackTrace(); // Trate a exceção apropriadamente
        }

        // Loop para encontrar o enum correspondente à string
        for (SituacaoEnum situacaoEnum : SituacaoEnum.values()) {
            if (situacaoEnum.getNome().equals(notaFiscal.getNota_situacao())) {
                // Configurar o item encontrado como selecionado no combobox
                cbSituacao.setSelectedItem(situacaoEnum);
                break; // Saia do loop após encontrar a correspondência
            }
        }

    }

    public void liberaCampos(boolean liberado) {
        dcDataNota.setEnabled(liberado);
        txtHora.setEnabled(liberado);
        cbSituacao.setEnabled(liberado);
        txtNotaNumero.setEnabled(liberado);
        txtChaveNota.setEnabled(liberado);
        txtNotaObservacao.setEnabled(liberado);
        vol_quantidade.setEnabled(liberado);
        vol_especie.setEnabled(liberado);
        vol_numeracao.setEnabled(liberado);
        vol_peso_bruto.setEnabled(liberado);
        vol_peso_liquido.setEnabled(liberado);
        vol_motorista.setEnabled(liberado);
        vol_placa.setEnabled(liberado);
        vol_uf.setEnabled(liberado);
    }

    public void bloqueiaCampos() {
        dcDataNota.setEnabled(false);
        txtHora.setEnabled(false);
        cbSituacao.setEnabled(false);
        txtNotaNumero.setEnabled(false);
        txtChaveNota.setEnabled(false);
        txtNotaObservacao.setEnabled(false);
//        jComboBoxDocumento.setEnabled(false);
        vol_quantidade.setEnabled(false);
        vol_especie.setEnabled(false);
        vol_numeracao.setEnabled(false);
        vol_peso_bruto.setEnabled(false);
        vol_peso_liquido.setEnabled(false);
        vol_motorista.setEnabled(false);
        vol_placa.setEnabled(false);
        vol_uf.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<SituacaoEnum> cbSituacao;
    private com.toedter.calendar.JDateChooser dcDataNota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonEnvAgo;
    private javax.swing.JButton jButtonEnvHoj;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelData3;
    private javax.swing.JLabel jLabelData4;
    private javax.swing.JLabel jLabel_Fornecedor;
    private javax.swing.JLabel jLabel_IdNota;
    private javax.swing.JLabel jLabel_Tipo_Fornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtChaveNota;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtNotaNumero;
    private javax.swing.JTextArea txtNotaObservacao;
    public static javax.swing.JTextField txtOsNOta;
    private javax.swing.JTextField vol_especie;
    private javax.swing.JTextField vol_motorista;
    private javax.swing.JTextField vol_numeracao;
    private javax.swing.JTextField vol_peso_bruto;
    private javax.swing.JTextField vol_peso_liquido;
    private javax.swing.JTextField vol_placa;
    private javax.swing.JTextField vol_quantidade;
    private javax.swing.JTextField vol_uf;
    // End of variables declaration//GEN-END:variables
}
