/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//// recebe
package Interface;

import Interface.Principal;
import ModeloBeans.Beans_ECFT;
import ModeloBeans.ModeloTabela;
import ConectaBanco.ConexaoBD;
import ModeloDao.Dao_ECFT;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Edson
 */
public class FCECadastroJIF extends javax.swing.JInternalFrame {

    Principal menu;
//    JIF_Cliente_Lista Produto_Lista;
    ConexaoBD conex = new ConexaoBD();
    Beans_ECFT BEANS = new Beans_ECFT();
    Dao_ECFT DAO = new Dao_ECFT();

    String cnpj;
    String cep;
    String telefone;

    String descricao = null;
    int ver = 1;

    int tipo_lista = 1;
    int id_referencia;

    String data;

    String nome = null;
    String armazena_tipo;
    String armazena_descricao;
    String armazena_edicao;
    String armazena_unidade;
    String armazena_valor;
    String armazena_ncm;
    String armazena_cfop;
    String armazena_estoque;
    String armazena_observacao;

    public FCECadastroJIF() {
        initComponents();
        remover_Ico();
        jLabel_Id.setVisible(false);
        jLabel1.setVisible(false);
//        jLabel_status.setVisible(false);
//        jLabel_Data_menu.setVisible(false);
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void remover_Ico() {
        this.setFrameIcon(null);

        // hack to remove system menu in Windows
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldInscricao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JTextField();
        jFormattedTextFieldTelefone = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JTextField();
        jComboBoxFC = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Observacao = new javax.swing.JTextArea();
        jLabel_Data_ent = new javax.swing.JLabel();
        jButton_Excluir = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Salvar = new javax.swing.JButton();
        jButton_Novo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Id = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Geral [Cliente/Fornecedore/Empresa/Transportadora]");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel14.setText("Descrição:");

        jLabel15.setText("* CNPJ:");
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel15MouseMoved(evt);
            }
        });
        jLabel15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel15FocusLost(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyPressed(evt);
            }
        });

        jTextFieldDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescricaoFocusLost(evt);
            }
        });
        jTextFieldDescricao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldDescricaoInputMethodTextChanged(evt);
            }
        });
        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyPressed(evt);
            }
        });

        jLabel16.setText("*Telefone:");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jTextFieldInscricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInscricaoFocusLost(evt);
            }
        });
        jTextFieldInscricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldInscricaoKeyPressed(evt);
            }
        });

        jLabel22.setText("Insc. Est.:");

        jFormattedTextFieldCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCnpjFocusLost(evt);
            }
        });

        jFormattedTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldTelefoneFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextFieldInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Endereço:");

        jLabel18.setText("No:");

        jLabel19.setText("*Cep:");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setText("Complemento:");

        jLabel21.setText("Bairro:");

        jLabel23.setText("Cidade:");

        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });
        jTextFieldEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEnderecoKeyPressed(evt);
            }
        });

        jTextFieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFocusLost(evt);
            }
        });
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyPressed(evt);
            }
        });

        jTextFieldComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldComplementoFocusLost(evt);
            }
        });
        jTextFieldComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyPressed(evt);
            }
        });

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });
        jTextFieldBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyReleased(evt);
            }
        });

        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });
        jTextFieldCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCidadeKeyPressed(evt);
            }
        });

        jFormattedTextFieldCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCepFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldComplemento)))))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORN/CLIE", "FORNECEDOR", "CLIENTE", "OUTRO", "TRANSPORTE", "EMPRESA" }));
        jComboBoxFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFCKeyPressed(evt);
            }
        });

        jLabel24.setText("Tipo.:");

        jTextArea_Observacao.setColumns(20);
        jTextArea_Observacao.setRows(5);
        jTextArea_Observacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea_Observacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_ObservacaoFocusLost(evt);
            }
        });
        jTextArea_Observacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea_ObservacaoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Observacao);

        jLabel_Data_ent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Data_ent.setText("data");
        jLabel_Data_ent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Excluir.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Excluir.setText("Excluir");
        jButton_Excluir.setEnabled(false);
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.setEnabled(false);
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });
        jButton_Salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_SalvarKeyPressed(evt);
            }
        });

        jButton_Novo.setText("Novo");
        jButton_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NovoActionPerformed(evt);
            }
        });
        jButton_Novo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_NovoKeyPressed(evt);
            }
        });

        jLabel1.setText("Id :");

        jLabel_Id.setText("Novo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFC, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel_Data_ent, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Excluir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Cancelar, jButton_Excluir, jButton_Novo, jButton_Salvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel_Id))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel_Data_ent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Novo)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_Excluir))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxFC, jLabel24});

        jMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusGained(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Atualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Alterar Data");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator1);

        jMenuItem2.setText("Limpa Cnpj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Limpa Telefone");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setText("Limpa Cep");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        if (ver == 2) {
        } else {
//            iniciaFormulario();
//            preencherTabela();
//            ver = 2;
//            if (jLabel_Id.getText().equals("Novo")) {
//                jButton_Salvar.setText("Salvar");
//            } else {
//                jButton_Salvar.setText("Alterar");
//            }
//        }
//        if (jLabel_status.getText().equals("ATIVO")) {
//            jButton_Excluir.setText("Excluir");
//        } else {
//            jButton_Excluir.setText("Ativar");
        }
    }//GEN-LAST:event_formFocusGained

    private void LimparTabela() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        modelo.fireTableRowsDeleted(ERROR, ERROR);
//        jTable_Produto.setModel(modelo);

    }

    public void iniciaFormulario() {
//        jLabel_Data_menu.setText(menu.jLabelData.getText());
        if (jLabel_Id.getText() == "novo") {
            jLabel_Data_ent.setText(Principal.jLabel_Data.getText() + " " + Principal.jLabel_Hora.getText());
            jTextFieldNome.setText("");
            jTextFieldDescricao.setText("");
            jFormattedTextFieldCnpj.setText("");
            jFormattedTextFieldTelefone.setText("");
            jTextArea_Observacao.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNumero.setText("");
            jFormattedTextFieldCep.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldInscricao.setText("");
            jComboBoxFC.setSelectedItem("FORN/CLIE");
            jButton_Excluir.setEnabled(false);
//            LimparTabela();
            jTextFieldNome.requestFocus();
            TravaCampos();
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            this.setTitle("Cadastro Geral [Cliente/Fornecedor/Empresa/Transportadora]");
        } else {
            conex.conexao();
            conex.executaSql("select * from ecft   where ecft_id = '" + jLabel_Id.getText() + "' order by ecft_id asc ");
            try {
                conex.rs.first();
//            jTextFieldCodCli.setText(String.valueOf(conex.rs.getInt("fc_id")));
                this.setTitle("Cadastro Geral [Cliente/Fornecedor/Empresa/Transportadora]    Id: " + (conex.rs.getString("sis_ecft")));
                jTextFieldNome.setText(conex.rs.getString("ecft_nome"));
                jTextFieldDescricao.setText(conex.rs.getString("ecft_descricao"));
                jComboBoxFC.setSelectedItem(conex.rs.getString("ecft_tipo"));
                jTextFieldInscricao.setText((conex.rs.getString("ecft_inscricao")));
                jTextFieldEndereco.setText(conex.rs.getString("ecft_endereco"));
                jTextFieldNumero.setText(conex.rs.getString("ecft_no"));
                jTextFieldComplemento.setText(conex.rs.getString("ecft_complemento"));
                jTextFieldBairro.setText(conex.rs.getString("ecft_bairro"));
                jTextFieldCidade.setText(conex.rs.getString("ecft_cidade"));
                jTextArea_Observacao.setText(conex.rs.getString("ecft_observacao"));
                // jLabel_status.setText((conex.rs.getString("ecft_status")));
                jLabel_Data_ent.setText((conex.rs.getString("ecft_registro")));
                id_referencia = ((conex.rs.getInt("sis_ecft")));
                cep = (conex.rs.getString("ecft_cep"));
                if (cep == ("  .   -   ")) {
                    jFormattedTextFieldCep.setText(null);
                } else {
                    jFormattedTextFieldCep.setText(cep);
                }
                cnpj = (conex.rs.getString("ecft_cnpj"));
                if (cnpj == ("  .   .   /    -  ")) {
                    jFormattedTextFieldCnpj.setText(null);
                } else {
                    jFormattedTextFieldCnpj.setText(cnpj);
                }
                telefone = (conex.rs.getString("ecft_telefone"));
                if (telefone == ("(  )    -    ")) {
                    jFormattedTextFieldTelefone.setText(null);
                } else {
                    jFormattedTextFieldTelefone.setText(telefone);
                }
                jButton_Novo.setEnabled(false);
                jButton_Salvar.setEnabled(true);
                jButton_Excluir.setEnabled(true);
                LiberaCampos();

            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(rootPane, "Erro ao iniciar formulario. \n" + ex);
                LimpaCampos();
                jButton_Novo.setEnabled(true);
                jButton_Salvar.setEnabled(false);
                jButton_Excluir.setEnabled(false);
            }
            conex.desconecta();

        }

    }

//    public void FechaForm() {
//        Component[] componentes1 = Produto_Lista.jPanel1.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes1) {
//            componente.setEnabled(true);
//            Produto_Lista.jTable_Produto.setEnabled(true);
//        }
//        Component[] componentes2 = Produto_Lista.jMenuBar1.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes2) {
//            componente.setEnabled(true);
//            Produto_Lista.jTable_Produto.setEnabled(true);
//        }
//        Produto_Lista.jButton_Alterar.setEnabled(false);
//        Produto_Lista.jButton_Excluir.setEnabled(false);
//        
//        Produto_Lista.jTextField_Busca.requestFocus(true);
////        Produto_Lista.jMenuBar1.requestFocus();
//    }

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
//        Component[] componentes = menu.Barra_Menu.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes) {
//            componente.setEnabled(true);
//        }
//        Component[] componentes2 = Painel_principal.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes2) {
//            componente.setEnabled(true);
//        }
        ver = 1;
//        FechaForm();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ver = 1;
//        FechaForm();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        iniciaFormulario();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null, "Você quer realmente alterar a data?\nVocê não tem permissão.");
        while (nome == null || nome.equals("")) {
            nome = JOptionPane.showInputDialog("Digite sua senha de acesso.");
            if (nome == null || nome.equals("")) {
                JOptionPane.showMessageDialog(null, "Você não digitou sua senha.");
                nome = "VAZIO";
            }
        }
//        JOptionPane.showMessageDialog(null, "Senha " + nome);
        if (nome.equals("123")) {
//            JDialog_Calendario calendario = new JDialog_Calendario(menu, rootPaneCheckingEnabled);
//            calendario.recebe_local("produto");
//            calendario.setVisible(true);
//            calendario.setResizable(false);
//            nome = null;
        } else {
            JOptionPane.showMessageDialog(null, "Acesso negado.");
            nome = null;
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    public void evento_Verifica() {
        if (jTextFieldDescricao.getText().isEmpty()) {
            jTextFieldDescricao.requestFocus();
            jTextFieldDescricao.setBackground(Color.red);
        } else {
            jTextFieldDescricao.setBackground(Color.white);
        }
        if (jTextFieldNome.getText().isEmpty()) {
            jTextFieldNome.requestFocus();
            jTextFieldNome.setBackground(Color.red);
        } else {
            jTextFieldNome.setBackground(Color.white);
        }

        if (jTextFieldNome.getText().isEmpty() | jTextFieldDescricao.getText().isEmpty()) {

        } else {
            evento_Salvar();
            jTextFieldNome.setBackground(Color.white);
            jTextFieldDescricao.setBackground(Color.white);
        }
//        MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//        MenuPrincipal.jButton_Meu_Foco.requestFocus();
    }

    public void evento_Salvar() {

        if (jLabel_Id.getText() == "novo") {
            inserirDados();
            DAO.Salvar(BEANS);
        } else {
            BEANS.setStecft(2);
            BEANS.setEcft_id(Integer.parseInt(jLabel_Id.getText()));
            DAO.Alterar(BEANS);
            inserirDados();
            DAO.Salvar(BEANS);

        }
//        this.dispose();
        jButton_Novo.setEnabled(true);
        jButton_Salvar.setEnabled(false);
        TravaCampos();
    }

    public void inserirDados() {

        BEANS.setEcft_nome(jTextFieldNome.getText());

        /////   .   .   /    -  
        if (jFormattedTextFieldCnpj.getText().equals("  .   .   /    -  ")) {
            BEANS.setEcft_cnpj("");
        } else {
            BEANS.setEcft_cnpj(jFormattedTextFieldCnpj.getText());
        }
        if (jFormattedTextFieldTelefone.getText().equals("(  )    -    ")) {
            BEANS.setEcft_telefone("");
        } else {
            BEANS.setEcft_telefone(jFormattedTextFieldTelefone.getText());
        }
        if (jFormattedTextFieldCep.getText().equals("  .   -   ")) {
            BEANS.setEcft_cep("");
        } else {
            BEANS.setEcft_cep(jFormattedTextFieldCep.getText());
        }
        BEANS.setEcft_descricao(jTextFieldDescricao.getText());
        BEANS.setEcft_tipo((String) jComboBoxFC.getSelectedItem());
        BEANS.setEcft_endereco(jTextFieldEndereco.getText());
        BEANS.setEcft_no(jTextFieldNumero.getText());
        BEANS.setEcft_complemento(jTextFieldComplemento.getText());
        BEANS.setEcft_bairro(jTextFieldBairro.getText());
        BEANS.setEcft_cidade(jTextFieldCidade.getText());
        BEANS.setEcft_inscricao(jTextFieldInscricao.getText());
        BEANS.setEcft_observacao(jTextArea_Observacao.getText());
        BEANS.setSis_EFCT(id_referencia);// aqui puxa referencia
        BEANS.setEcft_usuario(Principal.jLabelNomeUsuario.getText());
//        BEANS.setEcft_status(jLabel_status.getText());
        BEANS.setStecft(1);
        BEANS.setEcft_registro(Principal.jLabel_Data.getText()+" "+Principal.jLabel_Hora.getText());
    }


    private void jMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusGained
        iniciaFormulario();
    }//GEN-LAST:event_jMenuBar1FocusGained

    private void jButton_NovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_NovoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_NovoKeyPressed

    private void jButton_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NovoActionPerformed
        EventoBotaoNovo();
    }//GEN-LAST:event_jButton_NovoActionPerformed

    public void EventoBotaoNovo() {
        CarregaUltimo();
        LiberaCampos();
        jButton_Novo.setEnabled(false);
        jButton_Salvar.setEnabled(true);
        jComboBoxFC.requestFocus();
        jLabel_Data_ent.setText(Principal.jLabel_Data.getText() + " " + Principal.jLabel_Hora.getText());

        this.setTitle("Cadastro Geral [Cliente/Fornecedore/Empresa/Transportadora]    Id: " + id_referencia);
    }

    public void TravaCampos() {
        jTextFieldNome.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jFormattedTextFieldCnpj.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextArea_Observacao.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(false);
        jTextFieldComplemento.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);;
        jTextFieldInscricao.setEnabled(false);
        jComboBoxFC.setEnabled(false);
        jButton_Excluir.setEnabled(false);
    }

    public void LiberaCampos() {
        jTextFieldNome.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jFormattedTextFieldCnpj.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextArea_Observacao.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);;
        jTextFieldInscricao.setEnabled(true);
        jComboBoxFC.setEnabled(true);

    }

    public void CarregaUltimo() {
        conex.conexao();
        conex.executaSql2("SELECT  sis_ecft  FROM ecft where sis_ecft is not null and sis_ecft !=0 order by sis_ecft asc");
        try {
            conex.rs.last();
            id_referencia = conex.rs.getInt("sis_ecft");
//            JOptionPane.showMessageDialog(rootPane, id_referencia);
            id_referencia = id_referencia + 1;
//            JOptionPane.showMessageDialog(rootPane, id_referencia);
        } catch (SQLException ex) {
//            Logger.getLogger(UnidadeJIF.class.getName()).log(Level.SEVERE, null, ex);
            id_referencia = 1;
        }
//        JOptionPane.showMessageDialog(rootPane, id_referencia);
        conex.desconecta();
    }

    private void jButton_SalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_SalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            Principal.jButton_Meu_Foco.setText("lec2");
//           Principal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            evento_Verifica();
        }
    }//GEN-LAST:event_jButton_SalvarKeyPressed

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        ver = 1;
        evento_Verifica();
        LimpaCampos();
//        Principal.jLabelCodigoTela.setText("FCEListaAtualizar");
//        Principal.jButton1.doClick();
        Principal.jLabelCodigoTela.setText("AtualizaTudo");
      Principal.jButton1.doClick();
      FCEListaJIF.jButtonPesquisar.doClick();

    }//GEN-LAST:event_jButton_SalvarActionPerformed

    public void LimpaCampos() {

        jTextFieldNome.setText("");
        jTextFieldDescricao.setText("");
        jFormattedTextFieldCnpj.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldInscricao.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jFormattedTextFieldCep.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jComboBoxFC.setSelectedItem("FORN/CLIE");
    }

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        if (jLabel_Id.getText() == "Novo") {

            jTextFieldNome.setText("");
            jTextFieldDescricao.setText("");
            jFormattedTextFieldCnpj.setText("");
            jFormattedTextFieldTelefone.setText("");
            jTextFieldInscricao.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNumero.setText("");
            jFormattedTextFieldCep.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jComboBoxFC.setSelectedItem("FORN/CLIE");

        } else {
            //            this.dispose();
            iniciaFormulario();
        }

    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir/ativar ? ");
        if (resposta == JOptionPane.YES_OPTION) {
            BEANS.setStecft(3);
            BEANS.setEcft_usuario(Principal.jLabelNomeUsuario.getText());
            BEANS.setEcft_registro(Principal.jLabel_Data.getText());
            BEANS.setEcft_id(Integer.parseInt(jLabel_Id.getText()));
            DAO.Excluir(BEANS);
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            Principal.jLabelCodigoTela.setText("FCEListaAtualizar");
            Principal.jButton1.doClick();
            Principal.jLabelCodigoTela.setText("FechaFCECadastroEditar");
            Principal.jButton1.doClick();
        }

//        iniciaFormulario();

    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTextArea_ObservacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_ObservacaoFocusLost
        jTextArea_Observacao.setText(jTextArea_Observacao.getText().toUpperCase());
        if (jTextArea_Observacao.getText().length() > 160) {
            jTextArea_Observacao.requestFocus();
            jTextArea_Observacao.setBackground(Color.red);
        } else {
            jTextArea_Observacao.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextArea_ObservacaoFocusLost

    private void jComboBoxFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFCKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldNome.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
    }//GEN-LAST:event_jComboBoxFCKeyPressed

    private void jTextFieldCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeKeyPressed

        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            jButton_Salvar.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            //            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }

        if (jTextFieldCidade.getText().length() > 130) {
            jTextFieldCidade.requestFocus();
            jTextFieldCidade.setBackground(Color.red);
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCidadeKeyPressed

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
        if (jTextFieldCidade.getText().length() > 130) {
            jTextFieldCidade.requestFocus();
            jTextFieldCidade.setBackground(Color.red);
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jTextFieldBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroKeyReleased

    private void jTextFieldBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldComplemento.requestFocus();
        }

        if (jTextFieldBairro.getText().length() > 130) {
            jTextFieldBairro.requestFocus();
            jTextFieldBairro.setBackground(Color.red);
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldBairroKeyPressed

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
        if (jTextFieldBairro.getText().length() > 130) {
            jTextFieldBairro.requestFocus();
            jTextFieldBairro.setBackground(Color.red);
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldComplementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jFormattedTextFieldCep.requestFocus();
        }

        if (jTextFieldComplemento.getText().length() > 140) {
            jTextFieldComplemento.requestFocus();
            jTextFieldComplemento.setBackground(Color.red);
        } else {
            jTextFieldComplemento.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldComplementoKeyPressed

    private void jTextFieldComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldComplementoFocusLost
        jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
        if (jTextFieldComplemento.getText().length() > 140) {
            jTextFieldComplemento.requestFocus();
            jTextFieldComplemento.setBackground(Color.red);
        } else {
            jTextFieldComplemento.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldComplementoFocusLost

    private void jTextFieldNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFormattedTextFieldCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jFormattedTextFieldCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldEndereco.requestFocus();
        }
        if (jTextFieldNumero.getText().length() > 20) {
            jTextFieldNumero.requestFocus();
            jTextFieldNumero.setBackground(Color.red);
        } else {
            jTextFieldNumero.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyPressed

    private void jTextFieldEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jTextFieldNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jTextFieldNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jFormattedTextFieldTelefone.requestFocus();
        }

        if (jTextFieldEndereco.getText().length() > 155) {
            jTextFieldEndereco.requestFocus();
            jTextFieldEndereco.setBackground(Color.red);
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEnderecoKeyPressed

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
        if (jTextFieldEndereco.getText().length() > 155) {
            jTextFieldEndereco.requestFocus();
            jTextFieldEndereco.setBackground(Color.red);
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldInscricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInscricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldDescricao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldDescricao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jFormattedTextFieldCnpj.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldInscricaoKeyPressed

    private void jTextFieldInscricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldInscricaoFocusLost
//        jTextFieldInscricao.setText(jTextFieldInscricao.getText().toUpperCase());
        AjustaMeuInscricaoEstadual();
        //206.277.405.117
    }//GEN-LAST:event_jTextFieldInscricaoFocusLost

    private void jTextFieldDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldDescricao.setText(jTextFieldDescricao.getText().toUpperCase());
            jFormattedTextFieldTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldDescricao.setText(jTextFieldDescricao.getText().toUpperCase());
            jFormattedTextFieldTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldDescricao.setText(jTextFieldDescricao.getText().toUpperCase());
            jTextFieldInscricao.requestFocus();
        }

        if (jTextFieldDescricao.getText().length() > 155) {
            jTextFieldDescricao.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyPressed

    private void jTextFieldDescricaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoInputMethodTextChanged

    private void jTextFieldDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoFocusLost
        jTextFieldDescricao.setText(jTextFieldDescricao.getText().toUpperCase());
        if (jTextFieldDescricao.getText().length() > 155) {
            jTextFieldDescricao.requestFocus();
            jTextFieldDescricao.setBackground(Color.red);
            // JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        } else {
            jTextFieldDescricao.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldDescricaoFocusLost

    private void jTextFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            jButton_Novo.setEnabled(true);
            jButton_Salvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
            jFormattedTextFieldCnpj.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
            jComboBoxFC.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
            jFormattedTextFieldCnpj.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_SPACE) {
            //            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
        }

        if (jTextFieldNome.getText().length() > 30) {
            jTextFieldNome.requestFocus();
            jTextFieldNome.setBackground(Color.red);
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNomeKeyPressed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
        if (jTextFieldNome.getText().length() > 30) {
            jTextFieldNome.requestFocus();
            jTextFieldNome.setBackground(Color.red);
//            JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    public void VerificaMeuCnpj() {
        String MeuTexto = jFormattedTextFieldCnpj.getText();
        if (MeuTexto.equals("")) {
            System.out.println("jFormattedTextFieldCnpj        ERRO");
        } else if (MeuTexto.equals("  .   .   /    -  ")) {
            System.out.println("jFormattedTextFieldCnpj   2");
            jFormattedTextFieldCnpj.setText(cnpj);
        } else {
            jFormattedTextFieldCnpj.setText(null);
            System.out.println("jFormattedTextFieldCnpj        Normal");
        }
    }

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
//        jFormattedTextFieldCnpj.setText(null);
// jLabel15.setBackground(Color.green);
// jLabel15.setForeground(Color.green);
        VerificaMeuCnpj();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusLost
        jLabel15.setBackground(Color.green);
    }//GEN-LAST:event_jLabel15FocusLost

    private void jLabel15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusGained
// jLabel15.setBackground(null);
// System.out.println("RECEBI O FOCO1");
    }//GEN-LAST:event_jLabel15FocusGained

    private void jLabel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseMoved
//       jLabel15.setBackground(Color.yellow);
//        System.out.println("RECEBI O FOCO2");
//         jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseMoved

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
// jLabel15.setBackground(Color.yellow);
//        System.out.println("RECEBI O FOCO3");
//        jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        VerificaMeuTelefone();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        VerificaMeuCep();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VerificaMeuCnpj();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VerificaMeuTelefone();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        VerificaMeuCep();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jFormattedTextFieldCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCnpjFocusLost
        AjustaMeuCnpj();
    }//GEN-LAST:event_jFormattedTextFieldCnpjFocusLost

    private void jFormattedTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneFocusLost
        AjustaMeuTelefone();
    }//GEN-LAST:event_jFormattedTextFieldTelefoneFocusLost

    private void jFormattedTextFieldCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepFocusLost
        AjustaMeuCep();
    }//GEN-LAST:event_jFormattedTextFieldCepFocusLost

    private void jTextArea_ObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_ObservacaoKeyPressed
        if (jTextArea_Observacao.getText().length() > 160) {
            jTextArea_Observacao.requestFocus();
            jTextArea_Observacao.setBackground(Color.red);
        } else {
            jTextArea_Observacao.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextArea_ObservacaoKeyPressed

    private void jTextFieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFocusLost
        if (jTextFieldNumero.getText().length() > 20) {
            jTextFieldNumero.requestFocus();
            jTextFieldNumero.setBackground(Color.red);
        } else {
            jTextFieldNumero.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNumeroFocusLost

    public void AjustaMeuCnpj() {
        String s = jFormattedTextFieldCnpj.getText().replace(".", "").replace("/", "").replace("-", "");
        if (s.isEmpty()) {
            jFormattedTextFieldCnpj.setBackground(Color.white);
            System.err.println("    erro   < 1");
        } else {
            if (s.matches("^[a-zA-ZÁÂÃÀÇÉÊÍÓÔÕÚÜáâãàçéêíóôõúü]*$")) {
                System.out.println("Ajuste deu ................................ERRRROOOOOOOO");
                jFormattedTextFieldCnpj.setBackground(Color.red);
            } else if (s.length() > 18) {
                System.err.println(" erro     18");
//            jFormattedTextFieldCnpj.setText("");
                jFormattedTextFieldCnpj.setBackground(Color.red);
                jFormattedTextFieldCnpj.requestFocus();
            } else if (s.length() > 14) {
                System.err.println("  erro     15 ");
//            jFormattedTextFieldCnpj.setText("");
                jFormattedTextFieldCnpj.setBackground(Color.red);
                jFormattedTextFieldCnpj.requestFocus();
            } else if (s.matches(
                    "^[0-9]*$")) {
                if (s.length() == 14) {
                    String formatado
                            = s.substring(0, 2) + "." + s.substring(2, 5) + "."
                            + s.substring(5, 8) + "/" + s.substring(8, 12) + "-" + s.substring(12, 14);
                    System.err.println("    ddddd   " + formatado); ////   33.113.309/0054−59
                    jFormattedTextFieldCnpj.setText(formatado);
                } else if (s.length() < 14) {
                } else if (s.length() > 14) {
//                jFormattedTextFieldCnpj.setBackground(Color.red);
//                jFormattedTextFieldCnpj.requestFocus();
//                System.err.println("     erro 14 ");

                } else {
                    System.err.println("    ddddd   erro");

                    jFormattedTextFieldCnpj.setText("");
                    jFormattedTextFieldCnpj.requestFocus();
                }
                jFormattedTextFieldCnpj.setBackground(Color.white);
            }
        }

    }

    public void AjustaMeuInscricaoEstadual() {
        String s = jTextFieldInscricao.getText().replace(".", "").replace(" ", "").replace("  ", "");
        if (s.isEmpty()) {
            jTextFieldInscricao.setBackground(Color.white);
            System.err.println("    erro   < 1");
        } else {
            if (s.matches("^[a-zA-ZÁÂÃÀÇÉÊÍÓÔÕÚÜáâãàçéêíóôõúü]*$")) {
                System.out.println("Ajuste deu ................................ERRRROOOOOOOO");
                jTextFieldInscricao.setBackground(Color.red);
            } else if (s.length() > 18) {
                System.err.println(" erro     18");
//            jFormattedTextFieldCnpj.setText("");
                jTextFieldInscricao.setBackground(Color.red);
                jTextFieldInscricao.requestFocus();
            } else if (s.length() > 12) {
                System.err.println("  erro     15 ");
                jTextFieldInscricao.setBackground(Color.red);
                jTextFieldInscricao.requestFocus();
            } else if (s.matches(
                    "^[0-9]*$")) {
                if (s.length() == 12) {
                    String formatado
                            = s.substring(0, 3) + "." + s.substring(3, 6) + "."
                            + s.substring(6, 9) + "." + s.substring(9, 12);
                    System.err.println("    ddddd   " + formatado); // 206.277.405.117
                    jTextFieldInscricao.setText(formatado);
                } else if (s.length() < 12) {

                } else {
                    System.err.println("    ddddd   erro");

                    jTextFieldInscricao.setText("");
                    jTextFieldInscricao.requestFocus();
                }
                jTextFieldInscricao.setBackground(Color.white);
            }
        }

    }

    public void AjustaMeuCep() {
        String s = jFormattedTextFieldCep.getText().replace(".", "").replace("-", "");
        if (s.isEmpty()) {
            jFormattedTextFieldCep.setBackground(Color.white);
            System.err.println("    erro   < 1");
        } else {
            if (s.matches("^[a-zA-ZÁÂÃÀÇÉÊÍÓÔÕÚÜáâãàçéêíóôõúü]*$")) {
                System.out.println("Ajuste deu ................................ERRRROOOOOOOO");
                jFormattedTextFieldCep.setBackground(Color.red);
            } else if (s.length() > 18) {
                System.err.println(" erro     18");
//            jFormattedTextFieldCnpj.setText("");
                jFormattedTextFieldCep.setBackground(Color.red);
                jFormattedTextFieldCep.requestFocus();
            } else if (s.length() > 8) {
                System.err.println("  erro     15 ");
                jFormattedTextFieldCep.setBackground(Color.red);
                jFormattedTextFieldCep.requestFocus();
            } else if (s.matches(
                    "^[0-9]*$")) {
                if (s.length() == 8) {
                    String formatado = s.substring(0, 2) + "." + s.substring(2, 5) + "-" + s.substring(5, 8);
                    System.err.println("    ddddd   " + formatado); ////   06.415-240
                    System.err.println("    ddddd   " + formatado); // 206.277.405.117
                    jFormattedTextFieldCep.setText(formatado);
                } else if (s.length() < 8) {

                } else {
                    System.err.println("    ddddd   erro");

                    jFormattedTextFieldCep.setText("");
                    jFormattedTextFieldCep.requestFocus();
                }
                jFormattedTextFieldCep.setBackground(Color.white);
            }
        }

    }

    public void AjustaMeuTelefone() {
        String s = jFormattedTextFieldTelefone.getText().replace("-", "").replace("(", "").replace(")", "").replace(".", "");
        if (s.isEmpty()) { jFormattedTextFieldTelefone.setBackground(Color.white);
        } else if (s.matches("^[a-zA-ZÁÂÃÀÇÉÊÍÓÔÕÚÜáâãàçéêíóôõúü]*$")) {
            System.out.println("Ajuste deu ................................ERRRROOOOOOOO");
            jFormattedTextFieldTelefone.setBackground(Color.red);
        } else if (s.length() > 12) {
            System.err.println("    eeee   erro");
//            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldTelefone.requestFocus();
            jFormattedTextFieldTelefone.setBackground(Color.red);
        } else if (s.length() > 11) {
            System.err.println("    eeee   14    erro");
//            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldTelefone.requestFocus();
            jFormattedTextFieldTelefone.setBackground(Color.red);
        } else if (s.matches("^[0-9]*$")) {
//            String meu=jFormattedTextFieldTelefone.getText();
//            meu=meu.substring(11);
            if (s.length() == 10) {
                String formatado = "(" + s.substring(0, 2) + ")" + s.substring(2, 6) + "-" + s.substring(6, 10);
                System.err.println("    ddddd   " + formatado); ////   (11)4168-3085
                jFormattedTextFieldTelefone.setText(formatado);
            } else if (s.length() == 11) {
                String formatado = "(" + s.substring(0, 2) + ")" + s.substring(2, 3) + "." + s.substring(3, 7) + "-" + s.substring(7, 11);
                System.err.println("    (11)9 9999 9999   " + formatado); ////   (11)4168-3085
                jFormattedTextFieldTelefone.setText(formatado);
            } else if (s.length() < 10) {
            } else if (s.length() > 11) {
                System.err.println("    eeee   erro");

//                jFormattedTextFieldTelefone.setText(meu);
                jFormattedTextFieldTelefone.requestFocus();
            } else {
                System.err.println("    ddddd   erro");
//                jFormattedTextFieldTelefone.setText(meu);
                jFormattedTextFieldTelefone.requestFocus();
            }
            jFormattedTextFieldTelefone.setBackground(Color.white);
        }

    }

    public void VerificaMeuCep() {
        String MeuTexto = jFormattedTextFieldCep.getText();
        if (MeuTexto.equals("  .   -   ") | MeuTexto == ("  .   -   ") | MeuTexto == null) {
            System.out.println("jFormattedTextFieldCep    MeuTexto.equals(  .   -   )");
            jFormattedTextFieldCep.setText(cep);
        } else {
            jFormattedTextFieldCep.setText(null);
            System.out.println("jFormattedTextFieldCep        Normal");
        }
    }

    public void VerificaMeuTelefone() {
        String MeuTexto = jFormattedTextFieldTelefone.getText();
        if (MeuTexto.equals("(  )    -    ") | MeuTexto == ("(  )    -    ") | MeuTexto == null) {
            System.out.println("jFormattedTextFieldTelefone    MeuTexto.equals(\"(  )    -    \")");
            jFormattedTextFieldTelefone.setText(telefone);
        } else {
            jFormattedTextFieldTelefone.setText(null);
            System.out.println("jFormattedTextFieldTelefone        Normal");
        }
    }

    public void recebeId(String id) {
        jLabel_Id.setText(id);
    }

    public void recebe_Combo(String cb) {
        jComboBoxFC.setSelectedItem(cb);
    }

//    public void preencherTabela() {
//
//        ArrayList dados = new ArrayList();
//        String[] colunas = new String[]{"Id", "Status", "Nome", "Cnpj", "Descrição", "Telefone", "Tipo", "Registro", "Usuario", "Observação"};
//        conex.conexao();
//
//        conex.executaSql2("select * from forecli where fc_id =  '" + jLabel_Id.getText() + "' order by fc_id asc");
////        }
//        try {
//            conex.rs.first();
//            do {
//                dados.add(new Object[]{conex.rs.getInt("fc_id"), conex.rs.getString("status_forecli"), conex.rs.getString("fc_nome"),
//                    conex.rs.getString("fc_cnpj"), conex.rs.getString("fc_descricao"),
//                    conex.rs.getString("fc_telefone"), conex.rs.getString("fc_tipo"),
//                    conex.rs.getString("registro_forecli"), conex.rs.getString("usu_forecli"), conex.rs.getString("fc_observacao")
//                });
//            } while (conex.rs.next());
//        } catch (SQLException ex) {
////            JOptionPane.showMessageDialog(menu, ex);
//        }
//        ModeloTabela modelo = new ModeloTabela(dados, colunas);
//        jTable_Produto.setModel(modelo);
//        jTable_Produto.getColumnModel().getColumn(0).setPreferredWidth(80);
//        jTable_Produto.getColumnModel().getColumn(0).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(1).setPreferredWidth(100);
//        jTable_Produto.getColumnModel().getColumn(1).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(2).setPreferredWidth(150);
//        jTable_Produto.getColumnModel().getColumn(2).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(3).setPreferredWidth(150);
//        jTable_Produto.getColumnModel().getColumn(3).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(4).setPreferredWidth(280);
//        jTable_Produto.getColumnModel().getColumn(4).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(5).setPreferredWidth(150);
//        jTable_Produto.getColumnModel().getColumn(5).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(6).setPreferredWidth(100);
//        jTable_Produto.getColumnModel().getColumn(6).setResizable(true);
//        
//        jTable_Produto.getColumnModel().getColumn(7).setPreferredWidth(100);
//        jTable_Produto.getColumnModel().getColumn(7).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(8).setPreferredWidth(100);
//        jTable_Produto.getColumnModel().getColumn(8).setResizable(true);
//        jTable_Produto.getColumnModel().getColumn(9).setPreferredWidth(150);
//        jTable_Produto.getColumnModel().getColumn(9).setResizable(true);
////        jTable_Produto.getColumnModel().getColumn(10).setPreferredWidth(280);
////        jTable_Produto.getColumnModel().getColumn(10).setResizable(true);
//
//        jTable_Produto.getTableHeader().setReorderingAllowed(false);
//        jTable_Produto.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//        jTable_Produto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        
//        conex.desconecta();
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Novo;
    private javax.swing.JButton jButton_Salvar;
    public static javax.swing.JComboBox<String> jComboBoxFC;
    private javax.swing.JTextField jFormattedTextFieldCep;
    private javax.swing.JTextField jFormattedTextFieldCnpj;
    private javax.swing.JTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel_Data_ent;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_Observacao;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldInscricao;
    public static javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
