/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//// aqui serve pra buscar jlabel   jLabel_Data2 jLabel_Hora
package view;

import Interface.*;
import BackupRestore.Novo.PostgresBackup_X64NOV;
import BackupRestore.Novo.PostgresBackup_X86NOV;
import BackupRestore.Novo.PostgresRestore_X64NOV;
import BackupRestore.Novo.PostgresRestore_X86NOV;
import Sistema.ManipulaProtocolo;
import utils.ControleCores;
import utils.UsuarioLogado;
import extras.TelaInternaController;
import controller.MenuPrincipalController;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author edson
 */
public final class MenuPrincipal extends javax.swing.JFrame {

    MenuPrincipalController menuPrincipalController;

    String MenuMinhaData, MenuMinhaDataSistema, MenuMinhaHora;

    int SequenciadorA = 3, SequenciadorB = 7;
    String MinhaReferencia;

    public MenuPrincipal() {
        menuPrincipalController = new MenuPrincipalController();
        initComponents();

        MudaTitulo();
        HoraAtual();
        EscondeMenu();
        carregaPapelParede();
        menuPrincipalController.chamaLogin(this);
        System.out.println("Meu usuario::" + UsuarioLogado.getNome());

        pnPrincipal.setBackground(ControleCores.pegarCorPadrao());
        pnMenuInferior.setBackground(ControleCores.pegarCorPadrao());
        desktopPrincipal.setBackground(ControleCores.pegarCorPadrao());
        pnMenuPrincipal.setBackground(ControleCores.pegarCorPadrao());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenuPrincipal = new javax.swing.JPanel();
        pnMenuInferior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel_Hora = new javax.swing.JLabel();
        jLabel_Data = new javax.swing.JLabel();
        jLabel_Data2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelCodigoTela = new javax.swing.JLabel();
        jLabelCodigoTela2 = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Gerador_De_Codigo = new javax.swing.JLabel();
        desktopPrincipal = new javax.swing.JDesktopPane();
        pnPrincipal = new javax.swing.JPanel();
        lblPapelDeParede = new javax.swing.JLabel();
        jButton_Produto = new javax.swing.JButton();
        jButton_Nota = new javax.swing.JButton();
        jButton_Consulta = new javax.swing.JButton();
        jButton_Expedicao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem_EscondeMenu = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuChamaUnidade = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnMenuInferior.setBackground(new java.awt.Color(204, 204, 255));
        pnMenuInferior.setAlignmentX(0.0F);
        pnMenuInferior.setAlignmentY(0.0F);
        pnMenuInferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuInferiorMouseClicked(evt);
            }
        });

        jButton1.setText("Botão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_Hora.setFont(new java.awt.Font("Fira Sans", 3, 14)); // NOI18N
        jLabel_Hora.setText("00:00:00");

        jLabel_Data.setFont(new java.awt.Font("Fira Sans", 3, 14)); // NOI18N
        jLabel_Data.setText("00/00/0000");
        jLabel_Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_DataMouseClicked(evt);
            }
        });

        jLabel_Data2.setText("data");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelCodigoTela.setText("  ");
        jLabelCodigoTela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCodigoTela2.setText("  ");
        jLabelCodigoTela2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTipoUsuario.setFont(new java.awt.Font("Fira Sans", 3, 14)); // NOI18N
        jLabelTipoUsuario.setText("Administrador");

        jLabelNomeUsuario.setFont(new java.awt.Font("Fira Sans", 3, 14)); // NOI18N
        jLabelNomeUsuario.setText("Sistema");

        jLabel_Empresa.setText("0");

        jLabel_Gerador_De_Codigo.setText("  ");
        jLabel_Gerador_De_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Gerador_De_Codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Gerador_De_CodigoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMenuInferiorLayout = new javax.swing.GroupLayout(pnMenuInferior);
        pnMenuInferior.setLayout(pnMenuInferiorLayout);
        pnMenuInferiorLayout.setHorizontalGroup(
            pnMenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodigoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodigoTela2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Data2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Empresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Gerador_De_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnMenuInferiorLayout.setVerticalGroup(
            pnMenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuInferiorLayout.createSequentialGroup()
                .addGroup(pnMenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel_Hora)
                    .addComponent(jLabel_Data)
                    .addComponent(jLabel_Data2)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabelCodigoTela)
                    .addComponent(jLabelCodigoTela2)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(jLabelNomeUsuario)
                    .addComponent(jLabel_Empresa)
                    .addComponent(jLabel_Gerador_De_Codigo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        desktopPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        pnPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        lblPapelDeParede.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPapelDeParede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPapelDeParede.setMinimumSize(new java.awt.Dimension(1028, 772));
        lblPapelDeParede.setPreferredSize(new java.awt.Dimension(1028, 772));
        lblPapelDeParede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPapelDeParedeMouseClicked(evt);
            }
        });

        jButton_Produto.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jButton_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-produto-36.png"))); // NOI18N
        jButton_Produto.setText("Produto");
        jButton_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProdutoActionPerformed(evt);
            }
        });

        jButton_Nota.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jButton_Nota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-nota-fiscal-electrónica-36.png"))); // NOI18N
        jButton_Nota.setText("Nota");
        jButton_Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NotaActionPerformed(evt);
            }
        });

        jButton_Consulta.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jButton_Consulta.setText("Consulta");
        jButton_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaActionPerformed(evt);
            }
        });

        jButton_Expedicao.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jButton_Expedicao.setText("Expedição");
        jButton_Expedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExpedicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrincipalLayout.createSequentialGroup()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Consulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Expedicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPapelDeParede, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPapelDeParede, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Expedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addGap(1, 1, 1))
        );

        desktopPrincipal.setLayer(pnPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPrincipalLayout = new javax.swing.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnMenuPrincipalLayout = new javax.swing.GroupLayout(pnMenuPrincipal);
        pnMenuPrincipal.setLayout(pnMenuPrincipalLayout);
        pnMenuPrincipalLayout.setHorizontalGroup(
            pnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPrincipal)
                    .addComponent(pnMenuInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnMenuPrincipalLayout.setVerticalGroup(
            pnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuPrincipalLayout.createSequentialGroup()
                .addComponent(desktopPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMenuInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jMenu1.setText("Arquivo 6.0");
        jMenu1.add(jSeparator2);

        jMenu7.setText("Teste");

        jMenuItem6.setText("Tipo usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem11.setText("Login");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuItem17.setText("Relatorio");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuItem_EscondeMenu.setText("Esconde menu");
        jMenuItem_EscondeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EscondeMenuActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_EscondeMenu);

        jMenuItem19.setText("Esconde rodapé");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem24.setText("SysBanco");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem24);

        jMenuItem33.setText("Invisivel papel de parede");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem33);

        jMenuItem34.setText("Invisivel fundo");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem34);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator12);

        jMenu12.setText("Papel de parede");

        jMenuItem31.setText("null");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem31);

        jMenuItem12.setText("1");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenuItem13.setText("2");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem13);

        jMenuItem32.setText("3");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem32);

        jMenuItem25.setText("Seleciona papel de parede");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem25);

        jMenuItem30.setText("Seleciona cor de fundo");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem30);

        jMenu1.add(jMenu12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        menuChamaUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        menuChamaUnidade.setText("Unidade");
        menuChamaUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamaUnidadeActionPerformed(evt);
            }
        });
        jMenu2.add(menuChamaUnidade);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem2.setText("Produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu10.setText("Geral");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem4.setText("Cadastrar Cliente e/ou Fornecedor / Empresa / Transportadora");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);
        jMenu10.add(jSeparator9);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem7.setText("Cadastrar Natureza");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem7);
        jMenu10.add(jSeparator10);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem8.setText("Cadastrar Usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem8);

        jMenu2.add(jMenu10);

        jMenu11.setText("Movimento");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem3.setText("Cadastrar Setor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem3);
        jMenu11.add(jSeparator7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem9.setText("Cadastrar Movimento");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem9);

        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Expedição");
        jMenu3.add(jSeparator11);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem10.setText("Cadastrar Entrada/Saida");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);
        jMenu3.add(jSeparator8);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem14.setText("Expedição");
        jMenuItem14.setToolTipText("");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);
        jMenu3.add(jSeparator13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");
        jMenu4.add(jSeparator1);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem1.setText("Consulta Interna");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem15.setText("Expedição");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);
        jMenu4.add(jSeparator15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem16.setText("Bandeiras");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);
        jMenu4.add(jSeparator16);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img10.png"))); // NOI18N
        jMenuItem18.setText("Protocolo");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuBar1.add(jMenu4);

        jMenu15.setText("Internet");

        jMenuItem37.setText("Google");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem37);

        jMenuItem38.setText("Globomail");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem38);

        jMenuItem39.setText("Fsist");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem39);

        jMenuItem40.setText("Google");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem40);

        jMenuBar1.add(jMenu15);

        jMenu16.setText("Xml");

        jMenuItem35.setText("Entrada por xml");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem35);

        jMenuItem36.setText("Saida por xml");
        jMenu16.add(jMenuItem36);

        jMenuBar1.add(jMenu16);

        jMenu5.setText("Sistema");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem21.setText("Manipular dados 01");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Manipular dados 02");
        jMenu5.add(jMenuItem22);

        jMenuItem23.setText("Manipular dados 03");
        jMenu5.add(jMenuItem23);

        jMenuBar1.add(jMenu5);

        jMenu13.setText("Backup");

        jMenuItem29.setText("Selecione seu Sistema Operacioal");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem29);
        jMenu13.add(jSeparator17);

        jMenuItem20.setText("Salvar X64");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem20);

        jMenuItem26.setText("Salvar X86");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem26);
        jMenu13.add(jSeparator18);

        jMenuItem27.setText("Restaurar X64");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem27);

        jMenuItem28.setText("Restaurar X86");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem28);

        jMenuBar1.add(jMenu13);

        jMenu6.setText("Sobre");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu6MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu14.setText("Log out");
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu14MousePressed(evt);
            }
        });
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu14);

        jMenu8.setText("Sair");
        jMenu8.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu8MenuSelected(evt);
            }
        });
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu17.setText("Limpar tela");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu17MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu17);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jLabelCodigoTela.setText("ConsultaInterna");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu8MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu8MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu8MenuSelected

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked

    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        EventoSairPrograma();
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaInternaController.chamaListaProduto();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked

    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MousePressed

    }//GEN-LAST:event_jMenu6MousePressed

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        EventoSairPrograma();
    }//GEN-LAST:event_jMenu8MousePressed

    private void menuChamaUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamaUnidadeActionPerformed
        TelaInternaController.chamaCadastroUnidade();
    }//GEN-LAST:event_menuChamaUnidadeActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked

    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        MudaTipoUsuario();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jLabelCodigoTela.setText("FCELista");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jLabelCodigoTela.setText("NaturezaCadastro");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jLabelCodigoTela.setText("UsuarioCadastro");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jLabelCodigoTela.setText("SetorCadastro");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jLabelCodigoTela.setText("MovimentoLista");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
// jLabelCodigoTela.setText("MovimentoLista");
//        jButton1.doClick();
        MenuPrincipal.jLabelCodigoTela2.setText("novo");
        MenuPrincipal.jLabelCodigoTela.setText("MovimentoCadastroNovo");
        MenuPrincipal.jButton1.doClick();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);

        int i = JOptionPane.showConfirmDialog(null,
                "Deseja realmente sair?", "Saída",
                JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            repaint();
        }

    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        EscondeMenu();
        menuPrincipalController.chamaLogin(this);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        lblPapelDeParede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CorPaint.png"))); // NOI18N
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        lblPapelDeParede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Indonesia-Java-volcano-eruption-sky-mountains_1920x1080.jpg"))); // NOI18N
        lblPapelDeParede.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lblPapelDeParede.setVerticalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        MenuPrincipal.jLabelCodigoTela.setText("Expedicao");
        MenuPrincipal.jButton1.doClick();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        MenuPrincipal.jLabelCodigoTela.setText("Expedicao");
        MenuPrincipal.jButton1.doClick();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        jLabelCodigoTela.setText("Bandeiras");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        ManipulaProtocolo prot = new ManipulaProtocolo();
        prot.chamaRelatorioEmBranco();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jLabelCodigoTela.setText("Protocolo");
        jButton1.doClick();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem_EscondeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EscondeMenuActionPerformed
        EscondeMenu();
        System.out.println("Meu usuario::" + UsuarioLogado.getNome());
    }//GEN-LAST:event_jMenuItem_EscondeMenuActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        EscondePrincipal();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Selecione seu Sistema Operacional\nSe for X64 ou X86 \nPara fazer Backup e Restauração", "Selecione seu Sistema Operacional", INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        try {
            PostgresBackup_X64NOV.realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        try {
            PostgresBackup_X86NOV.realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        PostgresRestore_X64NOV restore = new PostgresRestore_X64NOV();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        PostgresRestore_X86NOV restore = new PostgresRestore_X86NOV();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        FrameManipulacao01 frameManipulacao01 = new FrameManipulacao01();
        frameManipulacao01.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed

        menuPrincipalController.chamaLogin(this);
    }//GEN-LAST:event_jMenu14ActionPerformed

    private void jMenu14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MousePressed
        System.out.println("Interface.Principal.jMenu14MousePressed()");
        EventoSairLogOut();
    }//GEN-LAST:event_jMenu14MousePressed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        String comando;
        File file1 = new File("C:\\Users\\edson\\Documents\\NetBeansProjects\\SysControleBanco\\dist");
        File file2 = new File("C:\\BKPBANCO\\SysControleBanco\\\\dist");
        if (file1.exists()) {
            JOptionPane.showMessageDialog(null, "Existe  1 !");
//            comando = "java -jar C:\\BKPBANCO\\SysControleBanco\\dist\\SysControleBanco.jar";
            comando = "java -jar C:\\Users\\edson\\Documents\\NetBeansProjects\\SysControleBanco\\dist\\SysControleBanco.jar";
            if (file2.exists()) {
                JOptionPane.showMessageDialog(null, "Existe 2 !");
                comando = "java -jar C:\\BKPBANCO\\SysControleBanco\\dist\\SysControleBanco.jar";
            } else {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Existe!");
            comando = "java -jar C:\\Users\\edson\\Documents\\NetBeansProjects\\SysControleBanco\\dist\\SysControleBanco.jar";
        }
        try {

            Process processo = Runtime.getRuntime().exec(comando);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Interface.Principal.jMenuItem24ActionPerformed()");
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        String LocalImagem = "C:\\Windows\\Web\\Wallpaper";
//                + "C:\\Users\\edson\\Pictures";
        LocalImagem = LocalImagem.replace("\\", "/");
        JFileChooser jfc = new JFileChooser();
        jfc = new JFileChooser(new File(LocalImagem));
        jfc.setFileFilter(new FileNameExtensionFilter("Imagem", "jpg", "jpeg", "gif"));
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.showDialog(jfc, "Selecione");
//        JOptionPane.showMessageDialog(null, jfc.getSelectedFile());
        String caminho = jfc.getSelectedFile().getAbsolutePath();
        ImageIcon icon = new ImageIcon(caminho);
        lblPapelDeParede.setIcon(icon);
        lblPapelDeParede.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lblPapelDeParede.setVerticalAlignment((int) CENTER_ALIGNMENT);

    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        JColorChooser jcc = new JColorChooser();
        Color c = jcc.showDialog(pnPrincipal, "Seleção de Cores", Color.yellow);
        pnPrincipal.setBackground(c);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        pnPrincipal.setBackground(null);
        lblPapelDeParede.setIcon(null);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        lblPapelDeParede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img16.jpg"))); // NOI18N
        lblPapelDeParede.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lblPapelDeParede.setVerticalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        if (lblPapelDeParede.isVisible()) {
            lblPapelDeParede.setVisible(false);
        } else {
            lblPapelDeParede.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        if (pnPrincipal.isVisible()) {
            pnPrincipal.setVisible(false);
        } else {
            pnPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed

    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed

    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed

    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        try {
            String comando = "java -jar C:\\Users\\edson\\Documents\\NetBeansProjects\\ManipulaXml01\\dist\\ManipulaXml01.jar";

            Runtime.getRuntime().exec(comando);
        } catch (IOException e) {
            System.out.println("Erro: " + e.getMessage() + "\n" + e.getCause());
        }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu17MouseClicked

    private void jMenu17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MousePressed
        jLabelCodigoTela.setText("LimpaTudo");
        jButton1.doClick();
    }//GEN-LAST:event_jMenu17MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControlaTela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DataMouseClicked
        DataAtual();
    }//GEN-LAST:event_jLabel_DataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //   jLabel_PapelDeParede.setBorder(javax.swing.BorderFactory.createEtchedBorder());;;
        // jLabel_PapelDeParede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        //jLabel_PapelDeParede.setMinimumSize(new java.awt.Dimension(1028, 772));
        //jLabel_PapelDeParede.setPreferredSize(new java.awt.Dimension(1028, 772));
        //        EscondeMenu();
        //tela.ChamaMovimentoCadastroNovo();
        jLabelCodigoTela.setText("MovimentoCadastroEditar");
        jLabelCodigoTela2.setText("13");
        jButton1.doClick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        jLabel_PapelDeParede.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N
        GeradorDeCodigo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel_Gerador_De_CodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Gerador_De_CodigoMouseClicked
        GeradorDeCodigo();
    }//GEN-LAST:event_jLabel_Gerador_De_CodigoMouseClicked

    private void pnMenuInferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuInferiorMouseClicked
        if (jButton_Consulta.isVisible()) {
            jButton_Consulta.setVisible(false);
            jButton_Expedicao.setVisible(false);
            jButton_Nota.setVisible(false);
            jButton_Produto.setVisible(false);
        } else {
            jButton_Consulta.setVisible(true);
            jButton_Expedicao.setVisible(true);
            jButton_Nota.setVisible(true);
            jButton_Produto.setVisible(true);
        }
    }//GEN-LAST:event_pnMenuInferiorMouseClicked

    private void lblPapelDeParedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelDeParedeMouseClicked
        if (evt.getClickCount() == 2) {
            if (jLabelTipoUsuario.getText().equals("Manutenção")) {
                EscondeMenu();
            } else {

            }
        }
    }//GEN-LAST:event_lblPapelDeParedeMouseClicked

    private void jButton_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProdutoActionPerformed
        TelaInternaController.chamaListaProduto();
    }//GEN-LAST:event_jButton_ProdutoActionPerformed

    private void jButton_NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NotaActionPerformed
        TelaInternaController.chamaListaNota();
    }//GEN-LAST:event_jButton_NotaActionPerformed

    private void jButton_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaActionPerformed
        jLabelCodigoTela.setText("ConsultaInterna");
        jButton1.doClick();
        //        ConsultaInterna3.jButton1.doClick();
    }//GEN-LAST:event_jButton_ConsultaActionPerformed

    private void jButton_ExpedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExpedicaoActionPerformed
        MenuPrincipal.jLabelCodigoTela.setText("Expedicao");
        MenuPrincipal.jButton1.doClick();
    }//GEN-LAST:event_jButton_ExpedicaoActionPerformed
    public void GeradorDeCodigo() {
        SequenciadorA = SequenciadorA + 1;
//    SequenciadorB=SequenciadorB+1;
        if (SequenciadorA > 9) {
            SequenciadorA = 1;
            SequenciadorB = SequenciadorB + 1;
        }

        if (SequenciadorB > 9) {
            SequenciadorB = 1;
        }
        MinhaReferencia = (String.valueOf(SequenciadorA)) + (String.valueOf(SequenciadorB));
        String D1 = jLabel_Data2.getText().replace("/", "");
        String H1 = jLabel_Hora.getText().replace(":", "");
        MinhaReferencia = D1 + H1 + MinhaReferencia;
        System.out.println("Interface.Principal.GeradorDeCodigo()  - MinhaReferencia " + MinhaReferencia);
        jLabel_Gerador_De_Codigo.setText(MinhaReferencia);
    }

    public static ImageIcon stretch(int larg, int alt, ImageIcon i) {
        return new ImageIcon(i.getImage().getScaledInstance(larg, alt, Image.SCALE_DEFAULT));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    public void EventoSairPrograma() {

        int i = JOptionPane.showConfirmDialog(null,
                "Deseja realmente sair?", "Saída",
                JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }

    }

    public void EventoSairLogOut() {

        int i = JOptionPane.showConfirmDialog(null,
                "Deseja realmente trocar usuario?", "Log Out",
                JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            EscondeMenu();
            menuPrincipalController.chamaLogin(this);
        } else {

        }

    }

    public void EscondeMenu() {
//        ManipulaProtocolo prot = new ManipulaProtocolo();
//        prot.chamaRelatorioEmBranco();

        if (jMenuBar1.isVisible()) {
            jMenuBar1.setVisible(false);
            pnMenuInferior.setVisible(false);
            jButton_Consulta.setVisible(false);
            jButton_Expedicao.setVisible(false);
            jButton_Nota.setVisible(false);
            jButton_Produto.setVisible(false);

        } else {
            jMenuBar1.setVisible(true);
            pnMenuInferior.setVisible(true);
            jButton_Consulta.setVisible(true);
            jButton_Expedicao.setVisible(true);
            jButton_Nota.setVisible(true);
            jButton_Produto.setVisible(true);

        }
        jLabelCodigoTela.setVisible(false);
        jLabelCodigoTela2.setVisible(false);
        jLabel_Data2.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jLabel_Gerador_De_Codigo.setVisible(false);
        jLabel_Empresa.setVisible(false);

        if (jLabelTipoUsuario.getText().equals("Manutenção")) {
            jMenu7.setVisible(true);
            jMenu5.setVisible(true);
        } else {
            jMenu7.setVisible(false);
            jMenu5.setVisible(false);
        }
    }

    public void ControlaTela() {
//        String MeuCodigo = jLabelCodigoTela.getText();
//        if (MeuCodigo == "TelaTeste1") {
//
//        } else if (MeuCodigo == "ListaProduto") {
//            tela.ChamaProdutoLista();
//        } else if (MeuCodigo == "AtualizaProdutoLista") {
//            tela.AtualizaProdutoLista();
//        } else if (MeuCodigo == "CadastroProduto") {
//            tela.ChamaCadastroProdutoInterno();
//        } else if (MeuCodigo == "CadastroProdutoEditar") {
//            tela.ChamaCadastroProdutoInternoEditar();
//        } else if (MeuCodigo == "FechaCadastroProdutoEditar") {
//            tela.FechaCadastroProdutoInternoEditar();
//        } else if (MeuCodigo == "CadastroUnidade") {
//            tela.chamaCadastroUnidade();
////        } else if (MeuCodigo == "CadastroUnidade") {
////            tela.ChamaCadastroUnidadeEditar();
//        } else if (MeuCodigo == "ConsultaInterna") {
//            tela.ChamaConsultaInterna();
//        } else if (MeuCodigo == "FCELista") {
//            tela.ChamaFCELista();
//        } else if (MeuCodigo == "FCEListaAtualizar") {
//            tela.ChamaFCEListaAtualizar();
//        } else if (MeuCodigo == "FCECadastro") {
//            tela.ChamaFCECadastro();
//        } else if (MeuCodigo == "FCECadastroEditar") {
//            tela.ChamaFCECadastroEditar();
//        } else if (MeuCodigo == "FechaFCECadastroEditar") {
//            tela.FechaFCECadastroEditar();
//        } else if (MeuCodigo == "NaturezaCadastro") {
//            tela.ChamaNaturezaCadastro();
//        } else if (MeuCodigo == "UsuarioCadastro") {
//            tela.ChamaUsuarioCadastro();
//        } else if (MeuCodigo == "SetorCadastro") {
//            tela.ChamaSetorCadastro();
//        } else if (MeuCodigo == "MovimentoLista") {
//            tela.ChamaMovimentoLista();
//        } else if (MeuCodigo == "MovimentoCadastroEditar") {
//            tela.ChamaMovimentoCadastroEditar();
//        } else if (MeuCodigo == "MovimentoCadastroNovo") {
//            tela.ChamaMovimentoCadastroNovo();
//        } else if (MeuCodigo == "FechaMovimentoCadastro") {
//            tela.FechaMovimentoCadastro();
//        } else if (MeuCodigo == "Exibir") {
//            tela.ChamaExibir();
//        } else if (MeuCodigo == "FrameExibir") {
//            tela.ChamaFrameExibir();
//        } else if (MeuCodigo == "Login") {
//            tela.ChamaLogin();
//        } else if (MeuCodigo == "Expedicao") {
//            tela.ChamaExpedicao();
//        } else if (MeuCodigo == "Bandeiras") {
//            tela.ChamaBandeira();
//        } else if (MeuCodigo == "Protocolo") {
//            tela.ChamaProtocolo();
//        } else if (MeuCodigo == "AtualizaTudo") {
//            tela.ChamaAtualizaTudo();
//        } else if (MeuCodigo == "LimpaTudo") {
//            tela.ChamaLimpaTudo();
//        } else {
//
//        }
//
    }

//    public void ChamaLoginPrincipal() {
//        
//        if (ChamaLoginPrincipal.isVisible()) {
//            ChamaLoginPrincipal.setVisible(false);
//            desktopPrincipal.remove(ChamaLoginPrincipal);
////             EscondeBarraBordasTeste();
//        } else {
//            desktopPrincipal.remove(ChamaLoginPrincipal);
//            desktopPrincipal.add(ChamaLoginPrincipal);
//
////            ChamaLoginPrincipal.setBorder(null);//retirar bordas;
//            ChamaLoginPrincipal.setPosicao();
////             EscondeBarraBordasTeste();
//            EscondeBarraBordasLogin();
//            ChamaLoginPrincipal.setVisible(true);
//            EscondeBarraBordasLogin();
//
////            
//        }
//    }
//    public void EscondeBarraBordasLogin() {
//        ChamaLoginPrincipal.setBorder(null);//retirar bordas;
//
//        ((BasicInternalFrameUI) ChamaLoginPrincipal.getUI()).setNorthPane(null);
//        ((BasicInternalFrameUI) ChamaLoginPrincipal.getUI()).setSouthPane(null);
//        ((BasicInternalFrameUI) ChamaLoginPrincipal.getUI()).setEastPane(null);
//        ((BasicInternalFrameUI) ChamaLoginPrincipal.getUI()).setWestPane(null);
//    }
    public void MudaTitulo() {
        this.setTitle("     Sys Estoque Versão 6.0   Lite   ");
    }

    public void DataAtual() {
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
        MenuMinhaData = (formato.format(dataSistema));
        MenuMinhaDataSistema = (formato2.format(dataSistema));
        //MenuMinhaDataSistema = MenuMinhaDataSistema.replace("/", "");
        jLabel_Data.setText(MenuMinhaData);
        jLabel_Data2.setText(MenuMinhaDataSistema);
        System.out.println("Carregou DataAtual");

    }

    public void HoraAtual() {
        Timer timer = new Timer(1000, new hora());
        timer.start();

        DataAtual();

    }

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            MenuMinhaHora = (String.format("%1$tH:%1$tM:%1$tS", now));
            String MenuMinhaHoraSistema = (String.format("%1$tM:%1$tS", now));
            MenuMinhaHoraSistema = MenuMinhaHora.replace(":", "");
            jLabel_Hora.setText(MenuMinhaHora);
//            ChamadaFormulario.ExecutaReferencia();]
            DataAtual_Atualizando();
        }

    }

    public void DataAtual_Atualizando() {
        String VerHora = jLabel_Hora.getText();
        // System.err.println("VerHora " + VerHora);
        if (VerHora.equals("00:00:00")) {
            DataAtual();
            JOptionPane.showMessageDialog(rootPane, "Data atual " + MenuMinhaData + " \nHora atual " + MenuMinhaHora);
            // System.err.println("Carregou DataAtual_Atualizando");
        } else if (VerHora.equals("12:00:00")) {
            JOptionPane.showMessageDialog(rootPane, "Data atual " + MenuMinhaData + " \nHora atual " + MenuMinhaHora);
        } else {
            //System.err.println("Não carregou DataAtual_Atualizando ");
        }

    }

    public void EscondePrincipal() {
        if (jButton1.isVisible()) {
            jLabelCodigoTela.setVisible(false);
            jLabelCodigoTela2.setVisible(false);
            jLabel_Data2.setVisible(false);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jLabel_Gerador_De_Codigo.setVisible(false);
            jLabel_Empresa.setVisible(false);
        } else {
            jLabelCodigoTela.setVisible(!false);
            jLabelCodigoTela2.setVisible(!false);
            jLabel_Data2.setVisible(!false);
            jButton1.setVisible(!false);
            jButton2.setVisible(!false);
            jButton3.setVisible(!false);
            jLabel_Gerador_De_Codigo.setVisible(!false);
            jLabel_Empresa.setVisible(!false);
        }

    }

    public void MudaTipoUsuario() {
        String MeuTipo = jLabelTipoUsuario.getText();
        if (MeuTipo == "Manutenção") {
            jLabelTipoUsuario.setText("Administrador");
        } else {
            jLabelTipoUsuario.setText("Manutenção");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPrincipal;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Consulta;
    private javax.swing.JButton jButton_Expedicao;
    private javax.swing.JButton jButton_Nota;
    private javax.swing.JButton jButton_Produto;
    public static javax.swing.JLabel jLabelCodigoTela;
    public static javax.swing.JLabel jLabelCodigoTela2;
    public static javax.swing.JLabel jLabelNomeUsuario;
    public static javax.swing.JLabel jLabelTipoUsuario;
    public static javax.swing.JLabel jLabel_Data;
    public static javax.swing.JLabel jLabel_Data2;
    public static javax.swing.JLabel jLabel_Empresa;
    public static javax.swing.JLabel jLabel_Gerador_De_Codigo;
    public static javax.swing.JLabel jLabel_Hora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public static javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JMenuItem jMenuItem_EscondeMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblPapelDeParede;
    public static javax.swing.JMenuItem menuChamaUnidade;
    private javax.swing.JPanel pnMenuInferior;
    private javax.swing.JPanel pnMenuPrincipal;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables

    private void carregaPapelParede() {
        lblPapelDeParede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Indonesia-Java-volcano-eruption-sky-mountains_1920x1080.jpg"))); // NOI18N
        lblPapelDeParede.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lblPapelDeParede.setVerticalAlignment((int) CENTER_ALIGNMENT);
    }

    public static JDesktopPane getDesktopPrincipal() {
        return desktopPrincipal;
    }

}
