/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Item;
import model.NotaFiscal;
import service.ItemService;
import service.NotaFiscalService;

/**
 *
 * @author edson
 */
public class TesteExbirNota extends javax.swing.JFrame {

    NotaFiscalService notaFiscalService = new NotaFiscalService();
    ItemService itemService = new ItemService();

    NotaFiscal notaFiscal = new NotaFiscal();
    Item item = new Item();

    /**
     * Creates new form TesteExbirNota
     */
    public TesteExbirNota() {
        initComponents();
        exibir();
    }

    public void exibir() {

        notaFiscal = notaFiscalService.obterNotaPorId(6436);
        
//        item=itemService.obterItenPorId(notaFiscal.getId_nota());
        String div = "-----------------------------------------------------------------------------------------------------------";
        String tipoNota = "Tipo: " + notaFiscal.getNota_operacao();
        String idNota = "Id nota: " + notaFiscal.getId_nota();
        String naturezaNota = "Natureza: " + notaFiscal.getNatureza().getDesc_natureza();
        String clienteNota = "Cliente: " + notaFiscal.getCliente().getCliente_nome();
        String dataNota = "Data: " + notaFiscal.getNota_data() + " Hora: " + notaFiscal.getNota_hora();
        String numeroNota = "Nota número: " + notaFiscal.getNota_nota();
        String chaveNota = " Chave: " + notaFiscal.getNota_chave();

        String observacaoNota = " Observação: " + notaFiscal.getNota_observacao();
        String motorista = " Motorista: " + notaFiscal.getTransporteModel().getMotorista();
        String placa = " Placa: " + notaFiscal.getTransporteModel().getPlaca();
        String uf = " Uf: " + notaFiscal.getTransporteModel().getUf();

        String especie = " Especie: " + notaFiscal.getTransporteModel().getEspecie();
        String numeracao = " Numeração: " + notaFiscal.getTransporteModel().getNumeracao();
        String pesoBruto = " Peso bruto: " + notaFiscal.getTransporteModel().getPesobruto();
        String pesoLiquido = " Peso liquido: " + notaFiscal.getTransporteModel().getPesoliquido();
        String quantidadeVolume = " Quantidade volume: " + notaFiscal.getTransporteModel().getQuantidade();

        String cabecalho = "<h2>" + tipoNota + "</h2>" + div + "<br> <h3>" + idNota + "</h3> " + naturezaNota + "<br>" + clienteNota + "<br>"
                + dataNota + "<br>" + numeroNota + "<br>" + chaveNota + "<br>"
                + div;
       
        String main = "";

        String rodape = "<br>" + observacaoNota + "<br><br>" + motorista + " " + placa + " " + uf + "<br><br>" + especie + " " + quantidadeVolume + " " + pesoBruto + " " + pesoLiquido + " " + numeracao;

        // Concatenando os dados usando HTML
        String textoHTML = "<html> " + cabecalho + " "+main+" " + rodape + "</html>";
        lblExbirHtml.setText(textoHTML);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        lblExbirHtml = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExbirHtml.setText("jLabel1");
        lblExbirHtml.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExbirHtml, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExbirHtml, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteExbirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteExbirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteExbirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteExbirNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteExbirNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblExbirHtml;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
