/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//// recebe
package view.internal;

import ModeloBeans.Beans_ECFT;
import ConectaBanco.ConexaoBD;
import ModeloDao.Dao_ECFT;
import controller.ClienteCadastroController;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Cliente;

/**
 *
 * @author Edson
 */
public class ClienteCadastroInternal extends javax.swing.JInternalFrame {
    
    ConexaoBD conex = new ConexaoBD();
    Beans_ECFT BEANS = new Beans_ECFT();
    Dao_ECFT DAO = new Dao_ECFT();
    
    String cnpj;
    String cep;
    String telefone;
    
    String descricao = null;
    int ver = 1;
    
    int tipo_lista = 1;
    int id_referencia;
    
    String data;
    
    String nome = null;
    String armazena_tipo;
    String armazena_descricao;
    String armazena_edicao;
    String armazena_unidade;
    String armazena_valor;
    String armazena_ncm;
    String armazena_cfop;
    String armazena_estoque;
    String armazena_observacao;
    
    ClienteCadastroController clienteCadastroController;

    public ClienteCadastroInternal(Cliente cliente) {
        initComponents();
        
        clienteCadastroController = new ClienteCadastroController();
        
        jLabel_Id.setVisible(false);
        jLabel1.setVisible(false);
//        jLabel_status.setVisible(false);
//        jLabel_Data_menu.setVisible(false);
        clienteCadastroController.carregarCampos(this, cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEstadual = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        jComboBoxFC = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel_Data_ent = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Id = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Cliente");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel14.setText("Descrição:");

        jLabel15.setText("* CNPJ:");
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel15MouseMoved(evt);
            }
        });
        jLabel15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel15FocusLost(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoFocusLost(evt);
            }
        });
        txtDescricao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtDescricaoInputMethodTextChanged(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });

        jLabel16.setText("*Telefone:");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        txtEstadual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEstadualFocusLost(evt);
            }
        });
        txtEstadual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadualKeyPressed(evt);
            }
        });

        jLabel22.setText("Insc. Est.:");

        txtCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnpjFocusLost(evt);
            }
        });

        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Endereço:");

        jLabel18.setText("No:");

        jLabel19.setText("*Cep:");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setText("Complemento:");

        jLabel21.setText("Bairro:");

        jLabel23.setText("Cidade:");

        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyPressed(evt);
            }
        });

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroKeyPressed(evt);
            }
        });

        txtComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtComplementoFocusLost(evt);
            }
        });
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComplementoKeyPressed(evt);
            }
        });

        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBairroFocusLost(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCidadeKeyPressed(evt);
            }
        });

        txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCepFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplemento)))))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORN/CLIE", "FORNECEDOR", "CLIENTE", "OUTRO", "TRANSPORTE", "EMPRESA" }));
        jComboBoxFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFCKeyPressed(evt);
            }
        });

        jLabel24.setText("Tipo.:");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtObservacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObservacaoFocusLost(evt);
            }
        });
        txtObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObservacaoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacao);

        jLabel_Data_ent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Data_ent.setText("data");
        jLabel_Data_ent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        btnNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNovoKeyPressed(evt);
            }
        });

        jLabel1.setText("Id :");

        jLabel_Id.setText("Novo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFC, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel_Data_ent, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnExcluir, btnNovo, btnSalvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel_Id))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel_Data_ent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxFC, jLabel24});

        jMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusGained(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Atualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Alterar Data");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator1);

        jMenuItem2.setText("Limpa Cnpj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Limpa Telefone");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setText("Limpa Cep");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        if (ver == 2) {
        } else {
//           
//            preencherTabela();
//            ver = 2;
//            if (jLabel_Id.getText().equals("Novo")) {
//                jButton_Salvar.setText("Salvar");
//            } else {
//                jButton_Salvar.setText("Alterar");
//            }
//        }
//        if (jLabel_status.getText().equals("ATIVO")) {
//            jButton_Excluir.setText("Excluir");
//        } else {
//            jButton_Excluir.setText("Ativar");
        }
    }//GEN-LAST:event_formFocusGained
    

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
//        Component[] componentes = menu.Barra_Menu.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes) {
//            componente.setEnabled(true);
//        }
//        Component[] componentes2 = Painel_principal.getComponents(); // altere para o nome da variavel do seu painel
//        for (Component componente : componentes2) {
//            componente.setEnabled(true);
//        }
        ver = 1;
//        FechaForm();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ver = 1;
//        FechaForm();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null, "Você quer realmente alterar a data?\nVocê não tem permissão.");
        while (nome == null || nome.equals("")) {
            nome = JOptionPane.showInputDialog("Digite sua senha de acesso.");
            if (nome == null || nome.equals("")) {
                JOptionPane.showMessageDialog(null, "Você não digitou sua senha.");
                nome = "VAZIO";
            }
        }
//        JOptionPane.showMessageDialog(null, "Senha " + nome);
        if (nome.equals("123")) {
//            JDialog_Calendario calendario = new JDialog_Calendario(menu, rootPaneCheckingEnabled);
//            calendario.recebe_local("produto");
//            calendario.setVisible(true);
//            calendario.setResizable(false);
//            nome = null;
        } else {
            JOptionPane.showMessageDialog(null, "Acesso negado.");
            nome = null;
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    

    private void jMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusGained
        
    }//GEN-LAST:event_jMenuBar1FocusGained

    private void btnNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNovoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoKeyPressed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            Principal.jButton_Meu_Foco.setText("lec2");
//           Principal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ver = 1;
        
        LimpaCampos();
//        Principal.jLabelCodigoTela.setText("FCEListaAtualizar");
//        Principal.jButton1.doClick();
//        Principal.jLabelCodigoTela.setText("AtualizaTudo");
//      Principal.jButton1.doClick();
        ClienteListaInternal.btnPesquisa.doClick();

    }//GEN-LAST:event_btnSalvarActionPerformed
    
    public void LimpaCampos() {
        
        txtNome.setText("");
        txtDescricao.setText("");
        txtCnpj.setText("");
        txtTelefone.setText("");
        txtEstadual.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtCep.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        jComboBoxFC.setSelectedItem("FORN/CLIE");
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (jLabel_Id.getText() == "Novo") {
            
            txtNome.setText("");
            txtDescricao.setText("");
            txtCnpj.setText("");
            txtTelefone.setText("");
            txtEstadual.setText("");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtCep.setText("");
            txtComplemento.setText("");
            txtBairro.setText("");
            txtCidade.setText("");
            jComboBoxFC.setSelectedItem("FORN/CLIE");
            
        } else {
            //            this.dispose();
            
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir/ativar ? ");
        if (resposta == JOptionPane.YES_OPTION) {
            BEANS.setStecft(3);
//            BEANS.setEcft_usuario(Principal.jLabelNomeUsuario.getText());
//            BEANS.setEcft_registro(Principal.jLabel_Data.getText());
            BEANS.setEcft_id(Integer.parseInt(jLabel_Id.getText()));
            DAO.Excluir(BEANS);
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
//            Principal.jLabelCodigoTela.setText("FCEListaAtualizar");
//            Principal.jButton1.doClick();
//            Principal.jLabelCodigoTela.setText("FechaFCECadastroEditar");
//            Principal.jButton1.doClick();
        }

//       

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtObservacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacaoFocusLost
        txtObservacao.setText(txtObservacao.getText().toUpperCase());
        if (txtObservacao.getText().length() > 160) {
            txtObservacao.requestFocus();
            txtObservacao.setBackground(Color.red);
        } else {
            txtObservacao.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtObservacaoFocusLost

    private void jComboBoxFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFCKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtNome.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
    }//GEN-LAST:event_jComboBoxFCKeyPressed

    private void txtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyPressed
        
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtCidade.setText(txtCidade.getText().toUpperCase());
            btnSalvar.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtCidade.setText(txtCidade.getText().toUpperCase());
            //            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtCidade.setText(txtCidade.getText().toUpperCase());
            txtBairro.requestFocus();
        }
        
        if (txtCidade.getText().length() > 130) {
            txtCidade.requestFocus();
            txtCidade.setBackground(Color.red);
        } else {
            txtCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCidadeKeyPressed

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        txtCidade.setText(txtCidade.getText().toUpperCase());
        if (txtCidade.getText().length() > 130) {
            txtCidade.requestFocus();
            txtCidade.setBackground(Color.red);
        } else {
            txtCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroKeyReleased

    private void txtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtBairro.setText(txtBairro.getText().toUpperCase());
            txtCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtBairro.setText(txtBairro.getText().toUpperCase());
            txtCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtBairro.setText(txtBairro.getText().toUpperCase());
            txtComplemento.requestFocus();
        }
        
        if (txtBairro.getText().length() > 130) {
            txtBairro.requestFocus();
            txtBairro.setBackground(Color.red);
        } else {
            txtBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtBairroKeyPressed

    private void txtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusLost
        txtBairro.setText(txtBairro.getText().toUpperCase());
        if (txtBairro.getText().length() > 130) {
            txtBairro.requestFocus();
            txtBairro.setBackground(Color.red);
        } else {
            txtBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtBairroFocusLost

    private void txtComplementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtComplemento.setText(txtComplemento.getText().toUpperCase());
            txtBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtComplemento.setText(txtComplemento.getText().toUpperCase());
            txtBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtComplemento.setText(txtComplemento.getText().toUpperCase());
            txtCep.requestFocus();
        }
        
        if (txtComplemento.getText().length() > 140) {
            txtComplemento.requestFocus();
            txtComplemento.setBackground(Color.red);
        } else {
            txtComplemento.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtComplementoKeyPressed

    private void txtComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComplementoFocusLost
        txtComplemento.setText(txtComplemento.getText().toUpperCase());
        if (txtComplemento.getText().length() > 140) {
            txtComplemento.requestFocus();
            txtComplemento.setBackground(Color.red);
        } else {
            txtComplemento.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtComplementoFocusLost

    private void txtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtEndereco.requestFocus();
        }
        if (txtNumero.getText().length() > 20) {
            txtNumero.requestFocus();
            txtNumero.setBackground(Color.red);
        } else {
            txtNumero.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNumeroKeyPressed

    private void txtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtEndereco.setText(txtEndereco.getText().toUpperCase());
            txtNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtEndereco.setText(txtEndereco.getText().toUpperCase());
            txtNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtEndereco.setText(txtEndereco.getText().toUpperCase());
            txtTelefone.requestFocus();
        }
        
        if (txtEndereco.getText().length() > 155) {
            txtEndereco.requestFocus();
            txtEndereco.setBackground(Color.red);
        } else {
            txtEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtEnderecoKeyPressed

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        txtEndereco.setText(txtEndereco.getText().toUpperCase());
        if (txtEndereco.getText().length() > 155) {
            txtEndereco.requestFocus();
            txtEndereco.setBackground(Color.red);
        } else {
            txtEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtEstadualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadualKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtDescricao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtDescricao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtCnpj.requestFocus();
        }
    }//GEN-LAST:event_txtEstadualKeyPressed

    private void txtEstadualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstadualFocusLost
//        jTextFieldInscricao.setText(jTextFieldInscricao.getText().toUpperCase());

        //206.277.405.117
    }//GEN-LAST:event_txtEstadualFocusLost

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
//            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
//            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtDescricao.setText(txtDescricao.getText().toUpperCase());
            txtTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            txtDescricao.setText(txtDescricao.getText().toUpperCase());
            txtTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            txtDescricao.setText(txtDescricao.getText().toUpperCase());
            txtEstadual.requestFocus();
        }
        
        if (txtDescricao.getText().length() > 155) {
            txtDescricao.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void txtDescricaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtDescricaoInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoInputMethodTextChanged

    private void txtDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoFocusLost
        txtDescricao.setText(txtDescricao.getText().toUpperCase());
        if (txtDescricao.getText().length() > 155) {
            txtDescricao.requestFocus();
            txtDescricao.setBackground(Color.red);
            // JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        } else {
            txtDescricao.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtDescricaoFocusLost

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        txtNome.setText(txtNome.getText().toUpperCase());
        if (txtNome.getText().length() > 30) {
            txtNome.requestFocus();
            txtNome.setBackground(Color.red);
//            JOptionPane.showMessageDialog(rootPane, "Verifique campo\nCampo ultrapassa limite de caracteres!");
        } else {
            txtNome.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNomeFocusLost
    

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
//        jFormattedTextFieldCnpj.setText(null);
// jLabel15.setBackground(Color.green);
// jLabel15.setForeground(Color.green);
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusLost
        jLabel15.setBackground(Color.green);
    }//GEN-LAST:event_jLabel15FocusLost

    private void jLabel15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusGained
// jLabel15.setBackground(null);
// System.out.println("RECEBI O FOCO1");
    }//GEN-LAST:event_jLabel15FocusGained

    private void jLabel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseMoved
//       jLabel15.setBackground(Color.yellow);
//        System.out.println("RECEBI O FOCO2");
//         jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseMoved

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
// jLabel15.setBackground(Color.yellow);
//        System.out.println("RECEBI O FOCO3");
//        jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void txtCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnpjFocusLost
        
    }//GEN-LAST:event_txtCnpjFocusLost

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        
    }//GEN-LAST:event_txtCepFocusLost

    private void txtObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacaoKeyPressed
        if (txtObservacao.getText().length() > 160) {
            txtObservacao.requestFocus();
            txtObservacao.setBackground(Color.red);
        } else {
            txtObservacao.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtObservacaoKeyPressed

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        if (txtNumero.getText().length() > 20) {
            txtNumero.requestFocus();
            txtNumero.setBackground(Color.red);
        } else {
            txtNumero.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNumeroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    public static javax.swing.JComboBox<String> jComboBoxFC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel_Data_ent;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstadual;
    public static javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {
        return btnCancelar;
    }
    
    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }
    
    public JButton getBtnExcluir() {
        return btnExcluir;
    }
    
    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }
    
    public JButton getBtnNovo() {
        return btnNovo;
    }
    
    public void setBtnNovo(JButton btnNovo) {
        this.btnNovo = btnNovo;
    }
    
    public JButton getBtnSalvar() {
        return btnSalvar;
    }
    
    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }
    
    public JTextField getTxtBairro() {
        return txtBairro;
    }
    
    public void setTxtBairro(JTextField txtBairro) {
        this.txtBairro = txtBairro;
    }
    
    public JTextField getTxtCep() {
        return txtCep;
    }
    
    public void setTxtCep(JTextField txtCep) {
        this.txtCep = txtCep;
    }
    
    public JTextField getTxtCidade() {
        return txtCidade;
    }
    
    public void setTxtCidade(JTextField txtCidade) {
        this.txtCidade = txtCidade;
    }
    
    public JTextField getTxtCnpj() {
        return txtCnpj;
    }
    
    public void setTxtCnpj(JTextField txtCnpj) {
        this.txtCnpj = txtCnpj;
    }
    
    public JTextField getTxtComplemento() {
        return txtComplemento;
    }
    
    public void setTxtComplemento(JTextField txtComplemento) {
        this.txtComplemento = txtComplemento;
    }
    
    public JTextField getTxtDescricao() {
        return txtDescricao;
    }
    
    public void setTxtDescricao(JTextField txtDescricao) {
        this.txtDescricao = txtDescricao;
    }
    
    public JTextField getTxtEndereco() {
        return txtEndereco;
    }
    
    public void setTxtEndereco(JTextField txtEndereco) {
        this.txtEndereco = txtEndereco;
    }
    
    public JTextField getTxtEstadual() {
        return txtEstadual;
    }
    
    public void setTxtEstadual(JTextField txtEstadual) {
        this.txtEstadual = txtEstadual;
    }
    
    public   JTextField getTxtNome() {
        return txtNome;
    }
    
    public   void setTxtNome(JTextField txtNome) {
        ClienteCadastroInternal.txtNome = txtNome;
    }
    
    public JTextField getTxtNumero() {
        return txtNumero;
    }
    
    public void setTxtNumero(JTextField txtNumero) {
        this.txtNumero = txtNumero;
    }
    
    public JTextArea getTxtObservacao() {
        return txtObservacao;
    }
    
    public void setTxtObservacao(JTextArea txtObservacao) {
        this.txtObservacao = txtObservacao;
    }
    
    public JTextField getTxtTelefone() {
        return txtTelefone;
    }
    
    public void setTxtTelefone(JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }
    
}
