/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
///  jComboBox_Natureza formulario jLabel_Calculado
package view.internal;

import Interface.Principal;
import ModeloBeans.Beans_Nota;
import ModeloBeans.ModeloTabela;
import ConectaBanco.ConexaoBD;
import Consulta.JDialogAuxilioChave;
import ModeloBeans.Beans_Movimento;
import ModeloDao.Dao_Nota;
import ModeloDao.Dao_Transporte;
import ModeloBeans.Beans_Transporte;
import com.toedter.calendar.JDateChooser;
import controller.MovimentoCadastroController;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Cliente;
import model.Natureza;

/**
 *
 * @author edson
 */
/// pree
public class MovimentoCadastroJIF extends javax.swing.JInternalFrame {

    ConexaoBD conex_MeuTotal = new ConexaoBD();
    ConexaoBD conex_Transporte = new ConexaoBD();

    ConexaoBD conex = new ConexaoBD();

    ConexaoBD conexApaga = new ConexaoBD();
    ConexaoBD conexInsere = new ConexaoBD();

    ConexaoBD conexSaldo = new ConexaoBD();

    Dao_Nota dao = new Dao_Nota();
    Beans_Nota beans = new Beans_Nota();

    Beans_Transporte beanst = new Beans_Transporte();
    Dao_Transporte daot = new Dao_Transporte();

    Principal menu;

//DialogCalculado CC = new JDialogCalculado(menu, rootPaneCheckingEnabled);
    int id_referencia;
    int id_nota;
    String MinhaNatureza;
    String MinhaIdNota;
    String SelecaoReferencia_Movimento;

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date data = null;

    String MeuTotal;
    int ComboFocu = 0;
    int ComboFocuNatureza = 0;

    private static int idProduto = 0;
    MovimentoCadastroController movimentoCadastroController;
    public static List<Beans_Movimento> movimentos;

    /**
     * Creates new form MovimentoJIF
     */
    public MovimentoCadastroJIF() {
        movimentoCadastroController = new MovimentoCadastroController();
        initComponents();

        movimentoCadastroController.mudarCorPaineis(this);
        movimentoCadastroController.carregarNatureza(this);
        movimentoCadastroController.carregarCliente(this);

        movimentos = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnTopo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbNatureza = new javax.swing.JComboBox<>();
        dataNota = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        btnDataAtual = new javax.swing.JButton();
        btnHoraAtual = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        jLabel_Status_Visualizar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnDados = new javax.swing.JPanel();
        jLabel_Texto_Produto1 = new javax.swing.JLabel();
        btnInserirProduto = new javax.swing.JButton();
        btnLimparCampoBuscaProduto = new javax.swing.JButton();
        btnRemoverUmProduto = new javax.swing.JButton();
        txtBuscarUmProdutoPorNome = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableListaProduto_Nota = new javax.swing.JTable();
        pnTransporte = new javax.swing.JPanel();
        jLabel_Titulo1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_modalidade = new javax.swing.JComboBox<>();
        jComboBox_transportadora = new javax.swing.JComboBox<>();
        vol_motorista = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vol_uf = new javax.swing.JTextField();
        vol_placa = new javax.swing.JTextField();
        jLabel_Titulo2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vol_quantidade = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        vol_especie = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        vol_peso_liquido = new javax.swing.JTextField();
        vol_peso_bruto = new javax.swing.JTextField();
        vol_numeracao = new javax.swing.JTextField();
        pnInformacao = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_Observacao = new javax.swing.JTextArea();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jRadioButton_ativa_Vizualizar = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnPrincipal.setBackground(new java.awt.Color(0, 255, 204));

        pnTopo.setBackground(new java.awt.Color(0, 255, 204));
        pnTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Natureza da Operação :");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Cliente / Fornecedor:");

        cbNatureza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNaturezaItemStateChanged(evt);
            }
        });
        cbNatureza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbNaturezaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbNaturezaFocusLost(evt);
            }
        });
        cbNatureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNaturezaActionPerformed(evt);
            }
        });
        cbNatureza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNaturezaKeyPressed(evt);
            }
        });

        dataNota.setDateFormatString("dd'/'MM'/'yyyy");
        dataNota.setInheritsPopupMenu(true);

        jLabel3.setText("Data :");

        jLabel4.setText("Hora :");

        txtNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotaFocusLost(evt);
            }
        });
        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNotaKeyReleased(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nota:");

        txtChave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChaveFocusLost(evt);
            }
        });
        txtChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaveActionPerformed(evt);
            }
        });
        txtChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChaveKeyPressed(evt);
            }
        });

        jLabel7.setText("Chave :");

        cbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClienteItemStateChanged(evt);
            }
        });
        cbCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbClienteFocusLost(evt);
            }
        });
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });
        cbCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbClienteKeyPressed(evt);
            }
        });

        btnDataAtual.setForeground(new java.awt.Color(255, 51, 51));
        btnDataAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-calendário-20.png"))); // NOI18N
        btnDataAtual.setToolTipText("Atualizar Campos");
        btnDataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAtualActionPerformed(evt);
            }
        });
        btnDataAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDataAtualKeyPressed(evt);
            }
        });

        btnHoraAtual.setForeground(new java.awt.Color(255, 51, 51));
        btnHoraAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-presente-20.png"))); // NOI18N
        btnHoraAtual.setToolTipText("Limpa Relogio");
        btnHoraAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraAtualActionPerformed(evt);
            }
        });
        btnHoraAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHoraAtualKeyPressed(evt);
            }
        });

        txtHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFocusLost(evt);
            }
        });
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoraKeyReleased(evt);
            }
        });

        lblInformacoes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacoes.setText(" ");
        lblInformacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
        pnTopo.setLayout(pnTopoLayout);
        pnTopoLayout.setHorizontalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNatureza, 0, 349, Short.MAX_VALUE)
                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHoraAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(btnDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTopoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTopoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNota, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTopoLayout.setVerticalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNatureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(7, 7, 7)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHoraAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTopoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDataAtual, btnHoraAtual, cbCliente, cbNatureza, dataNota, jLabel13, jLabel14, jLabel3, jLabel4, txtHora});

        jLabel_Status_Visualizar.setText("Status :");
        jLabel_Status_Visualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N

        pnDados.setBackground(new java.awt.Color(0, 255, 204));

        jLabel_Texto_Produto1.setText("Produto :");

        btnInserirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inserir-20.png"))); // NOI18N
        btnInserirProduto.setText("Inserir");
        btnInserirProduto.setToolTipText("Inclui Produto");
        btnInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirProdutoActionPerformed(evt);
            }
        });
        btnInserirProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInserirProdutoKeyPressed(evt);
            }
        });

        btnLimparCampoBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-vassoura-20.png"))); // NOI18N
        btnLimparCampoBuscaProduto.setText("Limpar");
        btnLimparCampoBuscaProduto.setToolTipText("Limpa Produto");
        btnLimparCampoBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCampoBuscaProdutoActionPerformed(evt);
            }
        });

        btnRemoverUmProduto.setForeground(new java.awt.Color(255, 51, 51));
        btnRemoverUmProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remover-20.png"))); // NOI18N
        btnRemoverUmProduto.setText("Excluir");
        btnRemoverUmProduto.setToolTipText("Exclui Produto");
        btnRemoverUmProduto.setEnabled(false);
        btnRemoverUmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUmProdutoActionPerformed(evt);
            }
        });

        txtBuscarUmProdutoPorNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarUmProdutoPorNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarUmProdutoPorNomeFocusLost(evt);
            }
        });
        txtBuscarUmProdutoPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarUmProdutoPorNomeKeyPressed(evt);
            }
        });

        jTableListaProduto_Nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaProduto_Nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaProduto_NotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableListaProduto_NotaMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTableListaProduto_Nota);

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Texto_Produto1)
                .addGap(8, 8, 8)
                .addComponent(txtBuscarUmProdutoPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparCampoBuscaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverUmProduto)
                .addContainerGap())
            .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnDadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInserirProduto, btnLimparCampoBuscaProduto, btnRemoverUmProduto});

        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUmProdutoPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Texto_Produto1)
                    .addComponent(btnInserirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCampoBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverUmProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnDadosLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInserirProduto, btnLimparCampoBuscaProduto, btnRemoverUmProduto, jLabel_Texto_Produto1, txtBuscarUmProdutoPorNome});

        jTabbedPane1.addTab("Dados", pnDados);

        pnTransporte.setBackground(new java.awt.Color(0, 255, 204));

        jLabel_Titulo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo1.setText("Transportadora");
        jLabel_Titulo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setText("Transportadora :");

        jLabel10.setText("Modalidade do Frete :");

        jComboBox_modalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-NÃO DEFINIDO", "1-DESTINATARIO", "2-REMETENTE", "3-TRANSPORTADORA", "4-DEVOLUÇÃO", "5-OUTRO" }));
        jComboBox_modalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_modalidadeItemStateChanged(evt);
            }
        });

        jComboBox_transportadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO DEFINIDO" }));
        jComboBox_transportadora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_transportadoraItemStateChanged(evt);
            }
        });
        jComboBox_transportadora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox_transportadoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_transportadoraFocusLost(evt);
            }
        });
        jComboBox_transportadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_transportadoraKeyPressed(evt);
            }
        });

        vol_motorista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vol_motoristaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_motoristaFocusLost(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Motorista :");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("UF");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Placa Veiculo");

        vol_uf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_ufFocusLost(evt);
            }
        });

        vol_placa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_placaFocusLost(evt);
            }
        });
        vol_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vol_placaKeyReleased(evt);
            }
        });

        jLabel_Titulo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo2.setText("Volumes transportados");
        jLabel_Titulo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Quantidade");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Espécie");

        vol_especie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vol_especieFocusLost(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Numeração");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Peso Bruto");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Peso Liquido");

        vol_numeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vol_numeracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTransporteLayout = new javax.swing.GroupLayout(pnTransporte);
        pnTransporte.setLayout(pnTransporteLayout);
        pnTransporteLayout.setHorizontalGroup(
            pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Titulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTransporteLayout.createSequentialGroup()
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(vol_quantidade, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vol_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vol_numeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vol_peso_bruto)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vol_peso_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnTransporteLayout.createSequentialGroup()
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vol_motorista, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vol_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vol_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnTransporteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_modalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_transportadora, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 275, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnTransporteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel23, jLabel25, jLabel26, jLabel27, jLabel30, vol_especie, vol_numeracao, vol_peso_bruto, vol_peso_liquido, vol_quantidade});

        pnTransporteLayout.setVerticalGroup(
            pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jComboBox_transportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox_modalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21))
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vol_motorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vol_peso_bruto)
                            .addComponent(vol_peso_liquido)
                            .addComponent(vol_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol_numeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );

        pnTransporteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_modalidade, jComboBox_transportadora, jLabel10, jLabel24});

        pnTransporteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel19, jLabel21, jLabel28});

        jTabbedPane1.addTab("Transportadora/Volumes", pnTransporte);

        pnInformacao.setBackground(new java.awt.Color(0, 255, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Observações");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea_Observacao.setColumns(20);
        jTextArea_Observacao.setRows(5);
        jTextArea_Observacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane7.setViewportView(jTextArea_Observacao);

        javax.swing.GroupLayout pnInformacaoLayout = new javax.swing.GroupLayout(pnInformacao);
        pnInformacao.setLayout(pnInformacaoLayout);
        pnInformacaoLayout.setHorizontalGroup(
            pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1114, Short.MAX_VALUE)
            .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnInformacaoLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE))
                    .addGap(4, 4, 4)))
        );
        pnInformacaoLayout.setVerticalGroup(
            pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInformacaoLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Informações Adicionais", pnInformacao);

        btnExcluir.setBackground(new java.awt.Color(255, 51, 0));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-24.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancelar-24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-24.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jRadioButton_ativa_Vizualizar.setText("Ativa vizualizar");
        jRadioButton_ativa_Vizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ativa_VizualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnTopo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_ativa_Vizualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Status_Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Status_Visualizar)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(jRadioButton_ativa_Vizualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem4.setText("Repete ultimo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Atualiza tabela");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Gerar copia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        AtualizarTudo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void MovimentoBancoTemporarioAlterado() {

    }

    public void ExecutaSaldo() {
        String MeuExecutaSaldo = String.valueOf(id_referencia);
        System.out.println("aquiExecutaSaldo()        Verificando            " + MeuExecutaSaldo);
        conexSaldo.conexao();
        try {
            java.sql.PreparedStatement pst = conexSaldo.con.prepareStatement("update produto as prod set \n"
                    + "saldo_prod=( select  sum(qtd_mov) as qtd_prod  from movprodutobase as base\n"
                    + " where id_prod_ent=sis_prod and stmovimento=1 and stsaldo=1 \n"
                    + " GROUP BY   prod.sis_prod order by sis_prod asc )\n"
                    + " from movprodutobase as base\n"
                    + "where prod.sis_prod=base.id_prod_ent and nota_mov='" + MeuExecutaSaldo + "' and base.stsaldo=1");
            pst.execute();
            System.out.println("aquiExecutaSaldo() ok");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao ExecutaSaldo -- \n" + ex);
        }
        conexSaldo.desconecta();
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        PreencherTabela();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente fazer uma cópia ? ");
        if (resposta == JOptionPane.YES_OPTION) {
//            MinhaCopia = "executando";
//            ExecutaCopia();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed

        if (txtHora.getText().length() >= 5) {

        }

    }//GEN-LAST:event_txtHoraKeyPressed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusLost
        if (txtHora.getText().isEmpty()) {
            txtHora.setText("  :  ");
        } else if (txtHora.getText().equals("  :  ")) {
            txtHora.setText("  :  ");
        } else {
//            AjustaMinhaHora();
        }
    }//GEN-LAST:event_txtHoraFocusLost


    private void btnHoraAtualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHoraAtualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoraAtualKeyPressed

    private void btnHoraAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraAtualActionPerformed
        movimentoCadastroController.horaAtual(this);
    }//GEN-LAST:event_btnHoraAtualActionPerformed

    private void btnDataAtualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDataAtualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataAtualKeyPressed

    private void btnDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAtualActionPerformed
        movimentoCadastroController.dataAtual(this);
    }//GEN-LAST:event_btnDataAtualActionPerformed

    private void cbClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbClienteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtHora.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
//            PreencherFornecedor();
        }
    }//GEN-LAST:event_cbClienteKeyPressed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClienteActionPerformed

    private void txtChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChaveKeyPressed
        if (evt.getKeyCode() == evt.VK_F2) {
            System.out.println("Interface.Movimento.MovimentoJIFAlterado.jTextField_Chave_NotaKeyPressed()\n F12");

        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
        }
        if (evt.getKeyCode() == evt.VK_F3) {

        }
        if (evt.getKeyCode() == evt.VK_F12) {
            JDialogAuxilioChave conf = new JDialogAuxilioChave(menu, rootPaneCheckingEnabled);
            conf.RecebeFornecedor("" + cbCliente.getSelectedItem());
            if (conf == null) {
                // TelaSalProd = new ModSaldoProd();
                conf.setVisible(true);
                conf.setResizable(false);

            } else {
                conf.setVisible(true);
                conf.setResizable(false);
            }
        }
    }//GEN-LAST:event_txtChaveKeyPressed

    private void txtChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaveActionPerformed

    private void txtChaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChaveFocusLost
        if (txtChave.getText().isEmpty()) {
        } else {
        }
    }//GEN-LAST:event_txtChaveFocusLost

    private void txtNotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaKeyReleased

    private void txtNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (txtChave.isEnabled()) {
                txtChave.requestFocus();
            } else {
            }
        }
    }//GEN-LAST:event_txtNotaKeyPressed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void txtNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotaFocusLost

    }//GEN-LAST:event_txtNotaFocusLost

    private void cbNaturezaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNaturezaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            dataNota.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
//            PreencherNatureza();
        }
    }//GEN-LAST:event_cbNaturezaKeyPressed

    private void cbNaturezaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbNaturezaFocusLost
//        SelecionarNatureza();
        //        if (jLabel_OS.getText() == "Novo") {
        //            preencheNatureza_Tipo();
        //        } else {
        //        }
    }//GEN-LAST:event_cbNaturezaFocusLost

    private void cbNaturezaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNaturezaItemStateChanged

    }//GEN-LAST:event_cbNaturezaItemStateChanged

    public void ManipulaNatureza() {

    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CarregaSistemaRepeteUltimo();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jRadioButton_ativa_VizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ativa_VizualizarActionPerformed
//        SalvaReferenciado();
    }//GEN-LAST:event_jRadioButton_ativa_VizualizarActionPerformed

    private void cbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClienteItemStateChanged


    }//GEN-LAST:event_cbClienteItemStateChanged

    private void cbClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusLost
//        SelecionarFornecedor();
    }//GEN-LAST:event_cbClienteFocusLost


    private void cbNaturezaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbNaturezaFocusGained
//        SelecionarNaturezaInt = 1;
        ComboFocuNatureza = 1;
    }//GEN-LAST:event_cbNaturezaFocusGained

    private void txtHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyReleased
//        AjustaMinhaHora();
    }//GEN-LAST:event_txtHoraKeyReleased

    private void cbNaturezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNaturezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNaturezaActionPerformed

    private void cbClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusGained
//        ComboFocuFornecedor = 1;

    }//GEN-LAST:event_cbClienteFocusGained

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        LimpaSistema();
//        LimpaCampoProduto();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        EventoFechaMovimento();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//        produtoController.excluirProduto(this);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //    produtoController.limparCampos(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //    produtoController.salvar(this);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void vol_especieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_especieFocusLost
        vol_especie.setText(vol_especie.getText().toUpperCase());
    }//GEN-LAST:event_vol_especieFocusLost

    private void vol_numeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vol_numeracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vol_numeracaoActionPerformed

    private void vol_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vol_placaKeyReleased
//        AjustaMinhaPlaca();
    }//GEN-LAST:event_vol_placaKeyReleased

    private void vol_placaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_placaFocusLost
        //aqui
        //  AjustaMinhaPlaca();
        vol_placa.setText(vol_placa.getText().toUpperCase());
    }//GEN-LAST:event_vol_placaFocusLost

    private void vol_ufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_ufFocusLost
//        AjustaMinhaUf();
        vol_uf.setText(vol_uf.getText().toUpperCase());
    }//GEN-LAST:event_vol_ufFocusLost

    private void vol_motoristaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_motoristaFocusLost
        vol_motorista.setText(vol_motorista.getText().toUpperCase());
        vol_motorista.setBackground(Color.WHITE);
    }//GEN-LAST:event_vol_motoristaFocusLost

    private void vol_motoristaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vol_motoristaFocusGained
        //        vol_motorista.setBackground(Color.cyan);
    }//GEN-LAST:event_vol_motoristaFocusGained

    private void jComboBox_transportadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_transportadoraKeyPressed
        if (evt.getKeyCode() == evt.VK_F5) {
            PreencherTransporte();
        }
    }//GEN-LAST:event_jComboBox_transportadoraKeyPressed

    private void jComboBox_transportadoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_transportadoraFocusLost

    }//GEN-LAST:event_jComboBox_transportadoraFocusLost

    private void jComboBox_transportadoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_transportadoraFocusGained
        ComboFocu = 1;

    }//GEN-LAST:event_jComboBox_transportadoraFocusGained

    private void jComboBox_transportadoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_transportadoraItemStateChanged

        String selecao = (String) jComboBox_transportadora.getSelectedItem();

        if (selecao == null) {
//            jLabel_exibe_transporte.setText(null);
//            vol_transportadora.setText("1");
            //             jComboBox_transportadoraInt.setSelectedIndex(1);
        } else {
            if (ComboFocu == 0) {
            } else {
            }
        }
    }//GEN-LAST:event_jComboBox_transportadoraItemStateChanged

    private void jComboBox_modalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_modalidadeItemStateChanged
        //        manipula_transporte();
    }//GEN-LAST:event_jComboBox_modalidadeItemStateChanged

    private void jTableListaProduto_NotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProduto_NotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableListaProduto_NotaMouseEntered

    private void jTableListaProduto_NotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProduto_NotaMouseClicked

        if (jTableListaProduto_Nota.isEnabled()) {
            String busca_Lista = "" + jTableListaProduto_Nota.getValueAt(jTableListaProduto_Nota.getSelectedRow(), 8);
            //            jLabel_Id_Mov.setText((busca_Lista));
            //            jLabelIdMovi.setText((busca_Lista));
            String busca_item = "" + jTableListaProduto_Nota.getValueAt(jTableListaProduto_Nota.getSelectedRow(), 0);
//            jLabel_IdMovimento.setText(busca_item);
            //            Evento_Busca_Movimento_Nota();
            //            flag_salvar = 2;
//            jTextField_Quantidade_Nota.requestFocus();
            btnRemoverUmProduto.setEnabled(true);
            //            jButton_Adicionar_Produto_Nota.setText("Alterar produto");
//            PreencheDadosAlterar();
//            FlagAlterar = 1;
//            Referencia_Movimento = "" + jTableListaProduto_Nota.getValueAt(jTableListaProduto_Nota.getSelectedRow(), 0);
            //                        JOptionPane.showMessageDialog(rootPane, Referencia_Movimento);
        } else {
        }
    }//GEN-LAST:event_jTableListaProduto_NotaMouseClicked

    private void txtBuscarUmProdutoPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUmProdutoPorNomeKeyPressed

        movimentoCadastroController.validarNomeProduto(this, evt);
    }//GEN-LAST:event_txtBuscarUmProdutoPorNomeKeyPressed

    private void txtBuscarUmProdutoPorNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarUmProdutoPorNomeFocusLost

    }//GEN-LAST:event_txtBuscarUmProdutoPorNomeFocusLost

    private void txtBuscarUmProdutoPorNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarUmProdutoPorNomeFocusGained
        // evento_Verifica();
    }//GEN-LAST:event_txtBuscarUmProdutoPorNomeFocusGained

    private void btnRemoverUmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUmProdutoActionPerformed

        btnRemoverUmProduto.setEnabled(false);
    }//GEN-LAST:event_btnRemoverUmProdutoActionPerformed

    private void btnLimparCampoBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCampoBuscaProdutoActionPerformed
        movimentoCadastroController.limparBuscarUmProdutoPorNome(this);
    }//GEN-LAST:event_btnLimparCampoBuscaProdutoActionPerformed

    private void btnInserirProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirProdutoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
//            BotaoAdicionarProduto();
        }
    }//GEN-LAST:event_btnInserirProdutoKeyPressed

    private void btnInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirProdutoActionPerformed
        movimentoCadastroController.chamaFormularioComplementar(this);
    }//GEN-LAST:event_btnInserirProdutoActionPerformed

    public void BotaoExcluir() {
        beans.setNota_status(3);
        beans.setId_nota(id_nota);
        dao.Excluir(beans);
        // this.dispose();
    }

    public void BotaoSalvar() {
        PreencherMeuTotal();
//        SelecionarNatureza();
        if (MinhaIdNota == "novo") {
            CarregaUltimo();
//            InsereDadosNota();
            dao.Salvar(beans);
            SalvarMovimentoBanco();
//            JOptionPane.showMessageDialog(rootPane, "Entrou novo");
        } else {
//            JOptionPane.showMessageDialog(rootPane, "Entrou alterar");
            beans.setNota_status(2);
//            beans.setId_nota(id_nota);
            beans.setId_referencia(id_referencia);
            dao.Alterar2(beans);
//            CarregaUltimo();
//            InsereDadosNota();
            dao.Salvar(beans);
            SalvarMovimentoBanco();
        }
//        SalvarTransporte();
    }

    public void SalvarTransporte() {
        beanst.setModalidade((String) jComboBox_modalidade.getSelectedItem());
        beanst.setTransportadora((String) jComboBox_transportadora.getSelectedItem());
        beanst.setMotorista(vol_motorista.getText());

        String placa = (vol_placa.getText());
        if (placa.equals("   -    ")) {
            beanst.setPlaca("");
        } else {
            beanst.setPlaca(vol_placa.getText());
        }
        String uf = (vol_uf.getText());
        if (uf.equals("  ")) {
            beanst.setUf("");
        } else {
            beanst.setUf(vol_uf.getText());
        }

        beanst.setQuantidade(vol_quantidade.getText());
        beanst.setEspecie(vol_especie.getText());
        beanst.setNumeracao(vol_numeracao.getText());
        beanst.setPesobruto(vol_peso_bruto.getText());
        beanst.setPesoliquido(vol_peso_liquido.getText());

        beanst.setOsnota(id_referencia);
        beanst.setOnline(0);
        daot.Alterar(beanst);
        beanst.setOnline(1);
        daot.Salvar(beanst);
    }

    public void SalvarMovimentoBanco() {
        MovimentoUpdatePrimario();
//        MovimentoBancoUpdateTodos();
        MovimentoBancoInsert();
    }

    public void MovimentoUpdatePrimario() {
        String busca = String.valueOf(id_referencia);
        conex.conexao();
        try {
            if (MinhaNatureza.equals("ENTRADA")) {
                java.sql.PreparedStatement pst = conex.con.prepareStatement("UPDATE movproduto as base SET qtd_mov=qtd_prod "
                        + " WHERE  base.nota_mov='" + busca + "'");
                pst.execute();
                System.out.println(" MovimentoUpdatePrimario -- MinhaNatureza ENTRADA - ok ");
            } else if (MinhaNatureza.equals("SAIDA")) {
                java.sql.PreparedStatement pst = conex.con.prepareStatement("UPDATE movproduto as base SET qtd_mov=-qtd_prod "
                        + " WHERE  base.nota_mov='" + busca + "'");
                pst.execute();
                System.out.println("MovimentoUpdatePrimario -- MinhaNatureza SAIDA - ok ");
            } else {
                System.out.println(" MovimentoUpdatePrimario -- MinhaNatureza ????????   -- ERRO");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao MovimentoUpdatePrimario() - " + ex);
        }
        conex.desconecta();
    }

    public void MovimentoBancoUpdateTodos() {
        String busca = String.valueOf(id_referencia);

        conex.conexao();
        try {
            java.sql.PreparedStatement pst = conex.con.prepareStatement("UPDATE movprodutobase as base\n"
                    + "      SET stmovimento=2 from movproduto as temp\n"
                    + " WHERE base.stmovimento = 3 and base.nota_mov='" + busca + "'");
            pst.execute();
//            JOptionPane.showMessageDialog(rootPane, " MovimentoBancoUpdateTodos "+id_referencia);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao MovimentoBancoUpdateTodos() . \\n" + ex);
        }
        conex.desconecta();
    }

    public void MovimentoBancoTemporarioApagar() {

        conexApaga.conexao();
        try {
            java.sql.PreparedStatement pst = conexApaga.con.prepareStatement("TRUNCATE TABLE movproduto RESTART IDENTITY;");
            pst.execute();
            System.out.println("aqui movimento temporario apagar ok");
//            JOptionPane.showMessageDialog(rootPane, " MovimentoBancoTemporarioApagar ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao MovimentoBancoTemporarioApagar() . \\n" + ex);
        }
        conexApaga.desconecta();
    }

    public void MovimentoBancoTemporario() {
        int busca = id_referencia;
        conexInsere.conexao();
        try {
            java.sql.PreparedStatement pst = conexInsere.con.prepareStatement(" INSERT INTO movproduto  (\n"
                    + "             id_prod_ent, data_mov, nota_mov, sistema_mov, qtd_mov, \n"
                    + "            qtd_prod, qtd_prod_ex, qtd_calc, qtd_calc_ex, valor_real, valor_moeda, \n"
                    + "            destino_mov, complemento_mov, registro_mov, status_mov, volume, \n"
                    + "            usuario_mov, modo_mov, total_mov)\n"
                    + "    SELECT  id_prod_ent, data_mov, nota_mov, sistema_mov, qtd_mov, \n"
                    + "       qtd_prod, qtd_prod_ex, qtd_calc, qtd_calc_ex, valor_real, valor_moeda, \n"
                    + "       destino_mov, complemento_mov, registro_mov, status_mov, volume, \n"
                    + "       usuario_mov, modo_mov, total_mov\n"
                    + "  FROM movprodutobase"
                    + " WHERE status_mov='ATIVO' and nota_mov='" + busca + "'");//// status_mov='ATIVO' and

            pst.execute();
            System.out.println(".............................................MovimentoBancoTemporario.......................");
//            JOptionPane.showMessageDialog(null, "MovimentoBancoTemporario");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao MovimentoBancoTemporario() . \\n" + ex);
        }
        conexInsere.desconecta();
    }

    public void MovimentoBancoInsert() {
        int busca = id_referencia;
        conex.conexao();
        try {
            java.sql.PreparedStatement pst1 = conex.con.prepareStatement("UPDATE movprodutobase as w\n"
                    + "   SET id_prod_ent=base.id_prod_ent, data_mov=base.data_mov, nota_mov=base.nota_mov, qtd_mov=base.qtd_mov, qtd_prod=base.qtd_prod, \n"
                    + "       qtd_prod_ex=base.qtd_prod_ex, qtd_calc=base.qtd_calc, qtd_calc_ex=base.qtd_calc_ex, valor_real=base.valor_real, valor_moeda=base.valor_moeda, \n"
                    + "       destino_mov=base.destino_mov, complemento_mov=base.complemento_mov, registro_mov=base.registro_mov, volume=base.volume, usuario_mov=base.usuario_mov, \n"
                    + "       modo_mov=base.modo_mov, total_mov=base.total_mov, sistema_mov=base.sistema_mov, stmovimento=base.stmovimento\n"
                    + "       FROM movproduto as base\n"
                    + " WHERE base.idmovtemp = w.id_mov ");
            pst1.execute();
            System.out.println("update \n ----------------------------------------------------------\n OK ");
            java.sql.PreparedStatement pst = conex.con.prepareStatement(" INSERT INTO movprodutobase  (\n"
                    + "             id_prod_ent, data_mov, nota_mov, sistema_mov, qtd_mov, \n"
                    + "            qtd_prod, qtd_prod_ex, qtd_calc, qtd_calc_ex, valor_real, valor_moeda, \n"
                    + "            destino_mov, complemento_mov, registro_mov, stmovimento, volume, \n"
                    + "            usuario_mov, modo_mov, total_mov,stsaldo)\n"
                    + "    SELECT  id_prod_ent, data_mov, nota_mov, sistema_mov, qtd_mov, \n"
                    + "       qtd_prod, qtd_prod_ex, qtd_calc, qtd_calc_ex, valor_real, valor_moeda, \n"
                    + "       destino_mov, complemento_mov, registro_mov, stmovimento, volume, \n"
                    + "       usuario_mov, modo_mov, total_mov,1\n"
                    + "  FROM movproduto"
                    + " WHERE  nota_mov='" + busca + "' and idmovtemp is null and stmovimento=1 and intmodotbl=1");//// status_mov='ATIVO' and

            pst.execute();
            System.out.println("insert \n -------------------------------------------------------\n OK ");
        } catch (SQLException ex) {
            System.out.println("Interface.MovimentoCadastroJIF.MovimentoBancoInsert  -- erro " + ex);
            JOptionPane.showMessageDialog(null, "Erro ao MovimentoBancoInsert() . \\n" + ex);
        }
        conex.desconecta();
    }

    public void CarregaFormulario() {

    }

    public void CarregaSistema() {
        System.out.println("-------- CarregaSistema ---------- " + MinhaIdNota);
        conex.conexao();
        conex.executaSql2("SELECT  id_referencianatureza,id_natureza,stnota,id_nota, id_referencianota,nota_observacao,desc_natureza,tipo_natureza,"
                + "ecft_nome,ecft_tipo,nota_documento,nota_situacao,nota_nota,nota_chave,nota_hora,nota_data,"
                + "modalidade, transportadora, motorista, placa, \n"
                + "       uf, quantidade, especie, numeracao, pesobruto, pesoliquido\n"
                + " FROM NOTA \n"
                + "inner join ecft on fornecedorint=sis_ecft \n"
                + "inner join natureza on naturezaint=id_referencianatureza\n"
                + "where id_nota is not null and id_nota !=0 and "
                + "id_nota ='" + MinhaIdNota + "' order by id_nota asc");
        try {
            conex.rs.last();
            String DescNatureza = (conex.rs.getString("desc_natureza"));
            String IdNatureza = (conex.rs.getString("id_referencianatureza"));
//            DescNatureza = IdNatureza + " " + DescNatureza;
            DescNatureza = DescNatureza + " | " + IdNatureza;
//            MinhaNaturezaInt = conex.rs.getInt("id_natureza");
            id_nota = conex.rs.getInt("id_nota");
            id_referencia = conex.rs.getInt("id_referencianota");
            jTextArea_Observacao.setText(conex.rs.getString("nota_observacao"));
            MinhaNatureza = conex.rs.getString("tipo_natureza");
            cbNatureza.setSelectedItem(DescNatureza);
//            jComboBox_Tipo_Fornecedor.setSelectedItem(conex.rs.getString("ecft_tipo"));
            cbCliente.setSelectedItem(conex.rs.getString("ecft_nome"));
            System.out.println("Interface.MovimentoCadastroJIF.CarregaSistema()" + conex.rs.getString("ecft_nome"));
//            jComboBox_Documento.setSelectedItem(conex.rs.getString("nota_documento"));
//            jComboBox_Situacao.setSelectedItem(conex.rs.getString("nota_situacao"));
            String nota_situacao_Visualizar = (conex.rs.getString("nota_situacao"));
            if (nota_situacao_Visualizar.equals("7-ENTRADA") | nota_situacao_Visualizar.equals("ENTRADA")) {
                jLabel_Status_Visualizar.setText("      ");
            } else {
                jLabel_Status_Visualizar.setText("Status : " + conex.rs.getString("nota_situacao"));
            }

            txtNota.setText(conex.rs.getString("nota_nota"));
            txtChave.setText(conex.rs.getString("nota_chave"));// 
            txtHora.setText(conex.rs.getString("nota_hora"));
            String insereData = (conex.rs.getString("nota_data"));

            try {
                data = formato.parse(insereData);
            } catch (ParseException exd) {
                System.out.println("erro data " + exd);
            }
            dataNota.setDate(data);
//            CarregaTransporte();
            jComboBox_modalidade.setSelectedItem((conex.rs.getString("modalidade")));
            jComboBox_transportadora.setSelectedItem(conex.rs.getString("transportadora"));
            String placa = (conex.rs.getString("placa"));
            if (placa == ("   -    ")) {
                vol_placa.setText(null);
            } else {
                vol_placa.setText(placa);
            }
            String uf = (conex.rs.getString("uf"));
            if (uf == ("   -    ")) {
                vol_uf.setText(null);
            } else {
                vol_uf.setText(uf);
            }
            vol_motorista.setText(conex.rs.getString("motorista"));
            vol_quantidade.setText(conex.rs.getString("quantidade"));
            vol_especie.setText(conex.rs.getString("especie"));
            vol_numeracao.setText(conex.rs.getString("numeracao"));
            vol_peso_bruto.setText(conex.rs.getString("pesobruto"));
            vol_peso_liquido.setText(conex.rs.getString("pesoliquido"));

        } catch (SQLException ex) {
            System.out.println("erro  CarregaSistema   " + ex);
//            JOptionPane.showMessageDialog(rootPane, "erro" + ex);
//            LimpaSistema();
        }
//        JOptionPane.showMessageDialog(rootPane, id_referencia);
        conex.desconecta();
        this.setTitle("Cadastro Movimento [ " + MinhaNatureza + " ] Id Referencia : " + id_referencia);
    }

    public void LimpaSistema() {

        txtNota.setText(null);
        txtChave.setText(null);
        txtHora.setText(null);
//            data = formato.parse(null);
        data = null;
        dataNota.setDate(data);
        LimpaTransporte();

    }

    public void LimpaTransporte() {
        jComboBox_modalidade.setSelectedItem("0-NÃO DEFINIDO");
        jComboBox_transportadora.setSelectedItem("NÃO DEFINIDO");
        vol_placa.setText(null);
        vol_uf.setText(null);
        vol_motorista.setText("");
        vol_quantidade.setText("");
        vol_especie.setText("");
        vol_numeracao.setText("");
        vol_peso_bruto.setText("");
        vol_peso_liquido.setText("");
    }

    public void LimpaSistema2() {

        txtChave.setText(null);
        txtHora.setText(null);
        txtNota.setText(null);
        data = null;
        dataNota.setDate(data);
        LimpaTransporte();
        lblInformacoes.setText("");
        System.out.println("LimpaSistema2  -- ");
    }

    public void CarregaUltimo() {
        conex.conexao();
        conex.executaSql2("SELECT  id_referencianota  FROM NOTA where id_referencianota is not null and id_referencianota !=0 order by id_referencianota asc");
        try {
            conex.rs.last();
            id_referencia = conex.rs.getInt("id_referencianota");
            id_referencia = id_referencia + 1;
            System.out.println("Interface.Movimento.MovimentoJIFAlterado.CarregaUltimo() \n " + id_referencia);
        } catch (SQLException ex) {
            id_referencia = 1;
        }
        conex.desconecta();
    }

    public void AtualizarTudo() {
//        PreencherFornecedor();
//        PreencherNatureza();
//        PreencherTransporte();
        LimparTabela();
        SelecaoReferencia_Movimento = null;
//        limpaCamposPalete();
//        jLabel_preenche_texto.setText("");
//        BloqueiaCamposPalete();
    }

    private void LimparTabela() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
//        jTablePalete.setModel(modelo);
        jTableListaProduto_Nota.setModel(modelo);
//        jTableListaProduto_Complemento.setModel(modelo);
//        jTableListaProduto_Palete_Produto.setModel(modelo);
    }

    private void LimparTabelaPalete() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
//        jTablePalete.setModel(modelo);
//        jTableListaProduto_Nota.setModel(modelo);
//        jTableListaProduto_Complemento.setModel(modelo);
//        jTableListaProduto_Palete_Produto.setModel(modelo);
    }

    public void PreencherMeuTotal() {
        String MeuValor;
        int MinhaOs = id_referencia;
        System.err.println("PreencherMeuTotal()                  INICIO ");
        conex_MeuTotal.conexao();

        conex_MeuTotal.executaSql("SELECT sum(qtd_prod) as qtd_prod , sum(qtd_calc) as calc_mov ,sum(valor_real*qtd_prod ) as valor_real ,nota_mov  from movproduto  where nota_mov='" + MinhaOs + "' and stmovimento = 1 and modo_mov='1' GROUP BY   movproduto.nota_mov order by nota_mov asc");
        try {
            conex_MeuTotal.rs.first();
            MeuTotal = (conex_MeuTotal.rs.getString("qtd_prod"));
            MeuValor = (conex_MeuTotal.rs.getString("valor_real"));
            System.err.println("PreencherMeuTotal()                  INICIO " + MeuValor);
            Double num4 = Double.parseDouble(String.valueOf(MeuValor));
            BigDecimal df = new BigDecimal(num4);
            NumberFormat nf = NumberFormat.getCurrencyInstance();
            nf.setMinimumFractionDigits(2);
            nf.setMaximumFractionDigits(2);
            String FormatoReal = nf.format(df);

            Double num4a = Double.parseDouble(String.valueOf(MeuTotal));
            BigDecimal dfa = new BigDecimal(num4a);
            NumberFormat nfa = NumberFormat.getInstance();
            nfa.setMinimumFractionDigits(3);
            nfa.setMaximumFractionDigits(3);
            String FormatoReala = nfa.format(dfa);
            FormatoReala = FormatoReala.replace(",0000", "");

            lblInformacoes.setText("<html><b> Total " + FormatoReala + "  </b><br>    " + FormatoReal + "</html>");
            System.err.println("PreencherMeuTotal()                  CERTO ");
            System.err.println(" Total   -           FormatoReala" + FormatoReala + "    FormatoReal    " + FormatoReal);
            MeuTotal = FormatoReal;
            System.err.println(" MeuTotal    -     FormatoReal          -        " + FormatoReal);
        } catch (SQLException ex) {
            System.err.println("PreencherMeuTotal()                  ERRO ");
            lblInformacoes.setText(" Total " + "  0    " + "R$ 0,00");
            MeuTotal = "0";
        }
        conex_MeuTotal.desconecta();

    }

    public void PreencherTransporte() {
        ComboFocu = 0;
        conex_Transporte.conexao();
        conex_Transporte.executaSql("select * from ecft where ecft_tipo = 'TRANSPORTE' and stecft=1 order by ecft_id asc");
        try {
            conex_Transporte.rs.first();
            jComboBox_transportadora.removeAllItems();
//            jComboBox_transportadoraInt.removeAllItems();
//            jComboBox_transportadora.addItem("NÃO DEFINIDO");
//            jComboBox_transportadoraInt.addItem("0");
            do {
                jComboBox_transportadora.addItem(conex_Transporte.rs.getString("ecft_nome"));
//                jComboBox_transportadoraInt.addItem(conex_Transporte.rs.getString("sis_ecft"));
                jComboBox_transportadora.setBackground(Color.GRAY);
            } while (conex_Transporte.rs.next());
            System.out.println("PreencherTransporte ok ");
            ComboFocu = 1;
        } catch (SQLException ex) {
            jComboBox_transportadora.setBackground(Color.red);
            System.out.println("PreencherTransporte erro " + ex);
        }
        conex_Transporte.desconecta();
        jComboBox_transportadora.setSelectedItem("NÃO DEFINIDO");
//        jComboBox_transportadoraInt.setSelectedItem("0");
    }

    public void RecebeIdNota(String IdNota) {
        MinhaIdNota = IdNota;
//        JOptionPane.showMessageDialog(rootPane, MinhaIdNota);
    }

    public void RecebeReferenciaMovimento(String ReferenciaMovi) {
//        Referencia_Movimento = ReferenciaMovi;
//        JOptionPane.showMessageDialog(rootPane, Referencia_Movimento); jComboBox_Situacao
    }

    public void RecebeDescricaoBusca(String MinhaBusca) {
        txtBuscarUmProdutoPorNome.setText(MinhaBusca);
    }

    public void InsereNaTabela() {
        conex.conexao();
        try {
            java.sql.PreparedStatement pstUpdate = conex.con.prepareStatement("TRUNCATE TABLE paletetemp RESTART IDENTITY;");
            pstUpdate.execute();
//            JOptionPane.showMessageDialog(null, "OK");
        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "ERRO" + ex);
        }
        try {
            java.sql.PreparedStatement pstUpdate = conex.con.prepareStatement("INSERT INTO paletetemp(\n"
                    + "             pctpad, lastro, altura, pctavu, totpct, unavu, totparc, \n"
                    + "            mov_palete, qtd_palete, nota_palete, verifica_principal, stpalete, \n" /// status_palete,
                    + "            usuario_palete, registro_palete, id_palete)\n"
                    + "    SELECT  pctpad, lastro, altura, pctavu, totpct, unavu, totparc, \n"
                    + "       mov_palete, qtd_palete, nota_palete, '0',  stpalete, \n"
                    + "       usuario_palete, registro_palete, id_palete\n"
                    + "  FROM palete where mov_palete ='" + SelecaoReferencia_Movimento + "' and stpalete=1 order by idlinha asc ");
            pstUpdate.execute();// '" + MinhaOs + "' 
            //  JOptionPane.showMessageDialog(null, "OK");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO insere" + ex);
        }

        conex.desconecta();
    }

    public void CarregaSistemaRepeteUltimo() {
        conex.conexao();
        conex.executaSql2("SELECT  id_referencianatureza,id_natureza,stnota,id_nota, id_referencianota,nota_observacao,desc_natureza,tipo_natureza,"
                + "ecft_nome,ecft_tipo,nota_documento,nota_situacao,nota_nota,nota_chave,nota_hora,nota_data,"
                + "modalidade, transportadora, motorista, placa, \n"
                + "       uf, quantidade, especie, numeracao, pesobruto, pesoliquido\n"
                + " FROM NOTA \n"
                + "inner join ecft on fornecedorint=sis_ecft \n"
                + "inner join natureza on naturezaint=id_referencianatureza\n"
                + "where id_nota is not null and id_nota !=0  " // and
                + " order by id_nota asc");//id_nota ='" + MinhaIdNota + "'
        try {
            conex.rs.last();
            String DescNatureza = (conex.rs.getString("desc_natureza"));
            String IdNatureza = (conex.rs.getString("id_referencianatureza"));
            DescNatureza = DescNatureza + " | " + IdNatureza;
//            MinhaNaturezaInt = conex.rs.getInt("id_natureza");
            MinhaNatureza = conex.rs.getString("tipo_natureza");
            cbNatureza.setSelectedItem(DescNatureza);
//            jComboBox_Tipo_Fornecedor.setSelectedItem(conex.rs.getString("ecft_tipo"));
            cbCliente.setSelectedItem(conex.rs.getString("ecft_nome"));
//            jComboBox_Documento.setSelectedItem(conex.rs.getString("nota_documento"));
//            jComboBox_Situacao.setSelectedItem(conex.rs.getString("nota_situacao"));
            String nota_situacao_Visualizar = (conex.rs.getString("nota_situacao"));
            if (nota_situacao_Visualizar.equals("7-ENTRADA") | nota_situacao_Visualizar.equals("ENTRADA")) {
                jLabel_Status_Visualizar.setText("      ");
            } else {
                jLabel_Status_Visualizar.setText("Status : " + conex.rs.getString("nota_situacao"));
            }
            txtNota.setText(conex.rs.getString("nota_nota"));
            txtChave.setText(conex.rs.getString("nota_chave"));// 
            txtHora.setText(conex.rs.getString("nota_hora"));
            String insereData = (conex.rs.getString("nota_data"));
            try {
                data = formato.parse(insereData);
            } catch (ParseException exd) {
                System.out.println("erro data " + exd);
            }
            dataNota.setDate(data);
        } catch (SQLException ex) {
            System.out.println("erro  CarregaSistema   " + ex);
        }
        conex.desconecta();
        this.setTitle("Cadastro Movimento [ " + MinhaNatureza + " ] Id Referencia : " + id_referencia);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDataAtual;
    public static javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnHoraAtual;
    private javax.swing.JButton btnInserirProduto;
    public static javax.swing.JButton btnLimparCampoBuscaProduto;
    private javax.swing.JButton btnRemoverUmProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    public static javax.swing.JComboBox<Natureza> cbNatureza;
    private com.toedter.calendar.JDateChooser dataNota;
    private javax.swing.JComboBox<String> jComboBox_modalidade;
    private javax.swing.JComboBox<String> jComboBox_transportadora;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Status_Visualizar;
    public static javax.swing.JLabel jLabel_Texto_Produto1;
    private javax.swing.JLabel jLabel_Titulo1;
    private javax.swing.JLabel jLabel_Titulo2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButton jRadioButton_ativa_Vizualizar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableListaProduto_Nota;
    private javax.swing.JTextArea jTextArea_Observacao;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnInformacao;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnTopo;
    private javax.swing.JPanel pnTransporte;
    public static javax.swing.JTextField txtBuscarUmProdutoPorNome;
    public static javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField vol_especie;
    private javax.swing.JTextField vol_motorista;
    private javax.swing.JTextField vol_numeracao;
    private javax.swing.JTextField vol_peso_bruto;
    private javax.swing.JTextField vol_peso_liquido;
    private javax.swing.JTextField vol_placa;
    private javax.swing.JTextField vol_quantidade;
    private javax.swing.JTextField vol_uf;
    // End of variables declaration//GEN-END:variables

    public JPanel getPnDados() {
        return pnDados;
    }

    public JPanel getPnInformacao() {
        return pnInformacao;
    }

    public JPanel getPnPrincipal() {
        return pnPrincipal;
    }

    public JPanel getPnTopo() {
        return pnTopo;
    }

    public JPanel getPnTransporte() {
        return pnTransporte;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnDataAtual() {
        return btnDataAtual;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnHoraAtual() {
        return btnHoraAtual;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JDateChooser getDataNota() {
        return dataNota;
    }

    public JTextField getTxtChave() {
        return txtChave;
    }

    public JTextField getTxtHora() {
        return txtHora;
    }

    public JTextField getTxtNota() {
        return txtNota;
    }

    public JComboBox<Natureza> getCbNatureza() {
        return cbNatureza;
    }

    public JComboBox<Cliente> getCbCliente() {
        return cbCliente;
    }

    public static JTextField getTxtBuscarUmProdutoPorNomeStatic() {
        return txtBuscarUmProdutoPorNome;
    }

    public static int getIdProduto() {
        return idProduto;
    }

    public static void setIdProduto(int idProduto) {
        MovimentoCadastroJIF.idProduto = idProduto;
    }

    public int getIdProdutoComun() {
        return idProduto;
    }

    public void setIdProdutoComun(int idProduto) {
        MovimentoCadastroJIF.idProduto = idProduto;
    }

    public JTextField getTxtBuscarUmProdutoPorNomeComun() {
        return txtBuscarUmProdutoPorNome;
    }

    public JButton getBtnInserirProduto() {
        return btnInserirProduto;
    }

    public JButton getBtnLimparCampoBuscaProduto() {
        return btnLimparCampoBuscaProduto;
    }

    public JButton getBtnRemoverUmProduto() {
        return btnRemoverUmProduto;
    }

    public static List<Beans_Movimento> getMovimentos() {
        return movimentos;
    }

    public static void setMovimentos(List<Beans_Movimento> movimentos) {
        MovimentoCadastroJIF.movimentos = movimentos;
    }

}
