/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
///  jComboBox_Natureza formulario jLabel_Calculado
package view.internal;

 
import com.toedter.calendar.JDateChooser;
import controller.MovimentoCadastroController;
import enums.TipoMovimentacao;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Cliente;
import model.Natureza;
import model.NotaFiscal;

/**
 *
 * @author edson
 */
/// pree
public class NotaCadastroJIF extends javax.swing.JInternalFrame {

    int ComboFocu = 0;

    private static int idProduto = 0;
    MovimentoCadastroController movimentoCadastroController;

    NotaFiscal notaFiscal;

    /**
     * Creates new form MovimentoJIF
     */
    public NotaCadastroJIF(NotaFiscal notaFiscal) {
        movimentoCadastroController = new MovimentoCadastroController(this);
        initComponents();
        movimentoCadastroController.mudarCorPaineis(this);
        movimentoCadastroController.carregarCliente(this);
        movimentoCadastroController.carregarNatureza(this);
        movimentoCadastroController.carregarTipoMovimentacao(this);
        this.notaFiscal = notaFiscal;
        movimentoCadastroController.carregarNotaFiscal(this, notaFiscal);
         jMenuBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnTopo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbNatureza = new javax.swing.JComboBox<>();
        dataNota = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        btnDataAtual = new javax.swing.JButton();
        btnHoraAtual = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnDados = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        btnInserirProduto = new javax.swing.JButton();
        btnLimparCampoBuscaProduto = new javax.swing.JButton();
        btnRemoverUmProduto = new javax.swing.JButton();
        txtBuscarUmProdutoPorNome = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel_Titulo3 = new javax.swing.JLabel();
        pnTransporte = new javax.swing.JPanel();
        jLabel_Titulo1 = new javax.swing.JLabel();
        txtMotorista = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        jLabel_Titulo2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtVolQuantidade = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtVolEspecie = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPesoLiquido = new javax.swing.JTextField();
        txtPesoBruto = new javax.swing.JTextField();
        txtVolNumeracao = new javax.swing.JTextField();
        pnInformacao = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAreaObservacao = new javax.swing.JTextArea();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cbTipoMovimentacao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Adicionar uma movimentação");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnPrincipal.setBackground(new java.awt.Color(0, 255, 204));

        pnTopo.setBackground(new java.awt.Color(0, 255, 204));
        pnTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Natureza da Operação :");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Cliente / Fornecedor:");

        cbNatureza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNaturezaItemStateChanged(evt);
            }
        });
        cbNatureza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbNaturezaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbNaturezaFocusLost(evt);
            }
        });
        cbNatureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNaturezaActionPerformed(evt);
            }
        });
        cbNatureza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNaturezaKeyPressed(evt);
            }
        });

        dataNota.setDateFormatString("dd'/'MM'/'yyyy");
        dataNota.setInheritsPopupMenu(true);

        jLabel3.setText("Data :");

        jLabel4.setText("Hora :");

        txtNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotaFocusLost(evt);
            }
        });
        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNotaKeyReleased(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nota:");

        txtChave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChaveFocusLost(evt);
            }
        });
        txtChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaveActionPerformed(evt);
            }
        });
        txtChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChaveKeyPressed(evt);
            }
        });

        jLabel7.setText("Chave :");

        cbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClienteItemStateChanged(evt);
            }
        });
        cbCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbClienteFocusLost(evt);
            }
        });
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });
        cbCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbClienteKeyPressed(evt);
            }
        });

        btnDataAtual.setForeground(new java.awt.Color(255, 51, 51));
        btnDataAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-calendário-20.png"))); // NOI18N
        btnDataAtual.setToolTipText("Atualizar Campos");
        btnDataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAtualActionPerformed(evt);
            }
        });
        btnDataAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDataAtualKeyPressed(evt);
            }
        });

        btnHoraAtual.setForeground(new java.awt.Color(255, 51, 51));
        btnHoraAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-presente-20.png"))); // NOI18N
        btnHoraAtual.setToolTipText("Limpa Relogio");
        btnHoraAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraAtualActionPerformed(evt);
            }
        });
        btnHoraAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHoraAtualKeyPressed(evt);
            }
        });

        txtHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFocusLost(evt);
            }
        });
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoraKeyReleased(evt);
            }
        });

        lblInformacoes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacoes.setText(" ");
        lblInformacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
        pnTopo.setLayout(pnTopoLayout);
        pnTopoLayout.setHorizontalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNatureza, 0, 349, Short.MAX_VALUE)
                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHoraAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(btnDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTopoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTopoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNota, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTopoLayout.setVerticalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNatureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(7, 7, 7)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHoraAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTopoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDataAtual, btnHoraAtual, cbCliente, cbNatureza, dataNota, jLabel13, jLabel14, jLabel3, jLabel4, txtHora});

        jTabbedPane1.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N

        pnDados.setBackground(new java.awt.Color(0, 255, 204));

        lblProduto.setText("Produto :");

        btnInserirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inserir-20.png"))); // NOI18N
        btnInserirProduto.setText("Inserir");
        btnInserirProduto.setToolTipText("Inclui Produto");
        btnInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirProdutoActionPerformed(evt);
            }
        });
        btnInserirProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInserirProdutoKeyPressed(evt);
            }
        });

        btnLimparCampoBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-vassoura-20.png"))); // NOI18N
        btnLimparCampoBuscaProduto.setText("Limpar");
        btnLimparCampoBuscaProduto.setToolTipText("Limpa Produto");
        btnLimparCampoBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCampoBuscaProdutoActionPerformed(evt);
            }
        });

        btnRemoverUmProduto.setForeground(new java.awt.Color(255, 51, 51));
        btnRemoverUmProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remover-20.png"))); // NOI18N
        btnRemoverUmProduto.setText("Excluir");
        btnRemoverUmProduto.setToolTipText("Exclui Produto");
        btnRemoverUmProduto.setEnabled(false);
        btnRemoverUmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUmProdutoActionPerformed(evt);
            }
        });

        txtBuscarUmProdutoPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarUmProdutoPorNomeKeyPressed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tabela);

        jLabel_Titulo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo3.setText("Itens");
        jLabel_Titulo3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblProduto)
                        .addGap(8, 8, 8)
                        .addComponent(txtBuscarUmProdutoPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparCampoBuscaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverUmProduto)
                        .addContainerGap())
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(jLabel_Titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
            .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnDadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInserirProduto, btnLimparCampoBuscaProduto, btnRemoverUmProduto});

        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUmProdutoPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduto)
                    .addComponent(btnInserirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCampoBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverUmProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInserirProduto, btnLimparCampoBuscaProduto, btnRemoverUmProduto, lblProduto, txtBuscarUmProdutoPorNome});

        jTabbedPane1.addTab("Dados", pnDados);

        pnTransporte.setBackground(new java.awt.Color(0, 255, 204));

        jLabel_Titulo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo1.setText("Transportadora");
        jLabel_Titulo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtMotorista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMotoristaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMotoristaFocusLost(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Motorista :");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("UF");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Placa Veiculo");

        txtUf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUfFocusLost(evt);
            }
        });

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });

        jLabel_Titulo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo2.setText("Volumes transportados");
        jLabel_Titulo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Quantidade");

        txtVolQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolQuantidadeActionPerformed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Espécie");

        txtVolEspecie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolEspecieFocusLost(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Numeração");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Peso Bruto");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Peso Liquido");

        txtPesoLiquido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoLiquidoActionPerformed(evt);
            }
        });

        txtVolNumeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolNumeracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTransporteLayout = new javax.swing.GroupLayout(pnTransporte);
        pnTransporte.setLayout(pnTransporteLayout);
        pnTransporteLayout.setHorizontalGroup(
            pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Titulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTransporteLayout.createSequentialGroup()
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtVolQuantidade, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtVolEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVolNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPesoBruto)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnTransporteLayout.createSequentialGroup()
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 466, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnTransporteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel23, jLabel25, jLabel26, jLabel27, jLabel30, txtPesoBruto, txtPesoLiquido, txtVolEspecie, txtVolNumeracao, txtVolQuantidade});

        pnTransporteLayout.setVerticalGroup(
            pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21))
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoBruto)
                            .addComponent(txtPesoLiquido)
                            .addComponent(txtVolEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVolQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVolNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTransporteLayout.createSequentialGroup()
                        .addGroup(pnTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );

        pnTransporteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel19, jLabel21, jLabel28});

        jTabbedPane1.addTab("Transportadora/Volumes", pnTransporte);

        pnInformacao.setBackground(new java.awt.Color(0, 255, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Observações");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAreaObservacao.setColumns(20);
        txtAreaObservacao.setLineWrap(true);
        txtAreaObservacao.setRows(5);
        txtAreaObservacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane7.setViewportView(txtAreaObservacao);

        javax.swing.GroupLayout pnInformacaoLayout = new javax.swing.GroupLayout(pnInformacao);
        pnInformacao.setLayout(pnInformacaoLayout);
        pnInformacaoLayout.setHorizontalGroup(
            pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1114, Short.MAX_VALUE)
            .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnInformacaoLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE))
                    .addGap(4, 4, 4)))
        );
        pnInformacaoLayout.setVerticalGroup(
            pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(pnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInformacaoLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Informações Adicionais", pnInformacao);

        btnExcluir.setBackground(new java.awt.Color(255, 51, 0));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-24.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancelar-24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-24.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de movimentação:");

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnTopo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(cbTipoMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pnPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcluir, cbTipoMovimentacao, jLabel1});

        jMenu1.setText("File");

        jMenuItem4.setText("Repete ultimo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Atualiza tabela");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Gerar copia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

//        AtualizarTudo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void MovimentoBancoTemporarioAlterado() {

    }


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        PreencherTabela();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente fazer uma cópia ? ");
        if (resposta == JOptionPane.YES_OPTION) {
//            MinhaCopia = "executando";
//            ExecutaCopia();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed

        if (txtHora.getText().length() >= 5) {

        }

    }//GEN-LAST:event_txtHoraKeyPressed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusLost
        if (txtHora.getText().isEmpty()) {
            txtHora.setText("  :  ");
        } else if (txtHora.getText().equals("  :  ")) {
            txtHora.setText("  :  ");
        } else {
//            AjustaMinhaHora();
        }
    }//GEN-LAST:event_txtHoraFocusLost


    private void btnHoraAtualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHoraAtualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoraAtualKeyPressed

    private void btnHoraAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraAtualActionPerformed
        movimentoCadastroController.horaAtual(this);
    }//GEN-LAST:event_btnHoraAtualActionPerformed

    private void btnDataAtualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDataAtualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataAtualKeyPressed

    private void btnDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAtualActionPerformed
        movimentoCadastroController.dataAtual(this);
    }//GEN-LAST:event_btnDataAtualActionPerformed

    private void cbClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbClienteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtHora.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
//            PreencherFornecedor();
        }
    }//GEN-LAST:event_cbClienteKeyPressed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClienteActionPerformed

    private void txtChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChaveKeyPressed
        if (evt.getKeyCode() == evt.VK_F2) {
            System.out.println("Interface.Movimento.MovimentoJIFAlterado.jTextField_Chave_NotaKeyPressed()\n F12");

        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
        }
        if (evt.getKeyCode() == evt.VK_F3) {

        }
        if (evt.getKeyCode() == evt.VK_F12) {
            
        }
    }//GEN-LAST:event_txtChaveKeyPressed

    private void txtChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaveActionPerformed

    private void txtChaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChaveFocusLost
        if (txtChave.getText().isEmpty()) {
        } else {
        }
    }//GEN-LAST:event_txtChaveFocusLost

    private void txtNotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaKeyReleased

    private void txtNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (txtChave.isEnabled()) {
                txtChave.requestFocus();
            } else {
            }
        }
    }//GEN-LAST:event_txtNotaKeyPressed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void txtNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotaFocusLost

    }//GEN-LAST:event_txtNotaFocusLost

    private void cbNaturezaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNaturezaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            dataNota.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
//            PreencherNatureza();
        }
    }//GEN-LAST:event_cbNaturezaKeyPressed

    private void cbNaturezaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbNaturezaFocusLost
//        SelecionarNatureza();
        //        if (jLabel_OS.getText() == "Novo") {
        //            preencheNatureza_Tipo();
        //        } else {
        //        }
    }//GEN-LAST:event_cbNaturezaFocusLost

    private void cbNaturezaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNaturezaItemStateChanged

    }//GEN-LAST:event_cbNaturezaItemStateChanged

    public void ManipulaNatureza() {

    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        CarregaSistemaRepeteUltimo();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClienteItemStateChanged


    }//GEN-LAST:event_cbClienteItemStateChanged

    private void cbClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusLost
//        SelecionarFornecedor();
    }//GEN-LAST:event_cbClienteFocusLost


    private void cbNaturezaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbNaturezaFocusGained
//        SelecionarNaturezaInt = 1;
//        ComboFocuNatureza = 1;
    }//GEN-LAST:event_cbNaturezaFocusGained

    private void txtHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyReleased
//        AjustaMinhaHora();
    }//GEN-LAST:event_txtHoraKeyReleased

    private void cbNaturezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNaturezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNaturezaActionPerformed

    private void cbClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusGained
//        ComboFocuFornecedor = 1;

    }//GEN-LAST:event_cbClienteFocusGained

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
//        LimpaSistema();
//        LimpaCampoProduto();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        EventoFechaMovimento();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        movimentoCadastroController.excluirNota(this);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        movimentoCadastroController.limparBuscarUmProdutoPorNome(this);
        movimentoCadastroController.limparTabela(this);
        movimentoCadastroController.limparCampos(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        movimentoCadastroController.salvarNota(this);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtVolEspecieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolEspecieFocusLost
        txtVolEspecie.setText(txtVolEspecie.getText().toUpperCase());
    }//GEN-LAST:event_txtVolEspecieFocusLost

    private void txtVolNumeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolNumeracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolNumeracaoActionPerformed

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
//        AjustaMinhaPlaca();
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
        //aqui
        //  AjustaMinhaPlaca();
        txtPlaca.setText(txtPlaca.getText().toUpperCase());
    }//GEN-LAST:event_txtPlacaFocusLost

    private void txtUfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUfFocusLost
//        AjustaMinhaUf();
        txtUf.setText(txtUf.getText().toUpperCase());
    }//GEN-LAST:event_txtUfFocusLost

    private void txtMotoristaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotoristaFocusLost
        txtMotorista.setText(txtMotorista.getText().toUpperCase());
        txtMotorista.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtMotoristaFocusLost

    private void txtMotoristaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotoristaFocusGained
        //        vol_motorista.setBackground(Color.cyan);
    }//GEN-LAST:event_txtMotoristaFocusGained

    private void tabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseEntered

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        movimentoCadastroController.selecionarUmItem(this, evt);

    }//GEN-LAST:event_tabelaMouseClicked

    private void btnRemoverUmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUmProdutoActionPerformed
        movimentoCadastroController.removerUmItem(this);
    }//GEN-LAST:event_btnRemoverUmProdutoActionPerformed

    private void btnLimparCampoBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCampoBuscaProdutoActionPerformed
        movimentoCadastroController.limparBuscarUmProdutoPorNome(this);
    }//GEN-LAST:event_btnLimparCampoBuscaProdutoActionPerformed

    private void btnInserirProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirProdutoKeyPressed
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            movimentoCadastroController.chamaFormularioComplementar(this);
//        }
    }//GEN-LAST:event_btnInserirProdutoKeyPressed

    private void btnInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirProdutoActionPerformed
        movimentoCadastroController.chamaFormularioComplementar(this);
        txtBuscarUmProdutoPorNome.requestFocus();
    }//GEN-LAST:event_btnInserirProdutoActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPesoLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoLiquidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoLiquidoActionPerformed

    private void txtVolQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolQuantidadeActionPerformed

    private void txtBuscarUmProdutoPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUmProdutoPorNomeKeyPressed
        movimentoCadastroController.validarNomeProduto(this, evt);
    }//GEN-LAST:event_txtBuscarUmProdutoPorNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDataAtual;
    public static javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnHoraAtual;
    private javax.swing.JButton btnInserirProduto;
    public static javax.swing.JButton btnLimparCampoBuscaProduto;
    private javax.swing.JButton btnRemoverUmProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    public static javax.swing.JComboBox<Natureza> cbNatureza;
    private javax.swing.JComboBox<TipoMovimentacao> cbTipoMovimentacao;
    private com.toedter.calendar.JDateChooser dataNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Titulo1;
    private javax.swing.JLabel jLabel_Titulo2;
    private javax.swing.JLabel jLabel_Titulo3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblInformacoes;
    public static javax.swing.JLabel lblProduto;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnInformacao;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnTopo;
    private javax.swing.JPanel pnTransporte;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea txtAreaObservacao;
    public static javax.swing.JTextField txtBuscarUmProdutoPorNome;
    public static javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMotorista;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPesoBruto;
    private javax.swing.JTextField txtPesoLiquido;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtUf;
    private javax.swing.JTextField txtVolEspecie;
    private javax.swing.JTextField txtVolNumeracao;
    private javax.swing.JTextField txtVolQuantidade;
    // End of variables declaration//GEN-END:variables

    public JPanel getPnDados() {
        return pnDados;
    }

    public JPanel getPnInformacao() {
        return pnInformacao;
    }

    public JPanel getPnPrincipal() {
        return pnPrincipal;
    }

    public JPanel getPnTopo() {
        return pnTopo;
    }

    public JPanel getPnTransporte() {
        return pnTransporte;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnDataAtual() {
        return btnDataAtual;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnHoraAtual() {
        return btnHoraAtual;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JDateChooser getDataNota() {
        return dataNota;
    }

    public JTextField getTxtChave() {
        return txtChave;
    }

    public JTextField getTxtHora() {
        return txtHora;
    }

    public JTextField getTxtNota() {
        return txtNota;
    }

    public JComboBox<Natureza> getCbNatureza() {
        return cbNatureza;
    }

    public JComboBox<Cliente> getCbCliente() {
        return cbCliente;
    }

    public static JTextField getTxtBuscarUmProdutoPorNomeStatic() {
        return txtBuscarUmProdutoPorNome;
    }

    public static int getIdProduto() {
        return idProduto;
    }

    public static void setIdProduto(int idProduto) {
        NotaCadastroJIF.idProduto = idProduto;
    }

    public int getIdProdutoComun() {
        return idProduto;
    }

    public void setIdProdutoComun(int idProduto) {
        NotaCadastroJIF.idProduto = idProduto;
    }

    public JTextField getTxtBuscarUmProdutoPorNomeComun() {
        return txtBuscarUmProdutoPorNome;
    }

    public JButton getBtnInserirProduto() {
        return btnInserirProduto;
    }

    public JButton getBtnLimparCampoBuscaProduto() {
        return btnLimparCampoBuscaProduto;
    }

    public JButton getBtnRemoverUmProduto() {
        return btnRemoverUmProduto;
    }

    public JTable getTabela() {
        return tabela;
    }

    public JTextArea getTxtAreaObservacao() {
        return txtAreaObservacao;
    }

    public void setTxtAreaObservacao(JTextArea txtAreaObservacao) {
        this.txtAreaObservacao = txtAreaObservacao;
    }

    public JTextField getTxtMotorista() {
        return txtMotorista;
    }

    public JTextField getTxtPesoBruto() {
        return txtPesoBruto;
    }

    public JTextField getTxtPesoLiquido() {
        return txtPesoLiquido;
    }

    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    public JTextField getTxtUf() {
        return txtUf;
    }

    public JTextField getTxtVolEspecie() {
        return txtVolEspecie;
    }

    public JTextField getTxtVolNumeracao() {
        return txtVolNumeracao;
    }

    public JTextField getTxtVolQuantidade() {
        return txtVolQuantidade;
    }

    public JComboBox<TipoMovimentacao> getCbTipoMovimentacao() {
        return cbTipoMovimentacao;
    }

    public void setCbTipoMovimentacao(JComboBox<TipoMovimentacao> cbTipoMovimentacao) {
        this.cbTipoMovimentacao = cbTipoMovimentacao;
    }

    public NotaFiscal getNotaFiscal() {
        return notaFiscal;
    }

    public void setNotaFiscal(NotaFiscal notaFiscal) {
        this.notaFiscal = notaFiscal;
    }

    public static JLabel getLblProduto() {
        return lblProduto;
    }
    

}
