/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/// jComboBox_Unidade
package view.internal;

import ConectaBanco.ConexaoBD;
import Interface.Principal;
import ModeloBeans.Beans_Movimento;
import ModeloBeans.Beans_Produto;
import ModeloBeans.ModeloTabela;
import ModeloDao.Dao_Movimento;
import ModeloDao.Dao_Produto;
import UTIL.ControleCores;
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Container;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author edson
 */
public class ProdutoCadastroJIF extends javax.swing.JInternalFrame {

    Beans_Produto Bprod = new Beans_Produto();
    Dao_Produto Dprod = new Dao_Produto();
    Dao_Movimento Mdao = new Dao_Movimento();
    Beans_Movimento Mbeans = new Beans_Movimento();
    ConexaoBD conex = new ConexaoBD();
    ConexaoBD conex3 = new ConexaoBD();
    String UltimaId;
    int NumeroUltimaId;
    int un_prod;
    int IntModoValor = 0;
    int ComboFocu = 0;
    int id_referencia;

    /**
     * Creates new form JIFTEste
     */
    public ProdutoCadastroJIF() {
        initComponents();
        remover_Ico();
        PreencheUnidade();
        EscondeInsereSaldoInicio();

        pnPrincipal.setBackground(ControleCores.pegarCorPadrao());
        pnBotoes.setBackground(ControleCores.pegarCorPadrao());
        pnCampos.setBackground(ControleCores.pegarCorPadrao());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        jLabel_Saldo_Prod2 = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        jLabel_Id_Secundario2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel_Sistema2 = new javax.swing.JLabel();
        jButton_Excluir = new javax.swing.JButton();
        pnCampos = new javax.swing.JPanel();
        jTextField_Tipo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Valor = new javax.swing.JTextField();
        jTextField_edicao = new javax.swing.JTextField();
        jTextField_Desc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Guia4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonNovaUnidade = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_Valor2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Obs = new javax.swing.JTextArea();
        jComboBox_Unidade = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jSpinnerNcm = new javax.swing.JSpinner();
        jSpinnerCfop = new javax.swing.JSpinner();
        jSpinnerEstoqueMinimo = new javax.swing.JSpinner();
        jComboBox_Unidade_Int = new javax.swing.JComboBox<>();
        jLabel_Exibe_Informacao = new javax.swing.JLabel();
        jTextFieldInsereSaldo = new javax.swing.JTextField();
        jButtonInsereSaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de produto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnPrincipal.setBackground(new java.awt.Color(0, 255, 204));
        pnPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Saldo_Prod2.setText("  Saldo Produto : Zerado");
        jLabel_Saldo_Prod2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Saldo_Prod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Saldo_Prod2MouseClicked(evt);
            }
        });

        pnBotoes.setBackground(new java.awt.Color(0, 255, 204));
        pnBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Id_Secundario2.setText("novo");

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-24.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancelar-24.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel_Sistema2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel_Sistema2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Sistema2.setText("Sistema");
        jLabel_Sistema2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Excluir.setBackground(new java.awt.Color(255, 51, 0));
        jButton_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-24.png"))); // NOI18N
        jButton_Excluir.setText("Excluir");
        jButton_Excluir.setEnabled(false);
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotoesLayout = new javax.swing.GroupLayout(pnBotoes);
        pnBotoes.setLayout(pnBotoesLayout);
        pnBotoesLayout.setHorizontalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel_Id_Secundario2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Sistema2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Excluir)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pnBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonSalvar, jButton_Excluir});

        pnBotoesLayout.setVerticalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Sistema2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSalvar)
                .addComponent(jButtonCancelar)
                .addComponent(jButton_Excluir)
                .addComponent(jLabel_Id_Secundario2))
        );

        pnCampos.setBackground(new java.awt.Color(0, 255, 204));
        pnCampos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField_Tipo.setToolTipText("digite");
        jTextField_Tipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_TipoFocusGained(evt);
            }
        });
        jTextField_Tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_TipoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_TipoKeyReleased(evt);
            }
        });

        jLabel13.setText("Tipo:");

        jTextField_Valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_ValorFocusLost(evt);
            }
        });
        jTextField_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ValorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ValorKeyReleased(evt);
            }
        });

        jTextField_edicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_edicaoFocusGained(evt);
            }
        });
        jTextField_edicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_edicaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_edicaoKeyReleased(evt);
            }
        });

        jTextField_Desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_DescFocusGained(evt);
            }
        });
        jTextField_Desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_DescKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_DescKeyReleased(evt);
            }
        });

        jLabel14.setText("Descrição :");

        jLabel_Guia4.setText("N°:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Estoque Min.");

        jButtonNovaUnidade.setText("+");
        jButtonNovaUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaUnidadeActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cfop");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Ncm");

        jLabel_Valor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Valor2.setText("Valor");

        jTextArea_Obs.setColumns(20);
        jTextArea_Obs.setRows(5);
        jTextArea_Obs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_ObsFocusGained(evt);
            }
        });
        jTextArea_Obs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea_ObsKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea_Obs);

        jComboBox_Unidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_UnidadeItemStateChanged(evt);
            }
        });
        jComboBox_Unidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_UnidadeKeyPressed(evt);
            }
        });

        jLabel18.setText("Unidade:");

        jSpinnerNcm.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99999999, 1));

        jSpinnerCfop.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));

        jSpinnerEstoqueMinimo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        javax.swing.GroupLayout pnCamposLayout = new javax.swing.GroupLayout(pnCampos);
        pnCampos.setLayout(pnCamposLayout);
        pnCamposLayout.setHorizontalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel_Guia4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Tipo)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addComponent(jTextField_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_Desc)))
                    .addGroup(pnCamposLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerCfop, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCamposLayout.createSequentialGroup()
                                .addComponent(jButtonNovaUnidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Unidade_Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinnerEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnCamposLayout.setVerticalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Guia4)
                    .addComponent(jComboBox_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaUnidade)
                    .addComponent(jComboBox_Unidade_Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel_Valor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCfop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_Exibe_Informacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonInsereSaldo.setText("+");
        jButtonInsereSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsereSaldoActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo :");

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Saldo_Prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInsereSaldo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Exibe_Informacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(jButtonInsereSaldo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Saldo_Prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Exibe_Informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInsereSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonInsereSaldo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Repetir Ultimo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cópia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Valor");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTextField_TipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TipoKeyPressed
//        this.excutaBotao(evt);
//        ContaCaracteresTipo();
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_Desc.requestFocus();
        }
        //        if (evt.getKeyCode() == evt.VK_UP) {
        //            jTextField_Desc.requestFocus();
        //        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextField_Desc.requestFocus();
        }
        //        if (evt.getKeyCode() == evt.VK_LEFT) {
        //            jTextField_Desc.requestFocus();
        //        }
        //        if (evt.getKeyCode() == evt.VK_RIGHT) {
        //            jComboBox_Unidade.requestFocus();
        //        }
    }//GEN-LAST:event_jTextField_TipoKeyPressed

    private void jTextField_TipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TipoKeyReleased
        ContaCaracteresTipo();
    }//GEN-LAST:event_jTextField_TipoKeyReleased

    private void jTextField_DescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescKeyPressed
//        ContaCaracteresDescricao();
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_edicao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextField_Tipo.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextField_edicao.requestFocus();
        }
        //        if (evt.getKeyCode() == evt.VK_LEFT) {
        //            jTextField_Desc.requestFocus();
        //        }
        //        if (evt.getKeyCode() == evt.VK_RIGHT) {
        //            jComboBox_Unidade.requestFocus();
    }//GEN-LAST:event_jTextField_DescKeyPressed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        SalvaTemp();
        LimpaCampos();
        BuscaUltimaId();
        Principal.jLabelCodigoTela.setText("AtualizaProdutoLista");
        Principal.jButton1.doClick();
        String Id_Secundario2 = jLabel_Id_Secundario2.getText();
        if (Id_Secundario2 == "novo") {
        } else {
            Principal.jLabelCodigoTela.setText("FechaCadastroProdutoEditar");
            Principal.jButton1.doClick();
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if (jLabel_Id_Secundario2.getText() == "novo") {
            LimpaCampos();
        } else {
            CarregaDadosDaTabela();
        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBox_UnidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_UnidadeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_Valor.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
            PreencheUnidade();
        }
        if (evt.getKeyCode() == evt.VK_F2) {
            Principal.jLabelCodigoTela.setText("CadastroUnidade");
            Principal.jButton1.doClick();
        }
        //        if (evt.getKeyCode() == evt.VK_UP) {
        //            jTextField_Desc.requestFocus();
        //        }
        //        if (evt.getKeyCode() == evt.VK_DOWN) {
        //            jTextField_EstoqueMin.requestFocus();
        //        }
        if (evt.getKeyCode() == evt.VK_LEFT) {
            jTextField_edicao.requestFocus();
        }
        //        if (evt.getKeyCode() == evt.VK_RIGHT) {
        //            jComboBox_Unidade.requestFocus();
        //        }
    }//GEN-LAST:event_jComboBox_UnidadeKeyPressed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        BotaoExcluir();
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTextField_ValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ValorFocusLost
        ManipulaValor();
    }//GEN-LAST:event_jTextField_ValorFocusLost

    private void jTextField_ValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ValorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jSpinnerNcm.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextField_edicao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextArea_Obs.requestFocus();
        }
        //        if (evt.getKeyCode() == evt.VK_LEFT) {
        //            jTextField_Desc.requestFocus();
        //        }
        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jSpinnerNcm.requestFocus();
        }
    }//GEN-LAST:event_jTextField_ValorKeyPressed

    private void jTextField_edicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_edicaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jComboBox_Unidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextField_Desc.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextField_Valor.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_LEFT) {
            jTextField_Desc.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_RIGHT) {
            jComboBox_Unidade.requestFocus();
        }

        //       VerificaEdicaoNumero();
    }//GEN-LAST:event_jTextField_edicaoKeyPressed

    private void jTextField_edicaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_edicaoKeyReleased
        ContaCaracteresEdicao();
    }//GEN-LAST:event_jTextField_edicaoKeyReleased

    private void jButtonNovaUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaUnidadeActionPerformed
        Principal.jLabelCodigoTela.setText("CadastroUnidade");
        Principal.jButton1.doClick();
    }//GEN-LAST:event_jButtonNovaUnidadeActionPerformed

    private void jTextField_DescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescKeyReleased
        ContaCaracteresDescricao();
    }//GEN-LAST:event_jTextField_DescKeyReleased

    private void jTextField_TipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TipoFocusGained
        ContaCaracteresTipo();
    }//GEN-LAST:event_jTextField_TipoFocusGained

    private void jTextField_DescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_DescFocusGained
        ContaCaracteresDescricao();
    }//GEN-LAST:event_jTextField_DescFocusGained

    private void jTextField_edicaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_edicaoFocusGained
        ContaCaracteresEdicao();
    }//GEN-LAST:event_jTextField_edicaoFocusGained

    private void jTextField_ValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ValorFocusGained
        ContaCaracteresValor();
    }//GEN-LAST:event_jTextField_ValorFocusGained

    private void jTextField_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ValorKeyReleased
        ContaCaracteresValor();
    }//GEN-LAST:event_jTextField_ValorKeyReleased

    private void jTextArea_ObsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_ObsFocusGained
        ContaCaracteresObservacao();
    }//GEN-LAST:event_jTextArea_ObsFocusGained

    private void jTextArea_ObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_ObsKeyReleased
        ContaCaracteresObservacao();
    }//GEN-LAST:event_jTextArea_ObsKeyReleased

    private void jLabel_Saldo_Prod2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Saldo_Prod2MouseClicked
        EscondeInsereSaldo();
    }//GEN-LAST:event_jLabel_Saldo_Prod2MouseClicked

    private void jButtonInsereSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsereSaldoActionPerformed
        AlteraSaldo();
        CarregaDadosDaTabela();
    }//GEN-LAST:event_jButtonInsereSaldoActionPerformed

    private void jComboBox_UnidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_UnidadeItemStateChanged
        String selecao = (String) jComboBox_Unidade.getSelectedItem();
        if (selecao == null) {
        } else {
            if (ComboFocu == 0) {
            } else {
                jComboBox_Unidade_Int.setSelectedIndex(jComboBox_Unidade.getSelectedIndex());
                System.out.println("==========  String " + jComboBox_Unidade.getSelectedItem());
                System.out.println("==========  Int " + jComboBox_Unidade.getSelectedItem());
                System.out.println("==========  Int " + jComboBox_Unidade_Int.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jComboBox_UnidadeItemStateChanged

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.out.println("Interface.ProdCadastroJIF.jMenu2ActionPerformed()");
        ManipulaModoValor();
        ManipulaValor();
        jTextField_Valor.requestFocus();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CarregaUltimoIdSecundaria();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void CarregaUltimoIdSecundaria() {
        String IdSecundaria = null;
        conex.conexao();
        conex.executaSql2("SELECT  id_prod  FROM produto where sis_prod is not null and sis_prod !=0 order by sis_prod asc ");
        try {
            conex.rs.last();
            IdSecundaria = conex.rs.getString("id_prod");
//            id_referencia = id_referencia + 1;
        } catch (SQLException ex) {
            IdSecundaria = "novo";
        }
        conex.desconecta();
        jLabel_Id_Secundario2.setText(String.valueOf(IdSecundaria));
        CarregaDadosDaTabela();
        CarregaUltimo();
        jLabel_Id_Secundario2.setText("novo");
    }

    public void CarregaUltimo() {
        conex.conexao();
        conex.executaSql2("SELECT  sis_prod  FROM produto where sis_prod is not null and sis_prod !=0 order by sis_prod asc ");
        try {
            conex.rs.last();
            id_referencia = conex.rs.getInt("sis_prod");
//            JOptionPane.showMessageDialog(rootPane, id_referencia);
            id_referencia = id_referencia + 1;
//            JOptionPane.showMessageDialog(rootPane, id_referencia);
        } catch (SQLException ex) {
//            Logger.getLogger(UnidadeJIF.class.getName()).log(Level.SEVERE, null, ex);
            id_referencia = 1;
        }
//        JOptionPane.showMessageDialog(rootPane, id_referencia);
        conex.desconecta();
        jLabel_Sistema2.setText(String.valueOf(id_referencia));
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente fazer uma cópia ? ");
        if (resposta == JOptionPane.YES_OPTION) {
            CarregaUltimo();
            jLabel_Id_Secundario2.setText("novo");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void AlteraSaldo() {
        try {
            String InsereSaldo = jTextFieldInsereSaldo.getText();
            int IdSecundario = Integer.parseInt(jLabel_Id_Secundario2.getText());
            InsereSaldo = InsereSaldo.replace(".", "").replace(",", ".");
            Bprod.setSaldo_prod(Double.parseDouble(InsereSaldo));
            Bprod.setId_prod(IdSecundario);
            Dprod.AlteraSaldo(Bprod);

            Mbeans.setId_prod_ent(IdSecundario);
            Mdao.AlterarStatusSaldo_MovProdutoBase_Produto(Mbeans);
            String MinhaQtd = (jTextFieldInsereSaldo.getText());
            MinhaQtd = MinhaQtd.replace(",", ".");
            Mbeans.setQtd_prod(Double.parseDouble(MinhaQtd));
            Mbeans.setQtd_prod_ex((MinhaQtd));
            Mbeans.setQtd_calc(Double.parseDouble(MinhaQtd));
            Mbeans.setQtd_mov(Double.parseDouble(MinhaQtd));
            Mbeans.setQtd_calc_ex(MinhaQtd);
            Mbeans.setStsaldo(1);
            Mbeans.setStatus_mov(1);
            Mdao.SalvarQuantidadeProduto_MovProdutoBase(Mbeans);
        } catch (Error ex) {
            JOptionPane.showMessageDialog(rootPane, "erro " + ex);
        }
    }

    public void EventoLimpar() {
//        jTextFieldBusca.setText("");
//        jTextFieldBusca.requestFocus();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
//        jTable_Produto.setModel(modelo);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void remover_Ico() {
        this.setFrameIcon(null);

        // hack to remove system menu in Windows
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
    }

    public void PreencheUnidade() {
        conex.conexao();
        conex.executaSql2("SELECT  sigla_unidade, desc_unidade,id_referenciaunidade FROM unidade  where stunid =1   order by id_referenciaunidade asc ");
        try {
            conex.rs.first();
            jComboBox_Unidade.removeAllItems();
            jComboBox_Unidade_Int.removeAllItems();

            do {
                String unidade = (conex.rs.getString("sigla_unidade"));
                jComboBox_Unidade.addItem(unidade);
                jComboBox_Unidade_Int.addItem(conex.rs.getString("id_referenciaunidade"));
            } while (conex.rs.next());
            ComboFocu = 1;
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoCadastroJIF.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Interface.ProdCadastroJIF.PreencheUnidade()  ERRO    ------------------- " + ex);
            jComboBox_Unidade.addItem("UN");
            jComboBox_Unidade.setSelectedItem("UN");
            jComboBox_Unidade_Int.addItem("0");
            jComboBox_Unidade_Int.setSelectedItem("0");
        }
        conex.desconecta();
        jComboBox_Unidade_Int.setVisible(true);
    }

    public void ContaCaracteresTipo() {
        int Caracteres = 30;
        int conta = jTextField_Tipo.getText().length();
        if (conta == 30) {
            jTextField_Tipo.setBackground(Color.yellow);
            jLabel_Exibe_Informacao.setText("Limite de caracteres " + conta + "/" + Caracteres);
        } else if (conta > 30) {
            jTextField_Tipo.setBackground(Color.red);
            System.out.println("maior " + conta);
            jLabel_Exibe_Informacao.setText("Ultrapassou limite de caracteres " + conta + "/" + Caracteres);
        } else {
            jTextField_Tipo.setBackground(Color.white);
            System.out.println("caracteres " + conta);
            jLabel_Exibe_Informacao.setText("caracteres " + conta + "/" + Caracteres);
        }
    }

    public void ContaCaracteresEdicao() {
        int Caracteres = 30;
        int conta = jTextField_edicao.getText().length();
        if (conta == 30) {
            jTextField_edicao.setBackground(Color.yellow);
            jLabel_Exibe_Informacao.setText("Limite de caracteres " + conta + "/" + Caracteres);
        } else if (conta > 30) {
            jTextField_edicao.setBackground(Color.red);
            System.out.println("maior " + conta);
            jLabel_Exibe_Informacao.setText("Ultrapassou limite de caracteres " + conta + "/" + Caracteres);
        } else {
            jTextField_edicao.setBackground(Color.white);
            System.out.println("caracteres " + conta);
            jLabel_Exibe_Informacao.setText("caracteres " + conta + "/" + Caracteres);
        }
    }

    public void ContaCaracteresValor() {
        int Caracteres = 30;
        int conta = jTextField_Valor.getText().length();
        if (conta == 30) {
            jTextField_Valor.setBackground(Color.yellow);
            jLabel_Exibe_Informacao.setText("Limite de caracteres " + conta + "/" + Caracteres);
        } else if (conta > 30) {
            jTextField_Valor.setBackground(Color.red);
            System.out.println("maior " + conta);
            jLabel_Exibe_Informacao.setText("Ultrapassou limite de caracteres " + conta + "/" + Caracteres);
        } else {
            jTextField_Valor.setBackground(Color.white);
            System.out.println("caracteres " + conta);
            jLabel_Exibe_Informacao.setText("caracteres " + conta + "/" + Caracteres);
        }
    }

    public void ContaCaracteresDescricao() {
        int Caracteres = 50;
        int conta = jTextField_Desc.getText().length();
        if (conta == 50) {
            jTextField_Desc.setBackground(Color.yellow);
            jLabel_Exibe_Informacao.setText("Limite de caracteres " + conta + "/" + Caracteres);
        } else if (conta > 50) {
            jTextField_Desc.setBackground(Color.red);
            System.out.println("maior " + conta);
            jLabel_Exibe_Informacao.setText("Ultrapassou limite de caracteres " + conta + "/" + Caracteres);
        } else {
            jTextField_Desc.setBackground(Color.white);
            System.out.println("caracteres " + conta);
            jLabel_Exibe_Informacao.setText("caracteres " + conta + "/" + Caracteres);
        }
    }

    public void ContaCaracteresObservacao() {
        int Caracteres = 150;
        int conta = jTextArea_Obs.getText().length();
        if (conta == 150) {
            jTextArea_Obs.setBackground(Color.yellow);
            jLabel_Exibe_Informacao.setText("Limite de caracteres " + conta + "/" + Caracteres);
        } else if (conta > 150) {
            jTextArea_Obs.setBackground(Color.red);
            System.out.println("maior " + conta);
            jLabel_Exibe_Informacao.setText("Ultrapassou limite de caracteres " + conta + "/" + Caracteres);
        } else {
            jTextArea_Obs.setBackground(Color.white);
            System.out.println("caracteres " + conta);
            jLabel_Exibe_Informacao.setText("caracteres " + conta + "/" + Caracteres);
        }
    }

    public void VerificaCor() {
        Color cor = jTextField_Tipo.getBackground();
        if (cor == red) {
            JOptionPane.showMessageDialog(rootPane, "Verifique");
            System.out.println("cor " + cor);
        } else {
            System.out.println("cor " + cor);
            SalvaTemp();
        }
    }

    public void LimpaCampos() {
        this.setTitle("Cadastro Produto");
        // jLabel_Valor.setText("Valor");
        jTextField_Tipo.setText(null);
        jTextField_Tipo.requestFocus();
        jTextField_Desc.setText(null);
        jTextField_edicao.setText(null);
        jTextField_Valor.setText(null);
        jSpinnerNcm.setValue(0);
        jSpinnerCfop.setValue(0);
        jSpinnerEstoqueMinimo.setValue(0);
        jTextArea_Obs.setText(null);
        jLabel_Exibe_Informacao.setText(null);
        jLabel_Saldo_Prod2.setText("  Saldo Produto : Zerado");
        jButton_Excluir.setEnabled(false);
        jComboBox_Unidade.setSelectedItem("UN");
    }

    public void VerificaNumeroNcm() {
        String s;
//        s = jTextField_Ncm.getText().replace(" ", "");
//        if (s.matches("^[0-9.]*$")) {
//            jTextField_Ncm.setBackground(null);
//        } else {
//            jTextField_Ncm.setText(null);
//            jTextField_Ncm.setBackground(Color.RED);
//        }
    }

    public void VerificaNumeroCfop() {
        String s;
//        s = jSpinner2.getText().replace(" ", "");
//        if (s.matches("^[0-9.]*$")) {
//            jSpinner2.setBackground(null);
//        } else {
//            jSpinner2.setText(null);
//            jSpinner2.setBackground(Color.RED);
//        }
    }

    public void RecebeIdProduto(String id) {
        jLabel_Id_Secundario2.setText(id);
        if (id == "novo" | id.equals("novo")) {
//            jLabel_Sistema2.setText(id);
//            JOptionPane.showMessageDialog(rootPane, "qqqqqqqqqqqqqqqqq");
            LimpaCampos();
            BuscaUltimaId();
        } else {
            CarregaDadosDaTabela();
        }
    }

    public void CarregaDadosDaTabela() {
        jButton_Excluir.setEnabled(true);
        conex.conexao();
        conex.executaSql2("  select * from produto inner join unidade on  idunid=id_referenciaunidade  where id_prod = '" + jLabel_Id_Secundario2.getText() + "' order by id_prod  desc");
        try {
            conex.rs.first();
            jComboBox_Unidade.setSelectedItem((conex.rs.getString("sigla_unidade")));
            String id_prod = (conex.rs.getString("id_prod"));
            jTextField_Tipo.setText(conex.rs.getString("tipo_prod"));
            jTextField_Tipo.requestFocus();
            jTextField_Desc.setText(conex.rs.getString("nome_prod"));
            jLabel_Sistema2.setText(conex.rs.getString("sis_prod"));
//            JOptionPane.showMessageDialog(rootPane, (conex.rs.getString("nome_prod")));
            jTextField_edicao.setText(conex.rs.getString("edicao_prod"));
//            String ValorBanco=(conex.rs.getString("valor_prod"));
//            ValorBanco=ValorBanco.replace(title, title)
            Double num41 = (conex.rs.getDouble("valor_prod"));
            BigDecimal df1 = new BigDecimal(num41);
            NumberFormat nf1 = NumberFormat.getInstance();// getCurrencyInstance
            nf1.setMinimumFractionDigits(3);
            nf1.setMaximumFractionDigits(3);
            String FormatoValorProd = nf1.format(df1);;
            FormatoValorProd = "R$ " + FormatoValorProd;
            String valor_prod_ex = (conex.rs.getString("valor_prod_ex"));
            jTextField_Valor.setText(valor_prod_ex);
            System.out.println("Interface.ProdCadastroJIF.CarregaDadosDaTabela()   - FormatoValorProd " + FormatoValorProd + "  valor_prod_ex " + valor_prod_ex);
            try {
                jSpinnerNcm.setValue(conex.rs.getInt("ncm_prod"));
            } catch (SQLException ex) {
                jSpinnerNcm.setValue(0);
            }
            try {
                jSpinnerCfop.setValue(conex.rs.getInt("cfop_prod"));
            } catch (SQLException ex) {
                jSpinnerCfop.setValue(0);
            }
            try {
                jSpinnerEstoqueMinimo.setValue(conex.rs.getFloat("estoque_prod"));
            } catch (SQLException ex) {
                jSpinnerEstoqueMinimo.setValue(1);
            }
            jTextArea_Obs.setText(conex.rs.getString("obs_prod"));
            Double num4 = (conex.rs.getDouble("saldo_prod"));
            BigDecimal df = new BigDecimal(num4);
            NumberFormat nf = NumberFormat.getInstance();
            nf.setMinimumFractionDigits(3);
            nf.setMaximumFractionDigits(3);
            String FormatoReal = nf.format(df);
            FormatoReal = FormatoReal.replace(",000", "");
            jLabel_Saldo_Prod2.setText(" Saldo : " + FormatoReal);
            jTextFieldInsereSaldo.setText(FormatoReal);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            LimpaCampos();
        }
        conex.desconecta();
    }

    public void BuscaUltimaId() {
        conex.conexao();
        conex.executaSql2("select * from produto order by sis_prod  desc ");
        try {
            conex.rs.first();
            NumeroUltimaId = (conex.rs.getInt("sis_prod") + 1);
            UltimaId = String.valueOf(NumeroUltimaId);
            System.out.println("Interface.ProdutoListaJIF.BuscaUltimaId()" + UltimaId);
            jLabel_Sistema2.setText(UltimaId);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoCadastroJIF.class.getName()).log(Level.SEVERE, null, ex);
            UltimaId = "1";
            jLabel_Sistema2.setText(UltimaId);
        }
        conex.desconecta();
    }

//    public void BuscaIdUnidade() {
//        String nome = (String) jComboBox_Unidade.getSelectedItem();
//        conex3.conexao();
//        conex3.executaSql2("SELECT  sigla_unidade,id_unidade, desc_unidade FROM unidade  where stunid =1 and sigla_unidade='" + nome + "'  order by id_referenciaunidade asc  ");
//        try {
//            conex3.rs.first();
//            un_prod = (conex3.rs.getInt("id_unidade"));
//        } catch (SQLException ex) {
//            Logger.getLogger(ProdutoCadastroJIF.class.getName()).log(Level.SEVERE, null, ex);
//            un_prod = 1;
//            System.out.println("---------------- BuscaIdUnidade----------------" + ex);
//        }
//        conex3.desconecta();
//        System.out.println("---------------- BuscaIdUnidade----------------" + un_prod);
//    }
    public void EscondeInsereSaldoInicio() {
        jTextFieldInsereSaldo.setVisible(false);
        jButtonInsereSaldo.setVisible(false);
        jLabel1.setVisible(false);
        jComboBox_Unidade_Int.setVisible(false);
    }

    public void EscondeInsereSaldo() {
        if (jTextFieldInsereSaldo.isVisible()) {
            jTextFieldInsereSaldo.setVisible(false);
            jButtonInsereSaldo.setVisible(false);
            jLabel1.setVisible(false);
        } else {
            jTextFieldInsereSaldo.setVisible(true);
            jButtonInsereSaldo.setVisible(true);
            jLabel1.setVisible(true);
        }

    }

    public void SalvaTemp() {
        if (jLabel_Id_Secundario2.getText() == "novo") {
            BuscaUltimaId();
        } else {

        }
        String MeuValorVerifica = jTextField_Valor.getText();
        if (MeuValorVerifica.isEmpty()) {
            jTextField_Valor.setText("R$ 0,00");
        }

        String TipoProd = jTextField_Tipo.getText(),
                DescProd = jTextField_Desc.getText(),
                NumProd = jTextField_edicao.getText(),
                data_reg = Principal.jLabel_Data.getText(),
                obs_prod = jTextArea_Obs.getText(),
                cfop_prod = "" + jSpinnerCfop.getValue(),
                ncm_prod = "" + jSpinnerNcm.getValue(),
                estoque_prod = "" + jSpinnerEstoqueMinimo.getValue();
        System.out.println("SalvaTemp() " + data_reg);
        TipoProd = TipoProd.toUpperCase();
        DescProd = DescProd.toUpperCase();
        obs_prod = obs_prod.toUpperCase();
        Bprod.setTipo_prod(TipoProd);
        Bprod.setNome_prod(DescProd);
        Bprod.setEdicao_prod(NumProd);
        Bprod.setCfop_prod(cfop_prod);
        Bprod.setData_reg(data_reg);
        Bprod.setNcm_prod(ncm_prod);
        Bprod.setObs_prod(obs_prod);
        if (estoque_prod.equals(null) | estoque_prod.equals("")) {
            estoque_prod = "1";
//            JOptionPane.showMessageDialog(rootPane, "valor =1");
        } else {
            estoque_prod = estoque_prod.replace(",", ".");
        }
        Bprod.setEstoque_prod(Double.parseDouble(estoque_prod));
        System.out.println("Interface.ProdCadastroJIF.SalvaTemp() ---- " + jComboBox_Unidade_Int.getSelectedItem());
        un_prod = Integer.parseInt((String) jComboBox_Unidade_Int.getSelectedItem());
        Bprod.setUn_prod(un_prod);
        String MeuValor = jTextField_Valor.getText();
        Bprod.setValor_ex(MeuValor);
        MeuValor = MeuValor.replace(",", ".").replace("R$", "");
        Bprod.setValor(Double.parseDouble(MeuValor));

        Bprod.setUsu_prod(Principal.jLabelNomeUsuario.getText());// aqui muda  ///   (Principal.jLabel_Usuario.getText())
        Bprod.setStatus_prod(1); // aqui ativo
        Bprod.setHora_reg(Principal.jLabel_Hora.getText());
        int Sis_prod = 0;
//        if (jLabel_Id_Secundario2.getText() == "novo") {
//            System.out.println("erro ao carregar "+jLabel_Id_Secundario2.getText());
//        } else {
        Sis_prod = Integer.parseInt(jLabel_Sistema2.getText());
//        }

        Bprod.setSis_prod(Sis_prod);
        Dprod.Salvar_Temporario(Bprod);
        if (jLabel_Id_Secundario2.getText() == "novo") {
        } else {
            AlterarTemp();
        }
        jTextField_Tipo.requestFocus();//// muda foco      /////// Cria_Registro_Primario
    }

    public void AlterarTemp() {
        Bprod.setStatus_prod(2);// alterado
        Bprod.setId_prod(Integer.parseInt(jLabel_Id_Secundario2.getText()));
        Dprod.Alterar_Atualizar_Temporario(Bprod);

    }

    public void BotaoExcluir() {
        int resposta = 0;
        int Status_Prod = 3; // excluido
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ? ");
        if (resposta == JOptionPane.YES_OPTION) {
            String v = jLabel_Id_Secundario2.getText();
            if (v == "novo" | v.equals("novo")) {
                System.out.println("Interface.Produto.CadastroProdutoJIF.BotaoExcluir()");

            } else {
                this.setTitle("Cadastro Produto");
                Bprod.setStatus_prod(Status_Prod);
                Bprod.setUsu_prod(Principal.jLabelNomeUsuario.getText());
                Bprod.setData_reg(Principal.jLabel_Data.getText());
                Bprod.setHora_reg(Principal.jLabel_Hora.getText());
                Bprod.setId_prod(Integer.parseInt(jLabel_Id_Secundario2.getText()));
                Dprod.Excluir_Atualizar_Temporario(Bprod);

                LimpaCampos();
//                this.setVisible(false);
//                this.dispose();
                Principal.jLabelCodigoTela.setText("FechaCadastroProdutoEditar");
                Principal.jButton1.doClick();
                Principal.jLabelCodigoTela.setText("AtualizaProdutoLista");
                Principal.jButton1.doClick();
            }
        }
    }

    public void ManipulaModoValor() {
        if (IntModoValor == 0) {
            IntModoValor = 1;
            jTextField_Valor.setBackground(Color.ORANGE);
        } else {
            IntModoValor = 0;
            jTextField_Valor.setBackground(Color.white);

        }
    }

    public void ManipulaValor() {
        String MeuValor = jTextField_Valor.getText();
        MeuValor = MeuValor.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        if (MeuValor.equals(null) | MeuValor.equals("") | MeuValor == (null) | MeuValor == " ") {
            System.out.println("Interface.ProdCadastroJIF.ManipulaValor()");
        } else {
            if (IntModoValor == 1) {
                Double num41 = (Double.parseDouble(MeuValor));
                BigDecimal df1 = new BigDecimal(num41);
                NumberFormat nf1 = NumberFormat.getInstance();// getCurrencyInstance
                nf1.setMinimumFractionDigits(4);
                nf1.setMaximumFractionDigits(4);
                String FormatoValorProd = nf1.format(df1);
                FormatoValorProd = "R$ " + FormatoValorProd;
                jTextField_Valor.setText(FormatoValorProd);
            } else {
                Double num42 = (Double.parseDouble(MeuValor));
//                BigDecimal df2 = new BigDecimal(num42);
//                NumberFormat nf2 = NumberFormat.getCurrencyInstance();// getCurrencyInstance
//                String FormatoValorProd = nf2.format(df2);
//                               FormatoValorProd = "R$ " + FormatoValorProd;;
//String a3 = jTextField_Valor.getText();
                Double num4 = Double.parseDouble(MeuValor);
                BigDecimal df = new BigDecimal(num4);
                NumberFormat nf = NumberFormat.getCurrencyInstance();
//        nf.setMaximumFractionDigits(8);
//            if (IntModoValor == 0) {
                String FormatoReal = nf.format(df);
                String b = String.valueOf(df);
                jTextField_Valor.setText(FormatoReal);
//                jCheckBoxMenuItem_ModoValor.setSelected(false);
//            } else {
//                nf.setMinimumFractionDigits(4);
//
//                String formatado = nf.format(df);
//                jTextField_Valor.setText((formatado));
////                jCheckBoxMenuItem_ModoValor.setSelected(true);
//            }

                System.out.println("Interface.ProdCadastroJIF.ManipulaValor()" + MeuValor);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonInsereSaldo;
    private javax.swing.JButton jButtonNovaUnidade;
    private javax.swing.JButton jButtonSalvar;
    public static javax.swing.JButton jButton_Excluir;
    private javax.swing.JComboBox<String> jComboBox_Unidade;
    private javax.swing.JComboBox<String> jComboBox_Unidade_Int;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel_Exibe_Informacao;
    private javax.swing.JLabel jLabel_Guia4;
    public static javax.swing.JLabel jLabel_Id_Secundario2;
    private javax.swing.JLabel jLabel_Saldo_Prod2;
    private javax.swing.JLabel jLabel_Sistema2;
    private javax.swing.JLabel jLabel_Valor2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerCfop;
    private javax.swing.JSpinner jSpinnerEstoqueMinimo;
    private javax.swing.JSpinner jSpinnerNcm;
    private javax.swing.JTextArea jTextArea_Obs;
    private javax.swing.JTextField jTextFieldInsereSaldo;
    private javax.swing.JTextField jTextField_Desc;
    private javax.swing.JTextField jTextField_Tipo;
    private javax.swing.JTextField jTextField_Valor;
    private javax.swing.JTextField jTextField_edicao;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnCampos;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
