/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.internal;

import ConectaBanco.ConexaoBD;
import Interface.Principal;
import ModeloBeans.ModeloTabela;
import ModeloDao.Dao_Unidade;
import UTIL.ControleCores;
import UTIL.DataHoraAtual;
import UTIL.UsuarioLogado;
import controller.UnidadeController;
import dao.UnidadeDao;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Unidade;
import tableModel.UnidadeTableModel;
import view.MenuPrincipal;

/**
 *
 * @author edson
 */
public class UnidadeCadastroJIF extends javax.swing.JInternalFrame {

    Unidade BUnis = new Unidade();
    UnidadeDao DUnid = new UnidadeDao();
    ConexaoBD conex = new ConexaoBD();
    String UltimaId;
    int NumeroUltimaId;

    int id_referencia;
    int id_unidade;
    int flag = 1;

    String MostraTabela = null;
    String ordem = "asc";
    int fragmento = 0;

    /**
     * Creates new form JIFTEste
     */
    private UnidadeController unidadeController;

    public UnidadeCadastroJIF() {
        initComponents();
        remover_Ico();
        unidadeController = new UnidadeController();

        groupFragmentado.add(rbFragmentadoNao);
        groupFragmentado.add(rbFragmentadoSim);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        groupFragmentado = new javax.swing.ButtonGroup();
        pnPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Lista = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        rbFragmentadoSim = new javax.swing.JRadioButton();
        rbFragmentadoNao = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de unidade");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnPrincipal.setBackground(ControleCores.pegarCorPadrao());

        jTable_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ListaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_ListaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Lista);

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de unidades");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(ControleCores.pegarCorPadrao());
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sigla");

        txtSigla.setEnabled(false);
        txtSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSiglaKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descrição");

        txtDescricao.setEnabled(false);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });

        rbFragmentadoSim.setText("sim");
        rbFragmentadoSim.setEnabled(false);
        rbFragmentadoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFragmentadoSimActionPerformed(evt);
            }
        });

        rbFragmentadoNao.setSelected(true);
        rbFragmentadoNao.setText("não");
        rbFragmentadoNao.setEnabled(false);
        rbFragmentadoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFragmentadoNaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jLabel5.setText("Fragmentado");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-novo-24.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-24.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancelar-24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-24.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtSigla, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbFragmentadoSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbFragmentadoNao)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnExcluir, btnNovo, btnSalvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFragmentadoSim)
                    .addComponent(rbFragmentadoNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        unidadeController.novaUnidade(this);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jTable_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ListaMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
        } else {
            if (evt.getClickCount() == 2) {
                flag = 2;
                txtSigla.setEnabled(true);
                txtDescricao.setEnabled(true);
                txtSigla.requestFocus();
                btnSalvar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnNovo.setEnabled(false);
                rbFragmentadoNao.setEnabled(true);
                rbFragmentadoSim.setEnabled(true);
                String TipoUsuario = MenuPrincipal.jLabelTipoUsuario.getText();
                if (TipoUsuario == "Manutenção") {
                    id_unidade = (int) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 0);
                    id_referencia = (int) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 0);
                    txtSigla.setText((String) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 2));
                    txtDescricao.setText((String) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 3));
                } else {
                    id_unidade = (int) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 0);
                    id_referencia = (int) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 0);
                    txtSigla.setText((String) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 1));
                    txtDescricao.setText((String) jTable_Lista.getValueAt(jTable_Lista.getSelectedRow(), 2));
                }
            }
        }
    }//GEN-LAST:event_jTable_ListaMouseClicked

    private void jTable_ListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ListaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_ListaMouseEntered

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (unidadeController.validarEntradas(this) == true) {
            System.out.println("true");
        } else {
            System.out.println("false");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
//            VerificarCamposVazios();
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        PreencheTabelaApagar();
//        flag = 1;
//        btnNovo.setEnabled(true);
//        btnSalvar.setEnabled(false);
//        txtDescricao.setText(null);
//        txtSigla.setText(null);
//        txtSigla.setEnabled(false);
//        txtDescricao.setEnabled(false);
//        btnExcluir.setEnabled(false);
//        rbFragmentadoNao.setEnabled(false);
//        rbFragmentadoSim.setEnabled(false);
        unidadeController.cancelarUnidade(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ? ");
        if (resposta == JOptionPane.YES_OPTION) {
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            txtDescricao.setText(null);
            txtSigla.setText(null);
            txtSigla.setEnabled(false);
            txtDescricao.setEnabled(false);

            BUnis.setRegistro_unidade(Principal.jLabel_Data.getText() + " " + Principal.jLabel_Hora.getText());
            BUnis.setStatus_unidade(3);
            BUnis.setUsuario_unidade(Principal.jLabelNomeUsuario.getText());
            BUnis.setId_unidade(id_unidade);
            DUnid.excluirUnidade(BUnis);
        } else {
        }
        PreencheTabelaApagar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtSiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiglaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtDescricao.requestFocus();
        }
//        VerificarCamposCheios();
    }//GEN-LAST:event_txtSiglaKeyPressed

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnSalvar.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void rbFragmentadoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFragmentadoNaoActionPerformed
        if (rbFragmentadoNao.isSelected()) {
            rbFragmentadoSim.setSelected(false);
        } else {
            rbFragmentadoSim.setSelected(true);
        }
    }//GEN-LAST:event_rbFragmentadoNaoActionPerformed

    private void rbFragmentadoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFragmentadoSimActionPerformed
        if (rbFragmentadoSim.isSelected()) {
            rbFragmentadoNao.setSelected(false);
        } else {
            rbFragmentadoNao.setSelected(true);
        }
    }//GEN-LAST:event_rbFragmentadoSimActionPerformed

    public void EventoLimpar() {
//        jTextFieldBusca.setText("");
//        jTextFieldBusca.requestFocus();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
//        jTable_Produto.setModel(modelo);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void remover_Ico() {
        this.setFrameIcon(null);

        // hack to remove system menu in Windows
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
    }

    public void BuscaUltimaId() {
        conex.conexao();
        conex.executaSql2("select * from produto order by sis_prod  desc ");
        try {
            conex.rs.first();
            NumeroUltimaId = (conex.rs.getInt("sis_prod") + 1);
            UltimaId = String.valueOf(NumeroUltimaId);
            System.out.println("Interface.ProdutoListaJIF.BuscaUltimaId()" + UltimaId);
//            jLabel_Sistema2.setText(UltimaId);
        } catch (SQLException ex) {
            Logger.getLogger(UnidadeCadastroJIF.class.getName()).log(Level.SEVERE, null, ex);
            UltimaId = "1";
        }
        conex.desconecta();
    }

    public void PreencheTabelaApagar() {
        String TipoUsuario = MenuPrincipal.jLabelTipoUsuario.getText();
        if (TipoUsuario == "Manutenção") {
            PreencheTabela3();
        } else {
            PreencheTabela();
        }

    }

    public void PreencheTabela() {

        Dao_Unidade d = new Dao_Unidade();

        UnidadeTableModel modelo = new UnidadeTableModel();
        List<Unidade> unidades = d.listarUnidades();
        modelo.setUnidades(unidades);

        jTable_Lista.setModel(modelo);
        jTable_Lista.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable_Lista.getColumnModel().getColumn(0).setResizable(true);

        jTable_Lista.getTableHeader().setReorderingAllowed(false);
//        jTable_Lista.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable_Lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void PreencheTabela3() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Codigo", "Status", "Sigla", "Fragmentado", "Descrição", "Registro", "Usuario", "Id"};
        String MostraTabela;
        String ordem = null;
        MostraTabela = "ATIVO";

        conex.conexao();

        if (ordem.equals("asc")) {
            conex.executaSql2("SELECT stunid,id_unidade, id_referenciaunidade, sigla_unidade, desc_unidade, registro_unidade, \n"
                    + "       usuario_unidade,fragmento_unidade\n"
                    + "  FROM unidade   order by id_referenciaunidade asc ");
        } else {
            conex.executaSql2("SELECT stunid,id_unidade, id_referenciaunidade, sigla_unidade, desc_unidade, registro_unidade, \n"
                    + "       usuario_unidade,fragmento_unidade\n"
                    + "  FROM unidade order by id_referenciaunidade desc ");
        }
        try {
            conex.rs.first();
            do {
                int VerFrag = 0;
                String FragNome;
                String statusex;
                int status;
                status = conex.rs.getInt("stunid");
                if (status == 1) {
                    statusex = "ATIVO";
                } else if (status == 2) {
                    statusex = "ALTERADO";
                } else if (status == 3) {
                    statusex = "EXCLUIDO";
                } else {
                    statusex = "INDEFINIDO";
                }
                VerFrag = conex.rs.getInt("fragmento_unidade");
                if (VerFrag == 0) {
                    FragNome = "NÃO";
                } else {
                    FragNome = "SIM";
                }
                dados.add(new Object[]{conex.rs.getInt("id_referenciaunidade"), statusex,
                    conex.rs.getString("sigla_unidade"), conex.rs.getString("desc_unidade"), FragNome,
                    conex.rs.getString("registro_unidade"), conex.rs.getString("usuario_unidade"), conex.rs.getInt("id_unidade")});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            Logger.getLogger(UnidadeCadastroJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTable_Lista.setModel(modelo);
        jTable_Lista.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable_Lista.getColumnModel().getColumn(0).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable_Lista.getColumnModel().getColumn(1).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(2).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(3).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(4).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(5).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTable_Lista.getColumnModel().getColumn(6).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(7).setPreferredWidth(00);
        jTable_Lista.getColumnModel().getColumn(7).setResizable(true);
        jTable_Lista.getTableHeader().setReorderingAllowed(false);
        jTable_Lista.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable_Lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();

    }

//    public void VerificarCamposVazios() {
//        VerificarCamposCheios();
//        if (txtDescricao.getText().isEmpty() | txtSigla.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(rootPane, "Campo(s) vazio(s)");
//        } else {
//            EventoSalvar();
//        }
//    }
//
//    public void VerificarCamposCheios() {
//
//        if (txtSigla.getText().length() >= 5) {
//            txtSigla.setText(null);
//            txtSigla.requestFocus();
//        }
//        if (txtDescricao.getText().length() >= 11) {
//            txtDescricao.setText(null);
//            txtDescricao.requestFocus();
//        }
//
//    }
    public void EventoSalvar() {
        txtSigla.setText(txtSigla.getText().toUpperCase());
        txtDescricao.setText(txtDescricao.getText().toUpperCase());
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtSigla.setEnabled(false);
        txtDescricao.setEnabled(false);
        rbFragmentadoNao.setEnabled(false);
        rbFragmentadoSim.setEnabled(false);

        if (flag == 2) {
//            BUnis.setId_unidade(id_unidade);
//            BUnis.setStatus_unidade(2);
//            DUnid.alterarUnidade(BUnis);
        } else {
            System.out.println("Interface.UnidadeCadastroJIF.EventoSalvar() sem id " + id_unidade);
        }

        unidadeController.salvarUnidade(this);

        PreencheTabelaApagar();
        txtDescricao.setText(null);
        txtSigla.setText(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup groupFragmentado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Lista;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JRadioButton rbFragmentadoNao;
    private javax.swing.JRadioButton rbFragmentadoSim;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnNovo() {
        return btnNovo;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JRadioButton getRbFragmentadoNao() {
        return rbFragmentadoNao;
    }

    public JRadioButton getRbFragmentadoSim() {
        return rbFragmentadoSim;
    }

    public JTextField getTxtDescricao() {
        return txtDescricao;
    }

    public JTextField getTxtSigla() {
        return txtSigla;
    }

    public void setRbFragmentadoNao(JRadioButton rbFragmentadoNao) {
        this.rbFragmentadoNao = rbFragmentadoNao;
    }

    public void setRbFragmentadoSim(JRadioButton rbFragmentadoSim) {
        this.rbFragmentadoSim = rbFragmentadoSim;
    }

    public void setTxtDescricao(JTextField txtDescricao) {
        this.txtDescricao = txtDescricao;
    }

    public void setTxtSigla(JTextField txtSigla) {
        this.txtSigla = txtSigla;
    }

    public ButtonGroup getGroupFragmentado() {
        return groupFragmentado;
    }

    public int getId_unidade() {
        return id_unidade;
    }

    public void setId_unidade(int id_unidade) {
        this.id_unidade = id_unidade;
    }

    public void setTxtSigla(String string) {
        if (txtSigla != null) {
            txtSigla.setText(string);
        }
    }

    public void setTxtDescricao(String string) {
        if (txtDescricao != null) {
            txtDescricao.setText(string);
        }
    }

    public JTable getjTable_Lista() {
        return jTable_Lista;
    }

    public void setjTable_Lista(JTable jTable_Lista) {
        this.jTable_Lista = jTable_Lista;
    }

}
